packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-data-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1791
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): support array parameters of mulit sort

packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1768
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:reuse-tab): fix remove tab when reuse is `false`

packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1792
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix reset pi is 1 when confirm filter

.github/semantic.yml, packages/abc/loading/loading.component.ts, packages/abc/loading/loading.service.ts, src/app/shared/shared-delon.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: fix loading

.github/semantic.yml, docs/upgrade-v10.en-US.md, docs/upgrade-v10.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.0.0-beta.3): 10.0.0-beta.3

packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/reuse-tab.component.ts, packages/abc/reuse-tab/reuse-tab.interfaces.ts, packages/abc/reuse-tab/reuse-tab.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1803
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:reuse-tab): add type of `_onReuseInit`

docs/getting-started.zh-CN.md, docs/server.en-US.md, docs/server.zh-CN.md, packages/schematics/docs/plugin.en-US.md, packages/schematics/docs/plugin.zh-CN.md, packages/schematics/ng-add/schema.json, src/app/layout/header/header.component.html, src/app/shared/components/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs:  update server

packages/form/src/widgets/string/string.widget.spec.ts, packages/form/src/widgets/string/string.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1806
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:widget:string): fix `autofocus` compatibility

src/app/shared/components/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: add beian

packages/schematics/application/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix lose `</div>` in index.html

packages/abc/st/st.component.html
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:st): add link title when type is link

packages/abc/down-file/down-file.directive.ts, packages/abc/down-file/down-file.spec.ts, packages/abc/down-file/index.en-US.md, packages/abc/down-file/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1808
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:down-file): add `pre` property

packages/form/src/widgets/radio/radio.widget.html
- close https://github.com/ng-alain/ng-alain/issues/1810
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form:radio): fix can't disabled item

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/public_api.ts, packages/abc/st/st-column-source.ts, packages/abc/st/st-data-source.ts, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st-data-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1811
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:st): add `className` of button

packages/schematics/application/index.ts, packages/schematics/ng-add/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(cli): use cnpm to interrupt the installation

package.json, packages/form/src/config.ts, packages/form/src/widget.ts, packages/form/src/widgets/date/index.en-US.md, packages/form/src/widgets/date/index.zh-CN.md, packages/theme/system/delon/_sf.less, src/app/core/code/code.service.ts, src/app/core/code/files/global-config.module.ts, src/demo.component.ts
fix(form): fix invlid week
- close https://github.com/ng-alain/ng-alain/issues/1813
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form:object): fix misalignment

package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.0.0-beta.4): release 10.0.0-beta.4

packages/theme/src/services/menu/menu.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1824
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:menu): fix processed logically of `setItem` method

packages/abc/sidebar-nav/sidebar-nav.component.ts
=> fix(abc:sidebar-nav): fix space to avoid scroll

packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/lifecycle_hooks.ts, packages/abc/reuse-tab/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:reuse-tab): add lifecycle hook interfaces

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: remove deprecated

packages/abc/st/demo/resizable.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/st.module.ts, packages/abc/st/style/index.less, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st.spec.ts, src/styles.less
- close https://github.com/ng-alain/ng-alain/issues/1290
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): support resizable headers

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-column-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1076
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): support TemplateRef of render & renderTitle

package.json, packages/form/src/widgets/upload/schema.ts, packages/schematics/application/files/src/app/routes/routes.module.ts, packages/schematics/application/index.ts, packages/schematics/edit/index.spec.ts, packages/schematics/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.ts, packages/schematics/view/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: change `extends` from `tsconfig.base.json` to `tsconfig.json`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, docs/upgrade-v10.en-US.md, docs/upgrade-v10.zh-CN.md, package.json, packages/schematics/application/index.ts, packages/schematics/utils/json.ts, scripts/ci/build-schematics.sh
- close https://github.com/ng-alain/ng-alain/issues/1733
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.0.0): release 10.0.0

packages/abc/date-picker/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: typo index.zh-CN.md

packages/abc/st/st.component.ts, packages/abc/st/test/st.spec.ts, src/app/layout/header/header.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1836
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix blank area in virtual scroll

packages/abc/reuse-tab/reuse-tab.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1837
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:reuse-tab): fix invalid this scope of hook events

packages/abc/st/st-data-source.ts, packages/abc/st/test/st-data-source.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix http params

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.0.2): release 10.0.2

packages/abc/sidebar-nav/sidebar-nav.component.ts, packages/abc/sidebar-nav/sidebar-nav.types.ts, packages/abc/st/st-column-source.ts, packages/abc/st/st.interfaces.ts, packages/acl/src/acl.type.ts, packages/chart/single-bar/index.md, packages/theme/src/services/menu/interface.ts, packages/theme/src/services/menu/menu.service.spec.ts, packages/theme/src/services/menu/menu.service.ts, packages/util/src/config/acl/acl.type.ts
- close https://github.com/ng-alain/ng-alain/issues/1843
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> perf: optimize `acl` type

packages/chart/gauge/gauge.component.ts, packages/chart/mini-area/mini-area.component.ts, packages/chart/mini-bar/mini-bar.component.ts, packages/chart/pie/pie.component.ts, packages/chart/radar/radar.component.ts, packages/chart/single-bar/single-bar.component.ts, packages/chart/timeline/timeline.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1849
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(g2:*): fix view can't be refresh when the data structure changed

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.0.3): release 10.0.3

packages/theme/docs/tools.en-US.md, packages/theme/docs/tools.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
提升部分文档的阅读性
```
[ ] Yes
[x] No
```
=> docs: improved the reading experience of some docs

packages/abc/se/se.component.html
- close https://github.com/ng-alain/ng-alain/issues/1855
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:se): fix invalid error style

packages/form/src/widgets/date/date.widget.html, packages/form/src/widgets/date/index.en-US.md, packages/form/src/widgets/date/index.zh-CN.md, packages/form/src/widgets/date/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/1854
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(module:sf:date): add `nzInputReadOnly` property

packages/chart/timeline/timeline.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1790
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(chart:timeline): can't change line when click legend

packages/theme/system/delon/_sf.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix misalignment of inline mode

packages/abc/se/demo/complex.md, packages/abc/se/index.en-US.md, packages/abc/se/index.zh-CN.md, packages/abc/se/se.component.html, packages/abc/se/se.component.ts, packages/abc/sv/demo/fixed.md, packages/abc/sv/index.en-US.md, packages/abc/sv/index.zh-CN.md, packages/abc/sv/sv.component.html, packages/abc/sv/sv.component.ts, packages/form/src/schema/ui.ts, packages/form/src/sf-item-wrap.component.html, packages/form/src/widgets/string/demo/simple.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:se,sv,form): add `optionalHelpColor`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.1.0): release 10.1.0

packages/form/src/sf-item-wrap.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): fix invalid error style

packages/form/src/sf.component.ts, packages/form/src/utils.ts
- close https://github.com/ng-alain/ng-alain/issues/1858
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix invalid condition in array

packages/form/src/sf-item.component.ts, packages/form/src/sf.component.ts, packages/form/src/widgets/array/array.widget.ts, packages/theme/system/delon/_sf.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): pref style in small screen

packages/abc/count-down/count-down.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:count-down): fix timestamp of number type

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.1.1): release 10.1.1

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/test/st-data-source.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix don't interrupt when invalid get data

packages/abc/st/st-column-source.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf(abc:st): optimize reminder text

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, docs/upgrade-v10.en-US.md, docs/upgrade-v10.zh-CN.md, package.json, scripts/publish/npm-deprecate.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(10.1.2): release 10.1.2

packages/form/docs/schema.en-US.md, packages/form/docs/schema.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1867
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: update condition

packages/schematics/application/index.ts, packages/schematics/core/lang.config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(cli): more friendly

packages/util/src/array/array.service.spec.ts, packages/util/src/array/array.service.ts, packages/util/src/array/index.en-US.md, packages/util/src/array/index.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(util:array): fix non-empty root parent id value should be return empty array

package.json, packages/abc/ng-package.json, packages/abc/package.json, packages/abc/xlsx/index.en-US.md, packages/abc/xlsx/index.zh-CN.md, packages/abc/xlsx/package.json, packages/abc/xlsx/xlsx.service.ts, packages/abc/xlsx/xlsx.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1868
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:xlsx): support utf8 file format

azure-pipelines.yml, docs/getting-started.en-US.md, docs/getting-started.zh-CN.md, package.json, packages/util/src/time/time.spec.ts, packages/util/src/time/time.ts, scripts/ci/build-artifacts.sh, scripts/ci/build-schematics.sh, scripts/ci/build.sh, scripts/publish/publish-scaffold.js, scripts/publish/publish.js, scripts/publish/publish.sh
- close https://github.com/ng-alain/ng-alain/issues/1870
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(util:time): fix invalid format `toDate`

packages/form/src/widgets/textarea/demo/simple.md, packages/form/src/widgets/textarea/index.en-US.md, packages/form/src/widgets/textarea/index.zh-CN.md, packages/form/src/widgets/textarea/schema.ts, packages/form/src/widgets/textarea/textarea.widget.html, packages/form/src/widgets/textarea/textarea.widget.spec.ts, packages/form/src/widgets/textarea/textarea.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1874
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form:textarea): add `change`, `focus`, `blur` events

packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/1880
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(sf): Allow use of `setVisible` method

packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/1879
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(sf): fix invalid empty value of `pathValue` property

docs/new-page.en-US.md, docs/new-page.zh-CN.md, packages/schematics/module/index.spec.ts, packages/schematics/module/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cli:module): feat auto import routing module to top routing module

packages/theme/layout-default/layout.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme:layout-default): add `nav` property

packages/schematics/application/index.ts, scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): remove tslint-language-service depend

.github/workflows/ssr.yml, Dockerfile.docs, package.json, packages/abc/pdf/pdf.component.ts, packages/form/src/widgets/custom/demo/simple.md, scripts/ci/build-artifacts-site-ssr.sh, src/app/layout/header/header.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: fix version

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.0.1): release 11.0.1

packages/cache/src/cache.spec.ts, packages/theme/src/services/http/http.client.ts, packages/theme/src/services/http/http.spec.ts, packages/theme/src/services/http/index.en-US.md, packages/theme/src/services/http/index.zh-CN.md, src/app/routes/home/home.component.html, src/styles/_home.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:_HttpClient): fix load status allow multiple requests

scripts/ci/build-schematics.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli:ng-add): include color.less & theme css files

packages/form/src/widgets/select/demo/search.md, packages/form/src/widgets/select/index.en-US.md, packages/form/src/widgets/select/index.zh-CN.md, packages/form/src/widgets/select/schema.ts, packages/form/src/widgets/select/select.widget.html, packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1890
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf:select): fix invalid loading status

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.0.2): release 11.0.2

scripts/build/copy-less.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix theme build

packages/auth/src/token/token.service.spec.ts, packages/auth/src/token/token.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1893
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(auth): fix always trigger refresh event in jwt

packages/form/src/sf.component.ts, src/app/app.module.ts, src/app/global-config.module.ts, src/app/layout/header/header.component.html, src/app/layout/header/header.component.ts, src/app/layout/header/search-box.component.ts, src/dev/dev.module.ts, src/dev/layout.component.ts, src/dev/list/layout.component.ts, src/dev/list/list-item.component.ts, src/dev/list/list.component.ts, src/dev/list/list.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1887
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: update document

packages/abc/st/demo/edit-row.md, packages/abc/st/demo/render.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.ts, packages/abc/st/test/st.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): support item type of `setRow`

packages/schematics/docs/plugin.en-US.md, packages/schematics/docs/plugin.zh-CN.md, packages/schematics/plugin/plugin.icon.spec.ts, packages/schematics/plugin/plugin.icon.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli:plugin:icon): fix support conditional expression

packages/abc/st/demo/edit-row.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.ts, packages/abc/st/test/st.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `pureList` method

scripts/ci/utils.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix invalid version number of `screenfull`

packages/theme/layout-blank/style/_layout.less, packages/theme/layout-default/style/_layout.less, packages/theme/system/mixins/_router.less, packages/theme/system/mixins/index.less, packages/theme/system/ng/_router.less, packages/theme/system/ng/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme): fix router animation when changed

packages/chart/number-info/demo/basic.md, packages/chart/number-info/demo/multiple.md, packages/chart/number-info/demo/theme.md, packages/chart/number-info/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(chart:number-info): support multiple style

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.2.0): release 11.2.0

packages/theme/docs/global.en-US.md, packages/theme/docs/global.zh-CN.md, packages/theme/system/mixins/_router.less, packages/theme/system/theme-default.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme): fix router animation is optional

package.json, src/app/app.module.ts, src/app/core/error-handler.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix error to google

packages/form/src/widgets/time/time.widget.html
- close https://github.com/ng-alain/ng-alain/issues/1913
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf:widget:time): fix lose placeholder

package.json, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> build: fix ng-zorro-antd 11.1.0

packages/form/src/widgets/date/date.widget.html, packages/form/src/widgets/number/number.widget.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix missing id association

packages/abc/sv/demo/basic.md, packages/abc/sv/index.en-US.md, packages/abc/sv/index.zh-CN.md, packages/abc/sv/public_api.ts, packages/abc/sv/style/index.less, packages/abc/sv/sv-value.component.ts, packages/abc/sv/sv.component.ts, packages/abc/sv/sv.module.ts, packages/abc/sv/sv.spec.ts, packages/abc/theme-default.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:sv): add `sv-value` component

packages/form/src/model/array.property.ts, packages/form/src/widgets/array/array.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1916
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf:widget:array): fix invalid `minItems`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.3.0): release 11.3.0

packages/form/src/widgets/select/index.en-US.md, packages/form/src/widgets/select/index.zh-CN.md, packages/form/src/widgets/select/schema.ts, packages/form/src/widgets/select/select.widget.html, packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1918
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(sf:widget:select): add `showArrow` property

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.3.1): release 11.3.1

packages/abc/st/st.component.ts, packages/abc/st/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1923
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix to top can't working

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1921
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `showHeader` property

packages/theme/layout-default/style/fix/_sidebar-nav.less, packages/theme/system/widgets/_half-float.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix: fix less4

packages/schematics/ng-update/upgrade-rules/v11/hmr.ts
- https://github.com/ng-alain/ng-alain/issues/1863
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli:ng-update): Cannot read property 'configurations' of undefined

packages/theme/src/services/http/http.client.ts
- close https://github.com/ng-alain/ng-alain/issues/1928
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:_HttpClient): fix count when subscribed

packages/util/array/array.service.ts, packages/util/pipes/filter/demo/filter.md, packages/util/pipes/filter/filter.pipe.spec.ts, packages/util/pipes/filter/filter.pipe.ts, packages/util/pipes/filter/index.en-US.md, packages/util/pipes/filter/index.ts, packages/util/pipes/filter/index.zh-CN.md, packages/util/pipes/filter/module.ts, packages/util/pipes/filter/package.json, packages/util/pipes/index.ts, src/app/shared/shared-delon.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util:pipes): add `filter` pipe

packages/abc/st/demo/sort.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.interfaces.ts, packages/util/array/array-type.service.ts, packages/util/array/array.service.spec.ts, packages/util/array/array.service.ts
- supportt data type of `ArrayService`
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat: support data type of `STColumn`

packages/abc/highlight/demo/simple.md, packages/abc/highlight/index.en-US.md, packages/abc/highlight/index.zh-CN.md, src/app/shared/shared-zorro.module.ts, src/site.config.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:highlight): add `highlight` component

packages/abc/auto-focus/auto-focus.directive.spec.ts, packages/abc/auto-focus/auto-focus.directive.ts, packages/abc/auto-focus/auto-focus.module.ts, packages/abc/auto-focus/demo/simple.md, packages/abc/auto-focus/index.en-US.md, packages/abc/auto-focus/index.ts, packages/abc/auto-focus/index.zh-CN.md, packages/abc/auto-focus/package.json, src/app/shared/shared-delon.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:auto-focus): add `auto-focus` component

packages/abc/global-footer/global-footer.component.ts, packages/abc/global-footer/global-footer.spec.ts, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.service.ts, packages/abc/sidebar-nav/sidebar-nav.component.ts, packages/abc/sidebar-nav/sidebar-nav.spec.ts, packages/theme/layout-default/layout-nav.component.ts, packages/theme/src/win_tokens.ts, packages/util/index.ts, packages/util/token/index.en-US.md, packages/util/token/index.ts, packages/util/token/index.zh-CN.md, packages/util/token/package.json, packages/util/token/page-visibility.spec.ts, packages/util/token/page-visibility.ts, packages/util/token/window.spec.ts, packages/util/token/window.ts, packages/util/tsconfig.json, packages/util/tsconfig.lib.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(util:token): add tokens

packages/util/array/array.service.spec.ts, packages/util/array/array.service.ts, packages/util/array/index.en-US.md, packages/util/array/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util:ArrayService): add `findTree` method

packages/abc/auto-focus/auto-focus.directive.spec.ts, packages/abc/auto-focus/auto-focus.directive.ts, packages/abc/auto-focus/index.en-US.md, packages/abc/auto-focus/index.zh-CN.md, packages/abc/loading/loading.spec.ts, packages/abc/st/index.en-US.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:auto-focus): add `delay` property

packages/abc/sidebar-nav/sidebar-nav.spec.ts, packages/form/src/sf.component.ts, packages/theme/src/services/http/http.spec.ts, packages/util/other/deep.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: types

packages/abc/st/demo/contextmenu.md, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.config.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st-data-source.spec.ts, packages/abc/st/test/st.spec.ts
- close #1168
- close https://github.com/ng-alain/ng-alain/issues/1473
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `contextmenu` property

packages/abc/date-picker/date-picker.module.ts, packages/abc/date-picker/demo/basic.md, packages/abc/date-picker/demo/shortcut.md, packages/abc/date-picker/public_api.ts, packages/abc/date-picker/range-shortcut.component.ts, packages/abc/date-picker/range.component.ts, packages/abc/date-picker/range.directive.spec.ts, packages/abc/date-picker/range.directive.ts, packages/util/config/abc/date-picker.type.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(abc:range-picker): refactor range-picker

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, packages/abc/date-picker/index.en-US.md, packages/abc/date-picker/index.zh-CN.md, packages/abc/date-picker/range.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.6.0): release 11.6.0

packages/util/array/array.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(util:ArrayService): fix cancel return readonly of `flat`, `uniq`

packages/chart/trend/trend.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(chart:trend): fix data flag of html attribute

packages/chart/trend/trend.component.html, packages/chart/trend/trend.component.ts, packages/chart/trend/trend.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix trend

packages/abc/image/demo/preview.md, packages/abc/image/image.directive.ts, packages/abc/image/image.module.ts, packages/abc/image/image.spec.ts, packages/abc/image/index.en-US.md, packages/abc/image/index.zh-CN.md, packages/abc/loading/loading.spec.ts, packages/abc/notice-icon/notice-icon.spec.ts, packages/form/spec/base.spec.ts, packages/testing/public_api.ts, packages/testing/src/cdk-overlay.ts, packages/util/config/abc/image.type.ts
- close https://github.com/ng-alain/ng-alain/issues/1931
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:_src): add `previewSrc` property

packages/util/form/index.en-US.md, packages/util/form/index.ts, packages/util/form/index.zh-CN.md, packages/util/form/match-control.spec.ts, packages/util/form/match-control.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util:form): add `MatchControl`

packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.component.ts, packages/abc/reuse-tab/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1934
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:reuse-tab): add `disabled` property

packages/abc/st/st-export.ts, packages/abc/st/test/st-export.spec.ts
-  close  https://github.com/ng-alain/ng-alain/issues/1933
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix data should be converted

packages/abc/st/st.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix `columns` can't be re-specified when call export Excel

packages/theme/public_api.ts, packages/theme/src/config.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:theme): add environment type

packages/theme/src/services/i18n/i18n.ts, src/app/app.component.ts, src/app/app.module.ts, src/app/core/i18n/service.ts, src/app/core/meta.service.ts, src/app/layout/header/header.component.html, src/app/layout/header/header.component.ts, src/app/layout/header/search-box.component.html, src/app/layout/header/search-box.component.ts, src/app/layout/layout.component.ts, src/app/routes/form-pages/validator/validator.component.html, src/app/shared/components/code-box/code-box.component.html, src/app/shared/components/docs/docs.component.html, src/app/shared/components/docs/docs.component.ts, src/app/shared/components/edit-button/edit-button.component.ts, src/app/shared/components/footer/footer.component.html, src/app/shared/shared.module.ts
…nI18NService`
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:theme:i18n): fix losing `defaultLang`, `currentLang` in `AlainI18NService`

packages/form/src/widgets/date/date.widget.spec.ts, packages/form/src/widgets/date/date.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1938
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form:widget:date): fix invalid default value when mode is `range`

packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/reuse-tab.component.html, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:reuse-tab): add `titleRender` property

packages/abc/let/demo/async.md, packages/abc/let/demo/simple.md, packages/abc/let/index.en-US.md, packages/abc/let/index.ts, packages/abc/let/index.zh-CN.md, packages/abc/let/let.directive.ts, packages/abc/let/let.module.ts, packages/abc/let/let.spec.ts, packages/abc/let/package.json, src/app/core/code/files/delon-abc.module.ts, src/app/shared/shared-delon.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:let): add `let` directive

angular.json, package.json, packages/form/docs/getting-started.en-US.md, packages/form/docs/getting-started.zh-CN.md, packages/form/src/validator.factory.ts, packages/schematics/application/index.ts, packages/schematics/migration.json, packages/schematics/ng-update/index.ts, packages/schematics/ng-update/upgrade-rules/v117/index.spec.ts, packages/schematics/ng-update/upgrade-rules/v117/index.ts, packages/schematics/utils/versions.ts, packages/util/config/sf/sf.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): Upgrade `ajv` to `7.x`

docs/import.en-US.md, docs/import.zh-CN.md, packages/abc/pdf/index.en-US.md, packages/abc/pdf/index.zh-CN.md, packages/abc/qr/index.en-US.md, packages/abc/qr/index.zh-CN.md, packages/schematics/ng-update/upgrade-rules/v117/index.spec.ts, packages/schematics/ng-update/upgrade-rules/v117/index.ts, packages/schematics/test.ts, packages/schematics/utils/package.ts, packages/util/config/abc/qr.type.ts, src/app/core/code/code.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: remove qrious lib of cli

_mock/user.ts, packages/mock/src/interface.ts, packages/mock/src/mock.module.ts, packages/mock/src/mock.service.spec.ts, packages/mock/src/mock.service.ts, packages/theme/src/config.ts, packages/util/config/mock/mock.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(mock): add `setData` in `MockService`

packages/typings.d.ts, packages/util/other/assert.spec.ts, packages/util/other/assert.ts, packages/util/other/logger.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> perf: use `ngDevMode` to tree-shake errors

packages/schematics/application/index.ts, packages/schematics/ng-update/upgrade-rules/v11/index.ts, packages/schematics/ng-update/upgrade-rules/v117/index.ts, packages/schematics/utils/versions.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: optimize cli

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.7.0): release 11.7.0

packages/abc/avatar-list/avatar-list.component.ts, packages/abc/down-file/down-file.directive.ts, packages/abc/let/let.directive.ts, packages/abc/notice-icon/index.en-US.md, packages/abc/notice-icon/index.zh-CN.md, packages/abc/notice-icon/notice-icon.component.html, packages/abc/notice-icon/notice-icon.component.ts, packages/abc/page-header/page-header.component.html, packages/abc/page-header/page-header.component.ts, packages/abc/se/se-container.component.ts, packages/abc/se/se.component.ts, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/sv/index.en-US.md, packages/abc/sv/index.zh-CN.md, packages/abc/sv/sv-container.component.ts, packages/abc/sv/sv-value.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf(module:*): coerces `number` or `boolean` type in `strictTemplates`

packages/form/examples/modal/demo/simple.md, packages/form/src/module.ts, packages/form/src/sf.component.ts, packages/form/src/validator.factory.ts, src/app/shared/components/dialog/sf.component.ts, src/app/shared/index.ts, src/app/shared/shared.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1945
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf): fix can't compile in `strict` of ajv

packages/chart/core/public_api.ts, packages/chart/core/utils.ts, packages/chart/mini-area/mini-area.component.ts, packages/chart/mini-bar/mini-bar.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(chart:mini-area,mini-bar): fix offset when tooltipType is 'mini'

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, packages/schematics/application/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.7.1): release 11.7.1

packages/abc/onboarding/onboarding.component.html, packages/abc/onboarding/onboarding.component.ts, packages/abc/onboarding/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(module:onboarding): fix closed mask when click target element

packages/abc/st/st-data-source.ts, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st-data-source.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> perf(abc:st): optimize the button text performance of rendered

packages/abc/st/st-column-source.ts, packages/abc/st/st.types.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix always fixed column in group header

packages/abc/ng-package.json, packages/acl/ng-package.json, packages/auth/ng-package.json, packages/cache/ng-package.json, packages/chart/ng-package.json, packages/form/ng-package.json, packages/mock/ng-package.json, packages/theme/ng-package.json, packages/util/ng-package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: fix "whitelistedNonPeerDependencies" is deprecated

packages/theme/src/services/settings/settings.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:SettingsService): support generic

packages/abc/media/media.component.ts, packages/abc/pdf/pdf.component.ts, packages/abc/xlsx/xlsx.service.ts, packages/abc/zip/zip.service.ts, packages/chart/core/g2.base.component.ts, packages/theme/layout-default/layout-nav.component.ts, packages/theme/setting-drawer/setting-drawer.component.ts, packages/util/decorator/index.en-US.md, packages/util/decorator/index.ts, packages/util/decorator/index.zh-CN.md, packages/util/decorator/zone-outside.spec.ts, packages/util/decorator/zone-outside.ts, src/app/routes/home/home.component.ts, src/app/shared/components/footer/footer.component.ts, src/dev/layout.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util): add `ZoneOutside`, `ZoneRun` decorator

packages/theme/system/antd/_table.less
- close https://github.com/ng-alain/ng-alain/issues/1951
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix style misalignment in small screen when set scroll

packages/form/src/validator.factory.ts
- close https://github.com/ng-alain/ng-alain/issues/1947
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix stack error when `enum` is large data

packages/abc/down-file/down-file.spec.ts, packages/abc/image/image.spec.ts, packages/abc/st/test/st.spec.ts, packages/theme/src/services/http/http.client.ts, packages/theme/src/services/http/http.spec.ts
…or of loading
- close https://github.com/ng-alain/ng-alain/issues/1954
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:_HttpClient): fix ExpressionChangedAfterItHasBeenCheckedError of loading

packages/abc/page-header/page-header.spec.ts, packages/theme/layout-default/layout.component.spec.ts, packages/theme/src/services/settings/index.en-US.md, packages/theme/src/services/settings/index.zh-CN.md, packages/theme/src/services/settings/settings.service.ts, packages/theme/src/services/settings/settings.spec.ts, packages/theme/src/theme.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1955
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat: optimize Keys configurable

packages/form/src/widgets/select/select.widget.html
- close https://github.com/ng-alain/ng-alain/issues/1953
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf:widget:select): fix invalid `showSearch`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.8.0): release 11.8.0

packages/form/src/module.ts, src/app/core/code/files/delon-abc.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> chore: fix site in stackblitz

packages/form/spec/form.spec.ts, packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/1959
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix invalid parament in error string

packages/theme/system/antd/_table.less
- close https://github.com/ng-alain/ng-alain/issues/1962
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix style misalignment in small screen

packages/abc/st/st-data-source.ts
- close https://github.com/ng-alain/ng-alain/issues/1963
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix avoid dirty button of `iif`

packages/abc/pdf/pdf.component.ts, packages/util/decorator/zone-outside.ts
- close https://github.com/ng-alain/ng-alain/issues/1960
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:pdf): fix selection content is misplaced

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.8.1): release 11.8.1

package.json, packages/form/docs/schema.en-US.md, packages/form/docs/schema.zh-CN.md, packages/form/src/schema/index.ts, packages/form/src/widgets/string/demo/simple.md
- close https://github.com/ng-alain/ng-alain/issues/1973
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: add regex demo

packages/theme/theme-btn/theme-btn.component.ts, packages/theme/theme-btn/theme-btn.module.ts
-  close  https://github.com/ng-alain/ng-alain/issues/1971/
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:theme-btn): optimize Keys of storage

packages/util/config/util/currency.type.ts, packages/util/format/currency.service.spec.ts, packages/util/format/currency.service.ts, packages/util/format/currency.types.ts, packages/util/format/index.en-US.md, packages/util/format/index.zh-CN.md, packages/util/pipes/currency/index.en-US.md, packages/util/pipes/currency/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1965
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util:currency): add `ingoreZeroPrecision` property

packages/abc/pdf/demo/basic.md, packages/abc/pdf/pdf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1975
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:pdf): add `loading` of pdf file loading

packages/acl/src/acl-if.directive.ts, packages/acl/src/acl.type.ts
- close #1227
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(acl): keeping pure lib

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/util/config/util/currency.type.ts, packages/util/format/currency.service.spec.ts, packages/util/format/currency.service.ts, packages/util/format/currency.types.ts, packages/util/format/index.en-US.md, packages/util/format/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1977
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util:CurrencyService): add support angular `currency` pipe render type

packages/abc/reuse-tab/reuse-tab.component.ts
- https://github.com/ng-alain/ng-alain/issues/1906
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:reuse-tab): support ssr

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/st.component.ts, packages/abc/st/st.config.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-data-source.spec.ts, packages/util/config/abc/st.type.ts
- close https://github.com/ng-alain/ng-alain/issues/1979
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `safeHtml` property in `STColumn`

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st.spec.ts, packages/util/config/abc/st.type.ts
-  close https://github.com/ng-alain/ng-alain/issues/1294
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `customRequest` property

package.json, packages/form/ng-package.json, packages/form/package.json, packages/form/src/validator.factory.ts, packages/schematics/ng-update/upgrade-rules/v117/index.ts, packages/schematics/utils/versions.ts, scripts/ci/utils.sh
- close https://github.com/ng-alain/ng-alain/issues/1984
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix losing format rules of ajv in 7.x version

packages/abc/st/st.component.html, packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1922
- close #1152
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix mutual pollution of `expand` and `click` event

package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): Upgrade `ajv` to `8.x`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> release(11.10.0): release 11.10.0

packages/schematics/ng-update/upgrade-rules/v117/index.ts, packages/schematics/utils/workspace.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix excess `allowedCommonJsDependencies`

packages/auth/src/token/helper.spec.ts, packages/auth/src/token/helper.ts
- close https://github.com/ng-alain/ng-alain/issues/1990
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1990
```
[ ] Yes
[x] No
```
=> fix(auth): catch the error when check jwt token

packages/abc/st/st-column-source.ts, packages/abc/st/st.config.ts, packages/util/config/abc/st.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): support `dateFormat` of global config

packages/abc/st/st-column-source.ts, packages/abc/st/st-export.ts, packages/abc/st/st.config.ts, packages/util/config/abc/st.type.ts
- feat(abc:st): support `yn` of global config
- close https://github.com/ng-alain/ng-alain/issues/1993
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix invalid `exported` in excel export

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.10.1): release 11.10.1

packages/form/src/widgets/time/time.widget.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form:widget:time): fix `minuteStep` param name

packages/theme/theme-btn/theme-btn.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1998
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:theme-btn): fix Failed to execute 'removeChild' on 'Node'

packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/2010
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix should be triggered `reset` every time when can be displayed

packages/chart/theme-compact.less, packages/chart/theme-dark.less, packages/chart/theme-default.less, packages/theme/theme-compact.less, packages/theme/theme-dark.less, packages/theme/theme-default.less
- close https://github.com/ng-alain/ng-alain/issues/1989
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(chart): remove empty theme variable

packages/chart/chart-echarts/echarts.component.ts, packages/chart/chart-echarts/echarts.spec.ts, packages/chart/chart-echarts/index.md
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(chart:echarts): fix can't percentage of width

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.10.3): release 11.10.3

packages/abc/down-file/down-file.directive.ts, packages/abc/down-file/down-file.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2021
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:down-file): fix should be enabled when http is invalid request

packages/abc/notice-icon/notice-icon.types.ts
- close https://github.com/ng-alain/ng-alain/issues/2017
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:notice-icon): fix support objects of `NoticeItem`

packages/acl/src/acl.service.spec.ts, packages/acl/src/acl.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2018
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(acl): fix should be cancel full when call  set

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(11.10.4): release 11.10.4

packages/chart/chart-echarts/echarts.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(chart:echarts): support resize

packages/abc/notice-icon/demo/popover.md, packages/abc/notice-icon/index.en-US.md, packages/abc/notice-icon/index.zh-CN.md, packages/abc/notice-icon/notice-icon-tab.component.html, packages/abc/notice-icon/notice-icon.module.ts, packages/abc/notice-icon/notice-icon.types.ts
- close https://github.com/ng-alain/ng-alain/issues/2004
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:notice-icon): add `emptyText`, `title`, `description` support TemplateRef

packages/abc/st/demo/type.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st-data-source.ts, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.config.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st-data-source.spec.ts, packages/util/config/abc/st.type.ts
- close https://github.com/ng-alain/ng-alain/issues/2006
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
=> refactor(abc:st): refactor `saftHtml` should be `safeType`

azure-pipelines.yml, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: upgrade to node 14

docs/i18n.en-US.md, docs/i18n.zh-CN.md, package.json, packages/abc/page-header/page-header.spec.ts, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st.spec.ts, packages/form/spec/form.spec.ts, packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/src/services/i18n/i18n.pipe.ts, packages/theme/src/services/i18n/i18n.spec.ts, packages/theme/src/services/i18n/i18n.ts, packages/theme/src/services/menu/menu.service.spec.ts, packages/theme/src/services/title/title.service.spec.ts, schematics/application/files/src/app/app.module.ts, schematics/application/files/src/app/core/startup/startup.service.ts, schematics/application/files/src/app/layout/basic/basic.component.ts, schematics/application/files/src/app/layout/layout.module.ts, schematics/application/files/src/app/routes/routes.module.ts, schematics/application/files/src/app/shared/shared.module.ts, schematics/application/index.spec.ts, schematics/application/index.ts, scripts/ci/build-schematics.sh, scripts/ci/build.sh, scripts/ci/utils.sh, src/app/core/i18n/service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: use build-in `i18n` instead of `@ngx-translate/core`

angular.json, package.json, src/app/layout/header/search-box.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: use cdn in docsearch

commitlint.config.js, packages/chart/bar/bar.component.ts, packages/chart/bar/index.md, packages/chart/mini-area/index.md, packages/chart/mini-area/mini-area.component.ts, packages/chart/mini-bar/index.md, packages/chart/mini-bar/mini-bar.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2013
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(chart:bar,mini-area,mini-bar): add `color` in data

packages/theme/docs/global.en-US.md, packages/theme/docs/global.zh-CN.md, packages/theme/system/theme-default.less, packages/theme/system/utils/index.less
- close https://github.com/ng-alain/ng-alain/issues/2019
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme): add enabled of util classes

packages/form/docs/schema.en-US.md, packages/form/docs/schema.zh-CN.md, packages/form/src/model/form.property.ts, packages/form/src/schema/ui.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(form): add `property` property of `visibleIf` function

packages/abc/se/demo/complex.md, packages/abc/se/style/index.less, packages/abc/sv/demo/basic.md, packages/abc/sv/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2020
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:se,sv): add `nz-divider` support

packages/abc/st/st-column-source.ts, packages/abc/st/st.interfaces.ts
- close https://github.com/ng-alain/ng-alain/issues/2023
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add autocomplete index

packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2033
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix optimize when specified new data in call  `export`

scripts/ci/build-schematics.sh
- close https://github.com/ng-alain/ng-alain/issues/2032
- close https://github.com/ng-alain/ng-alain/issues/2031
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix `UserLoginComponent` is declared by more than on NgModule

package.json, src/app/core/code/code.service.ts, src/app/core/code/files/app.module.ts, src/app/core/code/files/main-cli.ts, src/app/core/code/files/readme-cli.ts, src/app/core/code/files/startup.service.ts, src/app/core/code/files/tsconfig.json.ts, src/app/core/i18n/en-US.ts, src/app/core/i18n/zh-CN.ts, src/app/shared/components/code-box/code-box.component.html, src/app/shared/components/code-box/code-box.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1985
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: support angular cli of CodeSandbox

schematics/edit/schema.json, schematics/empty/schema.json, schematics/list/schema.json, schematics/tpl/schema.json, schematics/view/schema.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix duplicate alias of `t`

packages/theme/src/services/http/http.client.ts
- close https://github.com/ng-alain/ng-alain/issues/2036
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:http): fix missing `HttpContext`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, packages/theme/src/config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.0.1): release 12.0.1

package.json, schematics/collection.json, schematics/ng-update/index.ts, schematics/ng-update/upgrade-rules/v12/index.spec.ts, schematics/ng-update/upgrade-rules/v12/index.ts, schematics/ng-update/upgrade-rules/v12/schema.json, schematics/ng-update/upgrade-rules/v12/schema.ts
- https://github.com/ng-alain/ng-alain/issues/2027
- It seems to be caused by [#21075](https://github.com/angular/angular-cli/issues/21075), but it can't be reproduced in the test case, so the `fixAngularJson` option is added to ignore the Adjustment of `angular.json`
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): add `fixAngularJson` option

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.0.2): release 12.0.2

packages/abc/st/st-column-source.ts, packages/abc/st/st-export.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st-export.spec.ts
-  close https://github.com/ng-alain/ng-alain/issues/2042
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix excel column width

packages/abc/page-header/page-header.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2041
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:page-header): fix `should be run in update mode` error

schematics/application/index.ts, schematics/collection.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: remove ng-add-finished

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.0.3): release 12.0.3

packages/abc/page-header/page-header.component.html
- close https://github.com/ng-alain/ng-alain/issues/1510
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:page-header): fix can't slider for a lot of tabs

schematics/edit/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, schematics/empty/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, schematics/list/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, schematics/plugin/files/sts/swagger-edit/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, schematics/plugin/files/sts/swagger-list/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template, schematics/view/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts.template
- close https://github.com/ng-alain/ng-alain/issues/2051
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): remove deprecated async of test case

packages/abc/exception/exception.component.html, packages/abc/exception/exception.component.ts, packages/abc/exception/exception.spec.ts, packages/abc/exception/index.en-US.md, packages/abc/exception/index.zh-CN.md
- fixed https://github.com/ng-alain/ng-alain/discussions/2045
- close https://github.com/ng-alain/ng-alain/issues/2048
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:exception): add `backRouterLink` property

packages/form/src/widgets/number/demo/simple.md, packages/form/src/widgets/number/index.en-US.md, packages/form/src/widgets/number/index.zh-CN.md, packages/form/src/widgets/number/number.widget.html, packages/form/src/widgets/number/schema.ts, packages/theme/system/antd/_input-number.less, packages/theme/system/antd/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): add `hideStep` of `number` widget

packages/abc/reuse-tab/reuse-tab.service.spec.ts, packages/abc/reuse-tab/reuse-tab.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2053
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:reuse-tab): fix re-trigger the `_onReuseInit` event

packages/abc/st/demo/row-click.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `clickRowClassName` property

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.1.0): release 12.1.0

packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/2057
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:widget:select): fix invalid `orgData` of `change`event

packages/form/src/sf.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix invlid type in `button`

packages/auth/src/store/cookie-storage.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs(auth): typo

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.1.1): release 12.1.1

packages/form/src/widgets/select/select.widget.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #2057
```
[ ] Yes
[x] No
```
=> fix(form:widget:select): fix invalid `orgData` of `change` event (#1312)

packages/util/other/deep.spec.ts, packages/util/other/deep.ts
- close https://github.com/ng-alain/ng-alain/issues/2063
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(util:other:deep): fix can't merge function in `deepMergeKey`

packages/abc/st/st-data-source.ts
- close https://github.com/ng-alain/ng-alain/issues/2064
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix render `undefined` when `safeType` is `text`

packages/form/src/utils.ts, packages/util/decorator/convert.spec.ts, packages/util/decorator/convert.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(util:convert): fix invalid `defaultValue` parament in `InputBoolean`

scripts/site/generate.ts, scripts/site/utils/utils.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(site:gen): path error for `util-pipes` in the `windows env`

packages/theme/docs/global.en-US.md, packages/theme/docs/global.zh-CN.md, packages/theme/system/antd/_table.less, packages/theme/system/theme-default.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme): add `@nz-table-even-background`

packages/abc/se/index.en-US.md, packages/abc/se/index.zh-CN.md, packages/abc/se/se-container.component.ts, packages/abc/se/se.component.html, packages/abc/se/se.component.ts, packages/abc/se/se.spec.ts, packages/abc/se/style/index.less, packages/abc/sv/index.en-US.md, packages/abc/sv/index.zh-CN.md, packages/abc/sv/style/index.less, packages/abc/sv/sv-container.component.ts, packages/abc/sv/sv.component.html, packages/abc/sv/sv.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2066
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:se,sv): add `noColon` property

_mock/user.ts, packages/form/src/widgets/string/demo/simple.md, packages/form/src/widgets/string/demo/time.md, packages/form/src/widgets/string/index.en-US.md, packages/form/src/widgets/string/index.zh-CN.md, packages/form/src/widgets/string/schema.ts, packages/form/src/widgets/string/string.widget.spec.ts, packages/form/src/widgets/string/string.widget.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form:string): add `changeDebounceTime`, `changeMap` property

packages/abc/page-header/page-header.spec.ts, packages/abc/st/test/st-column-source.spec.ts, packages/theme/src/services/i18n/i18n.spec.ts, packages/theme/src/services/i18n/i18n.ts, packages/util/config/config.types.ts, packages/util/config/theme/i18n.type.ts, packages/util/config/theme/index.ts, src/app/core/i18n/service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:i18n): add `interpolation` in global config

packages/theme/public_api.ts, packages/theme/src/router/optional-preloader.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme): add `PreloadOptionalModules`

packages/form/src/sf-item-wrap.component.html, packages/form/src/sf.component.ts, packages/form/src/widgets/array/array.widget.html, src/dev/demo.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2067
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf): fix unknown keyword: "_description" in strict mode

packages/theme/docs/global.en-US.md, packages/theme/docs/global.zh-CN.md, packages/theme/system/antd/_table.less, packages/theme/system/theme-default.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: fix `.antTableEvenBG` in less complite

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.2.1): release 12.2.1

schematics/tpl/schema.json
- close https://github.com/ng-alain/ng-alain/issues/2079
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli:tpl): fix lose `tplName` property of `schema.json`

packages/form/src/schema/ui.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): add `widget` index sign

schematics/tpl/schema.json
```
[x] Bugfix
[ ] Feature
```
Issue Number: #1335 
```
[ ] Yes
[x] No
```
=> fix(cli:tpl): fix incorrect arguments index of schema.json

packages/abc/st/st-export.ts, packages/abc/st/test/st-export.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2084
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix `#NULL!` value when empty value and `type` is `date`

packages/auth/src/token/token.service.spec.ts, packages/auth/src/token/token.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2087
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(auth): fix ensure `change` event and `get()` have consistent results

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.html, packages/abc/st/style/index.less, packages/abc/theme-default.less
- close https://github.com/ng-alain/ng-alain/issues/2083
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix between sorts space of resizable handle

src/app/core/startup.service.ts, src/index.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: script load order

schematics/application/index.ts, schematics/ng-add/index.ts, scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: perf information render of ng add ng-alain

packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2092
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:reuse-tab): fix adding new tab should be after the current

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.2.2): release 12.2.2

packages/form/src/widgets/number/index.en-US.md, packages/form/src/widgets/number/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/2096
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: add qa

packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts, packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/2097
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:widget:autocomplete): fix invalid typing when async data

schematics/application/files/src/app/shared/index.ts, schematics/application/index.spec.ts, scripts/ci/build-schematics.sh
- close https://github.com/ng-alain/ng-alain/issues/2099
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix export json-schema when not choose form

packages/karma.conf.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: set  `clearContext`  is  `false`

packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2101
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix `ui` value cross pollute

packages/chart/chart-echarts/demo/on.md, packages/chart/chart-echarts/echarts.component.ts, packages/chart/chart-echarts/echarts.spec.ts, packages/chart/chart-echarts/echarts.types.ts, packages/chart/chart-echarts/index.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(chart:echarts): add `on` property

packages/karma.conf.js, packages/util/format/index.en-US.md, packages/util/format/index.zh-CN.md, packages/util/format/string.spec.ts, packages/util/format/string.ts, packages/util/pipes/format/mask.pipe.ts
- close https://github.com/ng-alain/ng-alain/issues/2076
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util:format): add token mode in format mask

packages/abc/xlsx/demo/export.md, packages/abc/xlsx/index.en-US.md, packages/abc/xlsx/index.zh-CN.md, packages/abc/xlsx/package.json, packages/abc/xlsx/xlsx.service.ts, packages/abc/xlsx/xlsx.spec.ts, packages/abc/xlsx/xlsx.types.ts
- close https://github.com/ng-alain/ng-alain/issues/2100
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:xlsx): add support csv file

scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix syncTaobao

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.3.0): release 12.3.0

packages/form/src/widgets/custom/index.zh-CN.md
tempalte 改为 template
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: 修改单词拼写错误

package.json, packages/abc/reuse-tab/reuse-tab-context-menu.component.html, packages/abc/reuse-tab/reuse-tab-context.service.ts, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2123
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:reuse-tab): fix disabled refresh when non-active tab

packages/form/src/widgets/number/index.en-US.md, packages/form/src/widgets/number/index.zh-CN.md, packages/form/src/widgets/number/number.widget.spec.ts, packages/form/src/widgets/number/number.widget.ts, packages/form/src/widgets/number/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/2119
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form:widget:number): add `change` event

docs/server.en-US.md, docs/server.zh-CN.md, schematics/application/index.ts, schematics/ng-update/upgrade-rules/v12/index.spec.ts, scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix: use `proxy.conf.js` instead of `proxy.conf.json`

packages/theme/layout-default/layout-nav.component.html, packages/theme/layout-default/layout-nav.component.spec.ts, packages/theme/layout-default/layout.module.ts, packages/theme/layout-default/style/fix/_sidebar-nav.less, packages/theme/src/services/menu/index.en-US.md, packages/theme/src/services/menu/index.zh-CN.md, packages/theme/src/services/menu/interface.ts, packages/theme/src/services/menu/menu.service.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:layout-default): fix can't render badge

docs/faq.en-US.md, docs/faq.zh-CN.md, docs/getting-started.zh-CN.md, schematics/plugin/plugin.network-env.spec.ts, schematics/plugin/plugin.network-env.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> docs: upgrade taobao.org to npmmirror.com

packages/chart/mini-area/index.md, packages/chart/mini-area/mini-area.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(chart:mini-area): remove color in data

docs/getting-started.en-US.md, docs/getting-started.zh-CN.md, src/app/core/code/code.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix site

.github/workflows/deploy-site.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix surge

packages/theme/src/services/i18n/i18n.spec.ts, packages/theme/src/services/i18n/i18n.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:i18n): add `flatData` in `AlainI18nBaseService`

packages/theme/system/antd/_table.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:st): fix causes misalignment when set `width` in small screens

packages/form/src/widgets/upload/upload.widget.ts
pureValue方法返回值定义错误引发编译器警告
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:widget:upload): fix invalid return type

packages/abc/sv/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:sv): fix vertical align of detail

packages/abc/exception/exception.component.ts, packages/abc/exception/exception.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:exception): fix observe content

schematics/docs/generate.en-US.md, schematics/docs/generate.zh-CN.md, schematics/empty/index.spec.ts, schematics/module/index.ts, schematics/schema.json, schematics/utils/alain.ts, schematics/utils/json.ts, schematics/utils/testing.ts, schematics/utils/workspace.ts
- close https://github.com/ng-alain/ng-alain/issues/2134
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cli): support specify routesRoot via `ng-alain.json`

schematics/application/files/src/app/core/startup/startup.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> perf: optimize error handling and navigate to the exception page

.eslintrc.js, .vscode/launch.json, package.json, packages/abc/down-file/down-file.spec.ts, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.service.spec.ts, packages/abc/st/test/base.spec.ts, packages/abc/zip/zip.spec.ts, packages/acl/src/acl.service.spec.ts, packages/auth/src/social/social.service.spec.ts, packages/form/spec/base.spec.ts, packages/form/spec/form.spec.ts, packages/theme/src/services/http/http.spec.ts, packages/util/date-time/picker.spec.ts, packages/util/format/validate.spec.ts, packages/util/math/in-range.spec.ts, packages/util/math/round.spec.ts, schematics/application/index.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2143
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: remove deprecated in test

packages/abc/st/demo/row-op.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.config.ts, packages/abc/st/test/base.spec.ts, packages/abc/st/test/st.spec.ts, packages/util/config/abc/st.type.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): remove `rowClickTime` property

schematics/curd/schema.json, schematics/curd/schema.ts, schematics/docs/generate.en-US.md, schematics/docs/generate.zh-CN.md, schematics/edit/schema.json, schematics/edit/schema.ts, schematics/empty/schema.json, schematics/empty/schema.ts, schematics/list/schema.json, schematics/list/schema.ts, schematics/test.ts, schematics/tpl/schema.json, schematics/tpl/schema.ts, schematics/utils/alain.spec.ts, schematics/utils/alain.ts
- close https://github.com/ng-alain/ng-alain/issues/2140
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(cli): add `withoutModulePrefixInComponentName`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, scripts/ci/utils.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.4.1): release 12.4.1

packages/abc/onboarding/schema.json, schematics/application/schema.json, schematics/curd/schema.json, schematics/docs/generate.en-US.md, schematics/docs/generate.zh-CN.md, schematics/edit/schema.json, schematics/empty/schema.json, schematics/list/schema.json, schematics/module/schema.json, schematics/ng-add/schema.json, schematics/ng-update/upgrade-rules/v12/schema.json, schematics/plugin/schema.json, schematics/sta/schema.json, schematics/tpl/schema.json, schematics/view/schema.json
- close https://github.com/ng-alain/ng-alain/issues/2149
- close https://github.com/ng-alain/ng-alain/issues/2150
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf(cli): update the $schema flag to the draft-07 standard

packages/abc/st/demo/checkbox.md, packages/abc/st/demo/radio.md, packages/abc/st/st-td.component.ts, packages/abc/st/st.component.html, packages/abc/st/st.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix can't render when data changed

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(12.4.2): release 12.4.2

packages/abc/lodop/lodop.types.ts
Add function declare ADD_PRINT_PDF
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:lodop): Update lodop.types.ts

packages/abc/media/index.en-US.md, packages/abc/media/index.zh-CN.md, packages/abc/media/media.service.ts, packages/abc/pdf/pdf.config.ts, packages/abc/qr/index.en-US.md, packages/abc/qr/index.zh-CN.md, packages/abc/qr/qr.config.ts, packages/abc/xlsx/index.en-US.md, packages/abc/xlsx/index.zh-CN.md, packages/abc/xlsx/xlsx.service.ts, packages/abc/zip/index.en-US.md, packages/abc/zip/index.zh-CN.md, packages/abc/zip/zip.service.ts, packages/util/config/abc/pdf.type.ts, packages/util/config/abc/qr.type.ts
- close https://github.com/ng-alain/ng-alain/issues/2163
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor: refactor all third-party libraries to reference jsdelivr CDN

azure-pipelines.yml, packages/abc/lodop/lodop.types.ts, schematics/ng-add/index.spec.ts, schematics/ng-add/index.ts, schematics/utils/node.ts
- close https://github.com/ng-alain/ng-alain/issues/2155
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli:ng-add): fix ingore invalid node version

packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/2161
- 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:autocomplete): fix can't be set default value

scripts/azure/github-comment.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix github comment

packages/form/src/widgets/array/array.widget.html, packages/form/src/widgets/array/array.widget.spec.ts, packages/form/src/widgets/array/index.en-US.md, packages/form/src/widgets/array/index.zh-CN.md, packages/form/src/widgets/array/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/2166
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form:array): add `required` property

packages/theme/layout-default/layout-nav.component.html, packages/theme/layout-default/layout-nav.component.spec.ts, packages/theme/layout-default/layout-nav.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2170
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:layout-default): fix can't hide submenu when move to other

packages/abc/image/image.directive.ts, packages/abc/image/index.en-US.md, packages/abc/image/index.zh-CN.md, packages/form/src/widgets/object/schema.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: remove deprecated APIs for V13

packages/util/browser/copy.spec.ts, packages/util/browser/copy.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> perf(util:copy): use standard interface `navigator.clipboard`

package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: bump ng-zorro-antd to `13.0.0`

.github/workflows/deploy-site.yml, CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.0.0): release 13.0.0

schematics/application/index.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix `lint:style` script

README.md, _mock/user.ts, packages/abc/st/test/st.spec.ts, packages/polyfills.ts, packages/theme/layout-default/style/_aside.less, packages/theme/src/services/http/http.spec.ts, packages/util/other/lazy.service.spec.ts, packages/util/other/lazy.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: remove deprecated

packages/chart/bar/bar.component.ts, packages/chart/bar/index.md, packages/chart/core/g2.base.component.ts, packages/chart/gauge/gauge.component.ts, packages/chart/gauge/index.md, packages/chart/mini-area/index.md, packages/chart/mini-area/mini-area.component.ts, packages/chart/mini-bar/index.md, packages/chart/mini-bar/mini-bar.component.ts, packages/chart/pie/index.md, packages/chart/pie/pie.component.ts, packages/chart/radar/index.md, packages/chart/radar/radar.component.ts, packages/chart/single-bar/index.md, packages/chart/single-bar/single-bar.component.ts, packages/chart/tag-cloud/index.md, packages/chart/tag-cloud/tag-cloud.component.ts, packages/chart/timeline/index.md, packages/chart/timeline/timeline.component.ts, src/styles/theme.less
- close https://github.com/ng-alain/ng-alain/issues/2181
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> feat(chart:*): add `ready` event

schematics/module/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli:module): fix missing comma

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.1.0): release 13.1.0

packages/abc/se/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2180
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:se): fix animation style

packages/cache/docs/service.md, packages/cache/src/cache.service.ts, packages/cache/src/cache.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2188
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cache): add `emitNotify` property

packages/form/src/model/array.property.ts
```
[ ] Bugfix
[ ] Feature
```
- close https://github.com/ng-alain/ng-alain/issues/2187
```
[ ] Yes
[ ] No
```
=> fix(form): fix schema polluted in array

packages/abc/qr/index.en-US.md, packages/abc/qr/index.zh-CN.md, packages/abc/qr/qr.component.ts, packages/abc/qr/qr.spec.ts
- close #1436
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:qr): support function of `value`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.2.0): release 13.2.0

packages/chart/pie/pie.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(chart:pie): fix ECAIHBC error in block

schematics/curd/schema.json, schematics/edit/schema.json, schematics/empty/schema.json, schematics/list/schema.json, schematics/tpl/schema.json, schematics/view/schema.json
- close https://github.com/ng-alain/ng-alain/issues/2197
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix duplcated `-t`

packages/form/src/widgets/tree-select/tree-select.widget.html
```
[ ✔] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ✔] No
```
=> fix(form:tree-select): fix typo `checkfStrictly`

packages/abc/pdf/pdf.component.ts, packages/abc/pdf/pdf.spec.ts, packages/abc/pdf/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:pdf): fix `container` must be absolutely positioned error

scripts/publish/sync-scaffold-version.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix sync scaffold version

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.2.1): release 13.2.1

packages/abc/theme-dark.less, packages/theme/theme-btn/index.en-US.md, packages/theme/theme-btn/index.zh-CN.md, packages/theme/theme-btn/theme-btn.component.ts, src/app/layout/layout.component.ts, src/app/shared/components/code-box/code-box.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2195
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme:theme-btn): add `themeChange` event

packages/form/docs/getting-started.en-US.md, packages/form/docs/getting-started.zh-CN.md, packages/form/docs/qa.zh-CN.md, packages/form/examples/conditional/demo/if.md, packages/form/examples/conditional/demo/visibleIf.md, packages/form/examples/conditional/index.en-US.md, packages/form/examples/conditional/index.zh-CN.md, packages/form/spec/form.spec.ts, packages/form/spec/schema.spec.ts, packages/form/src/errors.ts, packages/form/src/interface.ts, packages/form/src/model/form.property.factory.ts, packages/form/src/model/form.property.ts, packages/form/src/schema/ui.ts, packages/form/src/sf-item-wrap.component.html, packages/form/src/sf-item-wrap.component.ts, packages/form/src/sf-item.component.ts, packages/form/src/sf.component.ts, packages/form/src/utils.ts, packages/form/src/widget.ts, scripts/site/route-paths.txt
- perf `visibleIf`
- close https://github.com/ng-alain/ng-alain/issues/2198
- close https://github.com/ng-alain/ng-alain/issues/2182
- close https://github.com/ng-alain/ng-alain/issues/2153
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): add `feedback`

packages/form/docs/qa.en-US.md, packages/form/docs/qa.zh-CN.md, packages/form/src/widgets/radio/radio.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/2201
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf:widget:radio): fix SafeHtml

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.3.0): release 13.3.0

packages/abc/st/st.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(abc:st): chore deprecated

packages/abc/avatar-list/avatar-list.spec.ts, packages/abc/error-collect/error-collect.spec.ts, packages/abc/st/demo/row-op.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/st.component.ts, packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2205
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `addRow` method

packages/chart/card/card.component.html
- close https://github.com/ng-alain/ng-alain/issues/2206
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(chart:card): fix support html of `total` property

packages/abc/st/st.component.ts, packages/abc/st/test/base.spec.ts, packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2207
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix misalignment when removing multiple rows

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.4.0): release 13.4.0

schematics/utils/alain.ts
- close https://github.com/ng-alain/ng-alain/issues/2208
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix can't use `ng g ng-alain` command in subdirectories

schematics/utils/code-style.ts
- close https://github.com/ng-alain/ng-alain/issues/2211
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix deprecated `--syntax` of lint-staged

packages/form/src/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2212
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(sf): fix misalignment

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.4.1): release 13.4.1

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/2218
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: add how to control menu expand

packages/abc/tag-select/demo/simple.md, packages/abc/tag-select/style/index.less, packages/abc/tag-select/tag-select.component.html, packages/abc/tag-select/tag-select.spec.ts, packages/abc/theme-compact.less, packages/abc/theme-default.less
- close https://github.com/ng-alain/ng-alain/issues/2219
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:tag-select): fix style misalignment

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.4.2): release 13.4.2

package.json, packages/abc/ellipsis/ellipsis.spec.ts, packages/abc/reuse-tab/reuse-tab.component.ts, packages/abc/reuse-tab/style/index.less, packages/abc/reuse-tab/style/rtl.less, packages/theme/layout-default/style/_aside.less, packages/theme/layout-default/style/fix/_reuse-tab.less
- close https://github.com/ng-alain/ng-alain/issues/2222
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:layout-default): fix RTL will misalignment in medium screen

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/layout-default/layout-header.component.ts, packages/theme/layout-default/types.ts
- close https://github.com/ng-alain/ng-alain/issues/2223
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:layout-defualt): support custom logo area

packages/form/docs/getting-started.en-US.md, packages/form/docs/getting-started.zh-CN.md, packages/form/spec/base.spec.ts, packages/form/spec/form.spec.ts, packages/form/src/config.ts, packages/form/src/sf.component.ts, packages/util/config/sf/sf.type.ts
- close https://github.com/ng-alain/ng-alain/issues/2230
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): add `delay` property

schematics/docs/sta.en-US.md, schematics/docs/sta.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/2236
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: modify Unexpected name

packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2238
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix modify disabled & loading to cause refresh schema

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st.config.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-column-source.spec.ts, packages/util/config/abc/st.type.ts
- close https://github.com/ng-alain/ng-alain/issues/2239
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add `maxMultipleButton` of column

packages/abc/st/st-column-source.ts, scripts/publish/sync-scaffold-version.js
- close https://github.com/ng-alain/ng-alain/issues/2242
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix safe null check of menus

packages/abc/st/st-column-source.ts, packages/abc/st/st-data-source.ts, packages/abc/st/st-td.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st-data-source.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix #1474

packages/form/docs/error.en-US.md, packages/form/docs/error.zh-CN.md, packages/form/spec/form.spec.ts, packages/form/src/errors.ts, packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/2240
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): export `setErrors` method

packages/util/browser/cookie.service.spec.ts, packages/util/browser/cookie.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2241
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(util:cookie): fix wrong set value of `remove`

packages/abc/qr/index.en-US.md, packages/abc/qr/index.zh-CN.md, packages/abc/qr/qr.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2248
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:qr): fix can't center

angular.json, package.json, packages/abc/media/index.en-US.md, packages/abc/media/index.zh-CN.md, packages/abc/ng-package.json, packages/abc/package.json, packages/abc/pdf/index.en-US.md, packages/abc/pdf/index.zh-CN.md, packages/abc/qr/index.en-US.md, packages/abc/qr/index.zh-CN.md, packages/abc/xlsx/index.en-US.md, packages/abc/xlsx/index.zh-CN.md, packages/abc/zip/index.en-US.md, packages/abc/zip/index.zh-CN.md, packages/util/config/abc/media.type.ts, scripts/ci/utils.sh, src/app/global-config.module.ts
- close https://github.com/ng-alain/ng-alain/issues/2191
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: how to use local path

packages/util/browser/copy.spec.ts, packages/util/browser/copy.ts
- close https://github.com/ng-alain/ng-alain/issues/2246
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(util:copy): fix invalid `copy` in latest chrome

packages/util/config/abc/media.type.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix Plyr type

.stylelintrc, packages/theme/system/theme-dark.less, packages/theme/system/theme-default.less
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
=> style: add `indentation` property

schematics/utils/alain.ts
```
[ x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x ] No
```
=> fix(cli): fix folder name case sensitive

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.5.1): release 13.5.1

.github/workflows/deploy-site.yml, CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(13.5.2): release 13.5.2

packages/form/src/style/_issues.less, packages/form/src/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2275
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): fix width style

packages/abc/date-picker/range.directive.ts, packages/abc/down-file/down-file.spec.ts, packages/abc/onboarding/onboarding.module.ts, packages/abc/onboarding/onboarding.service.ts, packages/abc/zip/zip.spec.ts
Ref: https://github.com/ng-alain/ng-alain/issues/2232
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: remove deprecation

schematics/utils/versions.ts, scripts/ci/utils.sh
- close https://github.com/ng-alain/ng-alain/issues/2284
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf(cli): sync rxjs version when ng update

packages/abc/zip/demo/read.md, packages/abc/zip/demo/save.md, packages/abc/zip/zip.service.ts, packages/abc/zip/zip.spec.ts, packages/abc/zip/zip.types.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> refactor(*): add strictly typed

packages/abc/pdf/demo/basic.md, packages/abc/pdf/demo/design.md, packages/abc/pdf/index.en-US.md, packages/abc/pdf/index.zh-CN.md, packages/abc/pdf/pdf.component.ts, packages/abc/pdf/pdf.types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:pdf): add `eventBus` property

packages/theme/src/services/title/index.en-US.md, packages/theme/src/services/title/index.zh-CN.md, packages/theme/src/services/title/title.service.spec.ts, packages/theme/src/services/title/title.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2231
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:title): add `selector` property

packages/theme/docs/global.en-US.md, packages/theme/docs/global.zh-CN.md, packages/theme/system/antd/_drawer.less, packages/theme/system/theme-default.less
- close ng-alain/ng-alain#2268
- 
- ## PR Checklist
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme): fix missing xl style in vertical

packages/abc/page-header/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> style(abc:page-header): fix extra align

packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/public_api.ts, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.component.ts, packages/abc/reuse-tab/reuse-tab.interfaces.ts, packages/abc/reuse-tab/reuse-tab.module.ts, packages/abc/reuse-tab/reuse-tab.service.spec.ts, packages/abc/reuse-tab/reuse-tab.service.ts, packages/abc/reuse-tab/reuse-tab.state.spec.ts, packages/abc/reuse-tab/reuse-tab.state.ts
- close https://github.com/ng-alain/ng-alain/issues/2229
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:reuse-tab): support status of the last browser closed

.eslintrc.js, packages/abc/observers/demo/basic.md, packages/abc/observers/index.en-US.md, packages/abc/observers/index.ts, packages/abc/observers/index.zh-CN.md, packages/abc/observers/ng-package.json, packages/abc/observers/observer-size.ts, packages/abc/observers/public-api.ts, scripts/site/route-paths.txt, src/app/shared/shared-delon.module.ts
- close https://github.com/ng-alain/ng-alain/issues/2262
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:observers): add `[observeSize]` directive

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-data-source.spec.ts, packages/util/config/abc/st.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:st): add function of `reName`

packages/form/docs/schema.en-US.md, packages/form/docs/schema.zh-CN.md, packages/form/spec/schema.spec.ts, packages/form/src/model/form.property.ts, packages/form/src/schema/ui.ts
- close https://github.com/ng-alain/ng-alain/issues/2259
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): add `visibleIfLogical` logical type

packages/theme/src/locale/languages/zh-TW.ts
- close https://github.com/ng-alain/ng-alain/issues/2276
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: typo word

packages/form/src/widgets/array/array.widget.spec.ts, packages/form/src/widgets/array/array.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/2277
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(forum:array): fix invalid `minItems`

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-data-source.ts, packages/abc/st/st.config.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-data-source.spec.ts, packages/util/config/abc/st.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add whether to ignore `null` or `undefined` value

schematics/application/index.ts, schematics/migration.json, schematics/ng-update/index.ts, schematics/ng-update/upgrade-rules/v14/index.spec.ts, schematics/ng-update/upgrade-rules/v14/index.ts, schematics/test.ts, schematics/utils/versions.ts, schematics/utils/workspace.ts, scripts/ci/utils.sh
- close https://github.com/ng-alain/ng-alain/issues/2224
- close https://github.com/ng-alain/ng-alain/issues/2252
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> chore(cli): add schematicCollections

packages/form/src/schema/index.ts, packages/form/src/widgets/select/demo/simple.md, packages/form/src/widgets/select/select.widget.html
- close https://github.com/ng-alain/ng-alain/issues/2286
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): add `hide` property

package.json, schematics/sta/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: bump ng-zorro-antd 14

packages/abc/se/se.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2279
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:se): fix missing error style

packages/util/other/index.en-US.md, packages/util/other/index.zh-CN.md, packages/util/other/object.spec.ts, packages/util/other/object.ts
- close https://github.com/ng-alain/ng-alain/issues/2216
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(util): add `omit`

packages/theme/src/services/http/http.token.ts, packages/theme/src/services/http/index.en-US.md, packages/theme/src/services/http/index.zh-CN.md, src/app/layout/header/header.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme): add `RAW_BODY` token

package.json, schematics/utils/versions.ts, scripts/ci/utils.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix cli

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.0.0): release 14.0.0

schematics/application/files/src/app/core/index.ts, schematics/application/files/src/app/routes/routes-routing.module.ts, scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(cli): add dynamic start page

packages/abc/st/st-column-source.ts, packages/abc/st/st.component.html, packages/abc/st/test/st-column-source.spec.ts, packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2295
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix built-in style into to `className`

angular.json, packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/reuse-tab.component.ts, schematics/ng-update/upgrade-rules/v14/index.spec.ts, schematics/ng-update/upgrade-rules/v14/index.ts, schematics/utils/file.ts, src/dev/layout.component.ts, src/dev/pages/page.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2302
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:reuse-tab): fix can't refresh current tab

packages/abc/st/demo/custom-data.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st-filter.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/base.spec.ts, packages/abc/st/test/st-filter.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2299
- close https://github.com/ng-alain/ng-alain/issues/2301
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix can't close panel when `showOPArea` is `true`

schematics/application/files/src/app/core/startup/startup.service.ts
- close #1514
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix correctly returns undefined

packages/abc/st/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2307
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix click trigger on blank area of sub-menus

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.1.0): release 14.1.0

CHANGELOG.md, packages/form/spec/form.spec.ts, packages/form/src/errors.ts, packages/form/src/model/form.property.ts, packages/form/src/sf-item-wrap.component.html, packages/form/src/sf-item-wrap.component.ts, packages/form/src/sf-item.component.ts, packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2313
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): fix missing error style

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.1.1): release 14.1.1

package.json, schematics/sta/index.spec.ts
Fix via https://github.com/acacode/swagger-typescript-api/issues/370
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> chore: fix swagger-typescript-api

packages/theme/setting-drawer/setting-drawer.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:setting-drawer): add `lessJs` property

packages/form/docs/qa.en-US.md, packages/form/docs/qa.zh-CN.md, packages/form/spec/schema.spec.ts, packages/form/src/model/form.property.factory.ts, packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/2316
- Ref https://github.com/ng-alain/delon/pull/1531
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fallback #1531

package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): upgrade `ng-alain-plugin-theme`

packages/abc/st/st.component.html, packages/abc/st/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2324
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix miss center title when set sort

packages/abc/st/st.component.ts, packages/abc/st/test/st.spec.ts, packages/util/config/abc/st.type.ts
- close https://github.com/ng-alain/ng-alain/issues/2321
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix use pure recoard data for modal params

packages/abc/notice-icon/index.en-US.md, packages/abc/notice-icon/index.zh-CN.md, packages/abc/notice-icon/notice-icon.component.html, packages/abc/notice-icon/notice-icon.component.ts, packages/abc/notice-icon/notice-icon.spec.ts, packages/abc/notice-icon/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/2318
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:notice-icon): add `centered` property

package.json, schematics/docs/sta.en-US.md, schematics/docs/sta.zh-CN.md, schematics/sta/index.spec.ts, schematics/sta/index.ts, schematics/sta/schema.json, schematics/sta/types.ts
- close https://github.com/ng-alain/ng-alain/issues/2325
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(cli:sta): add `tagsMapping` property

packages/abc/exception/demo/403.md, packages/abc/exception/exception.component.ts, packages/abc/exception/index.en-US.md, packages/abc/exception/index.zh-CN.md, packages/util/config/abc/exception.type.ts, packages/util/config/abc/index.ts, packages/util/config/config.types.ts
- close https://github.com/ng-alain/ng-alain/issues/2317
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:exception): add `typeDict` of global config

packages/util/other/lazy.service.spec.ts, packages/util/other/lazy.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2327
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
=> feat(util:other:lazy): add `attriburte` property

.github/workflows/deploy-site.yml, CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.2.0): release 14.2.0

packages/abc/sv/demo/fixed.md, packages/abc/sv/index.en-US.md, packages/abc/sv/index.zh-CN.md, packages/abc/sv/sv.component.html, packages/abc/sv/sv.component.ts, packages/abc/sv/sv.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2330
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:sv): add `hideLabel` property

package.json, packages/theme/src/pipes/date/date.pipe.spec.ts, packages/theme/src/pipes/yn/yn.pipe.spec.ts, packages/theme/src/services/i18n/i18n.spec.ts, packages/util/pipes/currency/cny.pipe.spec.ts, packages/util/pipes/currency/mega.pipe.spec.ts, packages/util/pipes/currency/price.pipe.spec.ts, packages/util/pipes/filter/filter.pipe.spec.ts, packages/util/pipes/format/mask.pipe.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix code style

packages/abc/st/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix misalignment

packages/abc/st/st.component.html, packages/abc/st/style/index.less, packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2336
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix shadow spacing in truncate

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/layout-default/layout-header.component.ts, packages/theme/layout-default/layout-nav.component.ts, packages/theme/layout-default/layout.component.spec.ts, packages/theme/layout-default/layout.component.ts, packages/theme/layout-default/layout.service.spec.ts, packages/theme/layout-default/layout.service.ts, packages/theme/layout-default/public_api.ts, packages/theme/layout-default/style/_aside.less, packages/theme/layout-default/style/_fixed.less, packages/theme/layout-default/style/_layout.less, packages/theme/layout-default/style/fix/_reuse-tab.less, packages/theme/layout-default/style/fix/_sidebar-nav.less, packages/theme/layout-default/style/theme-default.less, packages/theme/layout-default/types.ts, src/dev/dev.module.ts, src/dev/home/home.component.ts, src/dev/layout.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2034
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:default): add `LayoutDefaultService` service

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, docs/upgrade-v14.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(14.3.0): release 14.3.0

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/layout-default/style/theme-default.less
- `@alain-default-aside-nav-item-height`
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:theme-default): remove unused parameter

schematics/tpl/schema.json
- close https://github.com/ng-alain/ng-alain/issues/2348
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix `name` points to an invalid index

packages/abc/st/st-column-source.ts, packages/abc/st/st.component.html, packages/abc/st/st.types.ts
- close https://github.com/ng-alain/ng-alain/issues/2346
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix `className` not applied to title

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/layout-default/layout-top-menu-item.ts, packages/theme/layout-default/layout.module.ts, packages/theme/layout-default/public_api.ts, packages/theme/layout-default/style/_header.less, packages/theme/layout-default/style/theme-compact.less, packages/theme/layout-default/style/theme-default.less, src/dev/layout.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2343
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:layout-default): add `layout-default-top-menu-item`

.stylelintrc, docs/faq.en-US.md, docs/faq.zh-CN.md, package.json, schematics/application/index.ts, schematics/ng-update/upgrade-rules/v15/index.ts, schematics/package.json, schematics/utils/less.ts, scripts/ci/utils.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: update update

packages/abc/package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:pdf): fix support `2.x`

package.json, packages/auth/docs/getting-started.en-US.md, packages/auth/docs/getting-started.zh-CN.md, packages/auth/docs/qa.en-US.md, packages/auth/docs/qa.zh-CN.md, packages/auth/src/token/base.interceptor.spec.ts, packages/form/src/widgets/select/select.widget.spec.ts, scripts/site/route-paths.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs(auth): update

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(15.0.1): release 15.0.1

packages/form/docs/schema.en-US.md, packages/form/docs/schema.zh-CN.md, packages/form/src/errors.ts, src/app/core/code/files/delon-abc.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(site): remove imagemodule

packages/form/src/widgets/number/demo/simple.md, packages/form/src/widgets/number/index.en-US.md, packages/form/src/widgets/number/index.zh-CN.md, packages/form/src/widgets/number/number.widget.html, packages/form/src/widgets/number/number.widget.spec.ts, packages/form/src/widgets/number/number.widget.ts, packages/form/src/widgets/number/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/2364
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form:number): support string type of `widgetWidth`

packages/form/spec/base.spec.ts, packages/form/src/errors.ts, packages/form/src/sf-item-wrap.component.ts, packages/form/src/sf.component.ts, packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts, packages/karma.conf.js
- close https://github.com/ng-alain/ng-alain/issues/2362
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:string): fix pre tab cause out of focus

packages/form/src/schema/ui.ts, packages/form/src/sf.component.ts, packages/form/src/widgets/array/demo/irregular.md
- close https://github.com/ng-alain/ng-alain/issues/2355
- close https://github.com/ng-alain/delon/pull/1582
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): fix ui value should inherit parent ui

packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2372
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix invalid total of global config

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, scripts/ci/lint.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(15.1.0): release 15.1.0

packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/acl/docs/guard.en-US.md, packages/acl/docs/guard.zh-CN.md, packages/acl/src/acl-guard.spec.ts, packages/acl/src/acl-guard.ts, packages/auth/src/token/jwt/jwt.guard.spec.ts, packages/auth/src/token/jwt/jwt.guard.ts, packages/auth/src/token/simple/simple.guard.spec.ts, packages/auth/src/token/simple/simple.guard.ts, schematics/application/index.spec.ts, schematics/curd/index.spec.ts, schematics/edit/index.spec.ts, schematics/empty/index.spec.ts, schematics/list/index.spec.ts, schematics/module/index.spec.ts, schematics/ng-update/upgrade-rules/v15/index.spec.ts, schematics/plugin/index.spec.ts, schematics/plugin/plugin.code-style.spec.ts, schematics/plugin/plugin.default-language.spec.ts, schematics/plugin/plugin.docker.spec.ts, schematics/plugin/plugin.icon.spec.ts, schematics/plugin/plugin.network-env.spec.ts, schematics/plugin/plugin.rtl.spec.ts, schematics/plugin/plugin.sts.spec.ts, schematics/sta/index.spec.ts, schematics/tpl/index.spec.ts, schematics/utils/alain.spec.ts, schematics/utils/testing.ts, schematics/view/index.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(*): `canMatch` instead of `canLoad`

packages/theme/src/services/menu/menu.service.spec.ts, packages/theme/src/services/menu/menu.service.ts
- feat(theme): support custom validation result via `MenuService.find.cb`
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme): add `ignoreHide` of `MenuService.find`

angular.json, package.json, packages/abc/pdf/index.en-US.md, packages/abc/pdf/index.zh-CN.md, packages/abc/pdf/pdf.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:pdf): use`currentScale` instead of `_setScale`

packages/abc/st/st.component.ts, packages/abc/st/style/index.less
- close ng-alain/ng-alain#2383 
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix missing row class in fixed column

.stylelintrc
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: add `media-feature-range-notation`

packages/form/src/style/index.less, packages/theme/system/theme-dark.less, packages/theme/system/theme-default.less
- close https://github.com/ng-alain/ng-alain/issues/2382
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form): remote transfer body backgroun in dark

packages/form/src/sf.component.ts, packages/util/other/deep.ts
`deepCopy` has performance issues with a lot of recursion
- close https://github.com/ng-alain/ng-alain/issues/2376
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): fix out of memory error

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(15.2.0): release 15.2.0

package.json, packages/abc/pdf/pdf.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:pdf): fix pdf of latest version

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(15.2.1): release 15.2.1

packages/abc/st/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix error row class in fixed column title cell

packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2393
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): fix inheriting references to other of ui

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(16.0.1): release 16.0.1

azure-pipelines.yml, package.json, scripts/site/route-paths.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: fix ssr

packages/theme/system/ng/_preserve-white-spaces.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme): fix ant-btn preserve white spaces when is link type

packages/abc/date-picker/range.directive.ts, tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: clean codes

packages/abc/reuse-tab/reuse-tab.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:reuse-tab): fix cache

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(16.1.1): release 16.1.1

packages/abc/sg/demo/basic.md, packages/abc/st/demo/buttons.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st-data-source.ts, packages/abc/st/st-td.component.html, packages/abc/st/st.interfaces.ts, packages/abc/st/st.types.ts, packages/abc/st/test/st.spec.ts, packages/abc/sv/demo/basic.md
- close https://github.com/ng-alain/ng-alain/issues/2331
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): button support function method of `icon`, `className`

packages/abc/sv/sv-container.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(abc:sv): fix sv-container type

packages/theme/system/antd/_table.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:table): fix table image spacing

packages/abc/reuse-tab/public_api.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:reuse-tab): fix missing export cache

packages/auth/src/store/cookie-storage.service.spec.ts, packages/auth/src/store/cookie-storage.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(auth:cookie): fix cookie expires

packages/theme/src/services/title/title.service.spec.ts, packages/theme/src/services/title/title.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme:title): fix ignore empty title

packages/abc/sv/demo/border.md, packages/abc/sv/index.en-US.md, packages/abc/sv/index.zh-CN.md, packages/abc/sv/style/index.less, packages/abc/sv/sv-container.component.ts, packages/abc/sv/sv.component.ts, packages/abc/sv/sv.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2385
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:sv): add `bordered` property

.github/workflows/mirror-gitee.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: fix shallow update not allowed

.github/workflows/mirror-gitee.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: correct mirror gitee

packages/abc/theme-dark.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:onboarding): correct dark style

schematics/schema.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: add `defaultProject` in `schema.json`

packages/abc/st/style/index.less, packages/theme/layout-default/style/_aside.less, packages/theme/system/utils/_scrollbar.less
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[ ] No
```
=> style: fix `declaration-block-no-redundant-longhand-properties`

schematics/application/index.spec.ts, schematics/application/index.ts, schematics/utils/workspace.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): missing `fileReplacements` in Angular16

packages/theme/system/antd/_tag.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:theme): add `.tag-wrap-list-spacing` class

package.json
Ref:
- https://github.com/NG-ZORRO/ng-zorro-antd/issues/8131
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(*): temp downgrade `ng-zorro-antd` to `16.2.0`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(16.4.1): release 16.4.1

packages/chart/timeline/demo/max-axis.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: update demo

packages/abc/qr/index.en-US.md, packages/abc/qr/index.zh-CN.md, packages/abc/qr/qr.component.ts, packages/abc/qr/qr.module.ts, src/styles/_custom.less
Please use [nz-qrcode](https://ng.ant.design/components/qr-code) instead.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:qr): will be removed in 18.0.0

package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: upgrade ng-zorro-antd

.github/workflows/deploy-site.yml, .github/workflows/docker-build-doc-site.yml, docs/contributing.zh-CN.md, docs/server.en-US.md, docs/server.zh-CN.md, schematics/README.md, schematics/application/files/src/app/core/startup/startup.service.ts, schematics/application/schema.json, schematics/curd/schema.json, schematics/edit/schema.json, schematics/empty/schema.json, schematics/list/schema.json, schematics/module/schema.json, schematics/sta/schema.json, schematics/tpl/schema.json, schematics/view/schema.json, src/app/core/meta.service.ts, src/app/core/startup.service.ts, src/index.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: unified NG-ALAIN text mark

.vscode/settings.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: add `typescript.referencesCodeLens.enabled`

src/app/core/startup.service.ts, src/index.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: remove Hotjar script

_mock/user.ts, packages/mock/docs/rule.en-US.md, packages/mock/docs/rule.zh-CN.md, packages/mock/public_api.ts, packages/mock/src/interface.ts, packages/mock/src/mock.interceptor.spec.ts, packages/mock/src/mock.interceptor.ts, packages/mock/src/utils.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(mock): support asynchronous of response

packages/testing/src/delay.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(testing): add `delay` function

packages/theme/layout-default/style/_aside.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme): corrected menu can't scrolling

packages/auth/src/auth.config.ts, packages/mock/docs/getting-started.en-US.md, packages/mock/docs/getting-started.zh-CN.md, packages/mock/src/mock.config.ts, packages/mock/src/mock.interceptor.spec.ts, packages/mock/src/mock.interceptor.ts, packages/mock/src/provide.ts, packages/theme/src/config.ts, schematics/ng-update/upgrade-rules/v17/angularJson.ts, schematics/ng-update/upgrade-rules/v17/files/jsonSchemaModule.ts, schematics/ng-update/upgrade-rules/v17/index.spec.ts, schematics/ng-update/upgrade-rules/v17/index.ts, schematics/ng-update/upgrade-rules/v17/preloader.ts, schematics/ng-update/upgrade-rules/v17/replaceProvideConfig.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(mock): add `mockInterceptor`

packages/theme/src/services/preloader/preloader.spec.ts, packages/theme/src/services/preloader/preloader.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(theme:preloader): support ssr

packages/theme/src/provide.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(theme): add icon

packages/abc/reuse-tab/index.en-US.md, packages/abc/reuse-tab/index.zh-CN.md, packages/abc/reuse-tab/provide.ts, packages/abc/reuse-tab/public_api.ts, packages/abc/reuse-tab/reuse-tab-context-menu.component.html, packages/abc/reuse-tab/reuse-tab-context-menu.component.ts, packages/abc/reuse-tab/reuse-tab-context.component.ts, packages/abc/reuse-tab/reuse-tab-context.directive.ts, packages/abc/reuse-tab/reuse-tab.component.html, packages/abc/reuse-tab/reuse-tab.component.spec.ts, packages/abc/reuse-tab/reuse-tab.component.ts, packages/abc/reuse-tab/reuse-tab.module.ts, packages/abc/reuse-tab/reuse-tab.service.ts, src/app/app.config.ts, src/dev/layout.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:reuse-tab): add provide

schematics/application/files/src/app/layout/basic/basic.component.ts
```
[x] Bugfix
[ ] Feature
```
fix prefer-self-closing-tags error
```
[ ] Yes
[x] No
```
=> style(cli): fix prefer-self-closing-tags error

packages/abc/st/test/st-data-source.spec.ts, packages/abc/st/test/st.spec.ts, packages/theme/src/pipes/date/date.pipe.ts, packages/util/config/config.types.ts, packages/util/config/theme/pipe.type.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme:pipe:date): add global config

packages/auth/docs/getting-started.en-US.md, packages/auth/docs/getting-started.zh-CN.md, packages/auth/src/auth.config.ts, packages/auth/src/token/base.interceptor.spec.ts, packages/mock/src/mock.config.ts, packages/mock/src/mock.interceptor.spec.ts, packages/mock/src/mock.interceptor.ts, packages/mock/src/provide.ts, packages/theme/src/config.ts, packages/util/config/auth/auth.type.ts, packages/util/config/mock/mock.type.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: perf mock interceptor

packages/abc/cell/provide.ts, packages/abc/st/provide.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: type of widget registry items

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, docs/how-to-start.en-US.md, docs/how-to-start.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.0.0): release 17.0.0

schematics/ng-add/index.ts
close https://github.com/ng-alain/ng-alain/issues/2449
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(cli): fix node version

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, scripts/site/route-paths.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.0.1): release 17.0.1

package.json, schematics/package.json, scripts/ci/utils.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix cannot find module `@angular/cdk/schematics`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.0.2): release 17.0.2

schematics/application/files/src/app/core/startup/startup.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2425
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): correct null value handling

schematics/utils/ast.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): correct 'providers' spelling errors

packages/abc/sv/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:sv): fix bottom spacing in border mode

packages/util/pipes/filter/filter.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(util:pipe:filter): use `pure`

packages/abc/se/se.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:se): fix missing required of reactive

packages/form/src/widgets/array/array.widget.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form:array): fix invalid trackBy

package.json, schematics/ng-update/upgrade-rules/v17/index.spec.ts, schematics/ng-update/upgrade-rules/v17/index.ts, schematics/ng-update/upgrade-rules/v17/nljep.ts, yarn.lock
- https://github.com/angular/angular-cli/issues/25572
- https://github.com/angular/angular-cli/issues/26310
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: add `ng-less-javascript-enabled-patch`

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.0.5): release 17.0.5

packages/auth/src/auth.config.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf(auth): remove default value of `ignores`

packages/abc/st/st-export.ts
- close https://github.com/ng-alain/ng-alain/issues/2463
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): corrected error null value syntax

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/layout-default/layout-nav.component.spec.ts, packages/theme/layout-default/layout-nav.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:layout-default): add `hideEmptyChildren`

packages/theme/docs/locale.en-US.md, packages/theme/docs/locale.zh-CN.md, packages/theme/src/locale/languages/vi-VI.ts, packages/theme/src/locale/public_api.ts, schematics/core/lang.config.ts, schematics/docs/plugin.en-US.md
The commit message follows our guidelines: https://github.com/ng-alain/delon/blob/master/CONTRIBUTING.md#commit
Tests for the changes have been added (for bug fixes / features)
Docs have been added / updated (for bug fixes / features)
PR Type
[ ] Bugfix
[X] Feature
What is the current behavior?
N/A
Issue Number:
What is the new behavior?
N/A
Does this PR introduce a breaking change?
[ ] Yes
[X] No
Please …
=> feat: add Vietnamese locate

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.1.0): release 17.1.0

.github/workflows/docker-build-doc-site.yml, src/app/core/code/code.service.ts, src/app/core/code/files/package.json.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(site): fix stackblitz

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.2.0): release 17.2.0

.github/workflows/ci.yml, packages/theme/ng-package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: fix build

.github/workflows/ci.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: fix push

packages/abc/reuse-tab/reuse-tab.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:reuse-tab): fix can't cache when component is not used

packages/abc/cell/cell-host.directive.ts, packages/abc/cell/cell.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore(abc:cell): fix lint

packages/cache/docs/getting-started.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs(cache): remove `DelonCacheModule`

packages/theme/system/utils/_other.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme): correct `.no-data` text color in dark

.github/workflows/ci.yml, scripts/ci/build-artifacts.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> ci: fix build post

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(17.3.1): release 17.3.1

packages/auth/docs/qa.en-US.md, packages/auth/docs/qa.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
示例是错误的，少了一个参数
```
[ ] Yes
[x] No
```
=> docs(auth): typo `null` in demo

.github/workflows/ci.yml, packages/abc/notice-icon/notice-icon.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:notice-icon): fix incorrect unsubscription

packages/theme/docs/locale.en-US.md, packages/theme/docs/locale.zh-CN.md, packages/theme/src/locale/languages/ar-SA.ts, packages/theme/src/locale/public_api.ts, schematics/core/lang.config.ts, schematics/docs/plugin.en-US.md, schematics/docs/plugin.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
no arabic support in locale list
we can use arabic locale
```
[ ] Yes
[x] No
```
=> feat: adding Arabic locale

packages/abc/notice-icon/notice-icon.component.html, packages/abc/notice-icon/notice-icon.component.ts, packages/abc/notice-icon/notice-icon.spec.ts
- close https://github.com/ng-alain/delon/pull/1804
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:notice-icon): fix nz-tabset animation triggers panel height

packages/theme/src/services/http/http.client.ts
- close https://github.com/ng-alain/ng-alain/issues/2501
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(theme:http): fix type mismatch

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, schematics/application/index.ts, scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(18.0.0): release 18.0.0

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(18.0.1): release 18.0.1

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(18.0.2): release 18.0.2

packages/form/src/widgets/select/select.widget.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:select): fix incorrect default value of `showArrow`

packages/abc/let/index.en-US.md, packages/abc/let/index.zh-CN.md, packages/abc/let/let.directive.ts, packages/abc/let/let.module.ts
- Please use `@let` instead
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:let): will be removed in v19

packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.html, packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2507
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(abc:st): add `expandIcon` property

packages/theme/system/theme-dark.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(theme): fix dark style color

packages/abc/cell/cell.service.ts, packages/theme/src/pipes/date/date.pipe.ts, packages/util/config/theme/index.ts, packages/util/config/theme/pipe.type.ts, packages/util/date-time/time.ts, scripts/ci/build-artifacts.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme): support custom process of `_date` pipe

packages/abc/st/st-data-source.ts, packages/abc/st/test/st-data-source.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): correct default value of `date` type

packages/abc/lodop/lodop.service.ts, packages/abc/lodop/lodop.spec.ts, packages/util/config/abc/lodop.type.ts
- close #1821
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:lodop): support URL with parameters

src/app/layout/header/header.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: missing 17 doc link

packages/form/widgets/tree-select/schema.ts, packages/form/widgets/tree-select/widget.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(form:tree-select): add `change` of schema

packages/abc/st/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): fix submenu blank area to be clickable

packages/abc/st/demo/expand.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st.component.html, packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2507
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:st): a more friendly expandIcon

package.json, yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: bump ng-zorro-antd to 18.2.0

packages/abc/cell/cell.component.ts, packages/abc/hotkey/hotkey.directive.ts, packages/abc/hotkey/index.en-US.md, packages/abc/hotkey/index.zh-CN.md, packages/abc/st/st-td.component.html, packages/abc/st/st.component.html, packages/abc/st/st.module.ts, packages/form/src/sf.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> perf: optimizing `@let`

packages/form/src/widgets/select/demo/simple.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs(form:select): update demo

packages/abc/auto-focus/auto-focus.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(abc:auto-focus): bump signal

packages/abc/reuse-tab/public_api.ts, src/tsconfig.site.json, tsconfig.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor: enable isolatedModules compiler option

src/app/core/code/files/tsconfig.json.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> build: enable `strictStandalone` flag

packages/form/src/widgets/number/number.widget.ts, packages/form/widgets/cascader/schema.ts, packages/form/widgets/cascader/widget.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(form): bump ng-zorro 19

packages/abc/notice-icon/notice-icon-tab.component.html, packages/abc/notice-icon/notice-icon-tab.component.ts, packages/abc/notice-icon/notice-icon.component.html, packages/abc/notice-icon/notice-icon.component.ts, packages/abc/notice-icon/notice-icon.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2543
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:notice-icon): incorrect show list when `popoverVisible` control

packages/theme/layout-default/layout.service.ts, src/dev/layout.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2542
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(theme:layout-default): collapsed aside when screen is small

packages/abc/reuse-tab/reuse-tab.service.ts
- close https://github.com/ng-alain/ng-alain/issues/2540
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(abc:reuse-tab): fix can't be restored in cache

packages/abc/st/demo/cell.md, packages/abc/st/st-td.component.html, packages/abc/st/st.component.ts, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st.spec.ts
Related issues
- close https://github.com/ng-alain/ng-alain/issues/2527
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): type `cell` support `click`

packages/abc/st/demo/grouping-columns.md, packages/abc/st/st-column-source.ts, packages/abc/st/st.component.ts, packages/abc/st/st.types.ts
- close https://github.com/ng-alain/ng-alain/issues/2532
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fix can't `addRow` in group columns

packages/abc/st/st.component.html, packages/abc/st/st.types.ts, packages/abc/st/test/st-data-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/2380
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> fix(abc:st): fixed columns not aligned

schematics/tpl/schema.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(cli): fix Unknown argument: swaggerPath

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(19.0.1): release 19.0.1

packages/theme/layout-default/layout-nav.component.html, packages/theme/layout-default/layout-nav.component.spec.ts, packages/theme/src/services/menu/index.en-US.md, packages/theme/src/services/menu/index.zh-CN.md, packages/theme/src/services/menu/interface.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
=> feat(module:theme): add the `badgeOverflowCount` property to Menu

packages/abc/auto-focus/demo/simple.md, packages/abc/cell/demo/simple.md, packages/abc/notice-icon/demo/basic.md, packages/abc/notice-icon/demo/popover.md, packages/abc/notice-icon/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> docs: upgrade signal

packages/form/src/widgets/array/array.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/2554
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form:array): fix track to identify each item uniquely

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(19.1.0): release 19.1.0

packages/form/widgets/transfer/index.en-US.md, packages/form/widgets/transfer/index.zh-CN.md, packages/form/widgets/transfer/schema.ts, packages/form/widgets/transfer/widget.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form:transfer): add `oneWay`

packages/abc/st/demo/sort.md, packages/abc/st/index.en-US.md, packages/abc/st/index.zh-CN.md, packages/abc/st/st-column-source.ts, packages/abc/st/st.component.html, packages/abc/st/st.interfaces.ts, packages/abc/st/test/st-column-source.spec.ts, packages/util/config/abc/st.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:st): add sort directions

packages/form/widgets/cascader/demo/simple.md, packages/form/widgets/cascader/index.en-US.md, packages/form/widgets/cascader/index.zh-CN.md, packages/form/widgets/cascader/schema.ts, packages/form/widgets/cascader/widget.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
=> feat(form:cascader): add multiple

.husky/pre-commit, .npmrc, CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json, src/assets/yarn.lock.txt
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(19.2.0): release 19.2.0

packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/2558
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> fix(form): incorrect strict mode

packages/form/src/widgets/date/index.en-US.md, packages/form/src/widgets/date/index.zh-CN.md, packages/form/src/widgets/date/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/2560
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(form): support string array in `placeholder`

packages/abc/notice-icon/index.en-US.md, packages/abc/notice-icon/index.zh-CN.md, packages/abc/notice-icon/notice-icon-tab.component.html, packages/abc/notice-icon/notice-icon-tab.component.ts, packages/abc/notice-icon/notice-icon.component.html, packages/abc/notice-icon/notice-icon.component.ts, packages/abc/notice-icon/notice-icon.types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(abc:notice-icon): add click event of select

packages/theme/layout-default/index.en-US.md, packages/theme/layout-default/index.zh-CN.md, packages/theme/layout-default/layout-nav.component.html, packages/theme/layout-default/layout-nav.component.spec.ts, packages/theme/layout-default/style/fix/_sidebar-nav.less, packages/theme/layout-default/style/theme-dark.less, packages/theme/layout-default/style/theme-default.less, packages/theme/src/services/menu/index.en-US.md, packages/theme/src/services/menu/index.zh-CN.md, packages/theme/src/services/menu/interface.ts, packages/theme/src/services/menu/menu.service.ts, src/dev/layout.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:menu): add `render_type` of menu item

packages/abc/st/index.en-US.md, packages/abc/st/test/base.spec.ts, packages/abc/st/test/st.spec.ts
- rel #1854
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> test(abc:st): add `delay`

packages/abc/footer-toolbar/footer-toolbar.component.html, packages/abc/footer-toolbar/footer-toolbar.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> refactor(abc:footer-toolbar): migrate to signals

packages/form/src/widgets/checkbox/checkbox.widget.ts, packages/form/src/widgets/checkbox/index.en-US.md, packages/form/src/widgets/checkbox/index.zh-CN.md, packages/form/src/widgets/checkbox/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/2563
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> fix(form:checkbox): make deprecated of `span` property

packages/theme/src/services/modal/modal.helper.ts, packages/theme/src/services/modal/modal.spec.ts, src/app/shared/components/dialog/modal.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
=> feat(theme:modalhelper): support signal of params

package.json, packages/abc/notice-icon/notice-icon.component.html, packages/abc/notice-icon/notice-icon.component.ts, packages/abc/page-header/demo/standard.md, packages/abc/page-header/demo/structure.md, packages/abc/reuse-tab/reuse-tab.component.html, packages/abc/reuse-tab/reuse-tab.component.ts, packages/abc/st/st-column-source.ts, packages/theme/setting-drawer/setting-drawer.component.html, packages/theme/system/antd/_modal.less, src/app/routes/form-pages/validator/validator.component.html, src/assets/yarn.lock.txt, yarn.lock
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> chore: bump ng-zorro-antd to beta

schematics/application/files/src/app/shared/shared-delon.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
=> fix(schematics): remove obsolete modules

CHANGELOG.md, docs/changelog.en-US.md, docs/changelog.zh-CN.md, package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
=> release(20.0.2): release 20.0.2
