- src/core/theme/styles/app/variables.less
- src/core/theme/styles/themes/theme.less
```
[x] Bugfix
[ ] Feature
```
Theme color doesn't work in datepicker component.
Datepicker component renders correctly with the theme color you specified.
```
[ ] Yes
[x] No
```
> [Theme] Calendar Mixin

- docs/deploy.md
change "实现" -> "实际", "觉用" -> "常用".
```
[ ] Bugfix
[ ] Feature
[x ] Documentation content changes
```
Issue Number: 74
```
[ ] Yes
[ x] No
```
> fix the typo in deploy.md

- packages/abc/simple-table/simple-table.component.ts
```
[ ] Bugfix
[ ] Feature
```
Simple-Table内关于[scroll]属性的类型描述错误
```
[ ] Yes
[x] No
```
> fix simple-table scroll attribute type

- packages/abc/simple-table/index.md
Update @delon/abc/simple-table/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Update simple table docs

- packages/abc/charts/index.md
- packages/abc/charts/timeline/timeline.component.ts
开放更多关于G2的API,使得开发者更方便的使用G2功能
```
[ ] Bugfix
[x] Feature
```
#79 
```
[ ] Yes
[x] No
```
> 添加日期格式和标题位置API

- packages/abc/xlsx/xlsx.service.ts
```
[x] Bugfix
[ ] Feature
```
fixed XlsxService's bug when read excel files from local
```
[ ] Yes
[x] No
```
> fixed AdXlsxModule cannot read excel file from local life

- packages/abc/simple-table/index.md
- packages/abc/simple-table/simple-table.component.ts
- packages/abc/simple-table/simple-table.spec.ts
spelling mistakes;
```
[x ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> Spelling mistake

- packages/form/src/widgets/upload/upload.widget.ts
'argName' should be name
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> Fix upload widget ui params name wrong

- packages/abc/charts/pie/pie.component.ts
- packages/theme/styles/app/antd/_preserve-white-spaces.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: [512](https://github.com/cipchk/ng-alain/issues/512)
```
[ ] Yes
[x] No
```
> fixed #512 在分析页点击明细项，饼图会消失

- packages/util/src/array/array.service.ts
假如 pid = "abc1", 则 pid > 0 不成立，错了。
```
[x ] Bugfix
[ ] Feature
```
修正数组转化树形的错误，当 pid 为字符串的时候。
```
[ ] Yes
[x ] No
```
> pid can be a string.

- packages/theme/docs/menu.md
[Menu] 链接地址不正确
```
[X] Bugfix
[ ] Feature
```
> [Menu] 链接地址不正确

- .gitignore
```
[ x] Feature
```
ide生成的文件没有加入到gitignore文件
加入到gitignore文件
```
[ ] Yes
[ x] No
```
> 增加ignore文件

- packages/form/src/widgets/custom/demo/simple.md
- packages/form/src/widgets/custom/index.md
更新动态组件的Custom文档说明
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> 更新动态组件的Custom文档说明，避免掉坑

- docs/getting-started.md
- packages/schematics/docs/add.md
- packages/schematics/docs/getting-started.md
```
[x] Bugfix
[ ] Feature
```
npm 使用 tag 时要用 `@` 符号
`ng add ng-alain:next`
应为：
`ng add ng-alain@next`
https://docs.npmjs.com/getting-started/using-tags
```
[ ] Yes
[x] No
```
> fix(docs): fix invalid tag name "ng-alain:next"

- packages/theme/styles/app/delon/form.less
```
[x] Bugfix
[ ] Feature
```
Issue Number: #152 
```
[ ] Yes
[x] No
```
> fix(form): fix select width when search mode

- packages/form/src/utils.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/form/src/widgets/mention/mention.widget.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #167 
```
[ ] Yes
[x] No
```
> fix(form): fix missing render readOnly

- packages/abc/table/index.md
- packages/abc/table/table-data-source.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/685
```
[ ] Yes
[x] No
```
> refactor(abc:st): use _HttpClient instead of HttpClient

- packages/abc/global-footer/demo/custom.md
- packages/abc/global-footer/global-footer-item.component.ts
- packages/abc/global-footer/global-footer.component.html
- packages/abc/global-footer/global-footer.component.ts
- packages/abc/global-footer/global-footer.module.ts
- packages/abc/global-footer/global-footer.spec.ts
- packages/abc/global-footer/global-footer.types.ts
- packages/abc/global-footer/index.md
- packages/abc/global-footer/public_api.ts
- packages/abc/global-footer/style/index.less
- src/app/routes/dev/demo/demo.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:global-footer): support item custom template

- packages/theme/src/services/settings/settings.service.ts
- packages/theme/src/services/settings/settings.spec.ts
batch replacement layout property
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(theme:setting.service): support batch replacement layout property

- docs/getting-started.zh-CN.md
current screenshot doesn't match the 1st installation method, Developer  may be confused
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refine doc to add 2nd installation method

- build-schematics.sh
- packages/schematics/application/index.ts
- packages/schematics/collection.json
- packages/schematics/docs/generate.md
- packages/schematics/tpl/index.spec.ts
- packages/schematics/tpl/index.ts
- packages/schematics/tpl/schema.json
- packages/schematics/tpl/schema.ts
- packages/schematics/utils/alain.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add custom template in generate command line

- packages/theme/src/services/http/http.client.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/694
```
[ ] Yes
[x] No
```
> fix(theme:_HttClient): fix invalid parse of param

- packages/util/src/time/time.spec.ts
- packages/util/src/time/time.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/696
```
[ ] Yes
[x] No
```
> fix(util:getTimeDistance): fix missing -today

- packages/form/src/widgets/cascader/cascader.widget.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/695
```
[ ] Yes
[x] No
```
> fix(form:cascader): fix missing showSearch

- packages/abc/table/index.md
add description to loading property
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> add description to loading property

- docs/upgrade-v2.en-US.md
- docs/upgrade-v2.zh-CN.md
- packages/abc/footer-toolbar/demo/basic.md
- packages/abc/footer-toolbar/footer-toolbar.component.html
- packages/abc/footer-toolbar/footer-toolbar.component.ts
- packages/abc/footer-toolbar/footer-toolbar.spec.ts
- packages/abc/page-header/demo/image.md
- packages/abc/page-header/demo/simple.md
- packages/abc/page-header/demo/standard.md
- packages/abc/page-header/demo/structure.md
- packages/abc/page-header/page-header.component.ts
- packages/abc/page-header/page-header.spec.ts
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
| Component        | Old ContentChild | New Property | ng update | Description |
|------------------|------------------|--------------|-----------|-------------|
| `st`             | `body`           | `body`       | √         | -           |
| `st`             | `expand`         | `expand`     | √         | -           |
| `footer-toolbar` | `extra`          | `extra`      | √         | -           |
| `page-header`    | `breadcrumb`     | `breadcrumb` | √         | -           |
| `page-header`    | `logo`           | `logo`       | √         | -           |
| `page-header`    | `action`         | `action`     | √         | -           |
| `page-header`    | `content`        | `content`    | √         | -           |
| `page-header`    | `extra`          | `extra`      | √         | - …
> refactor(all): use input instead of ContentChild

- packages/abc/page-header/index.md
- packages/abc/page-header/page-header.component.html
- packages/abc/page-header/page-header.component.ts
- packages/abc/page-header/page-header.spec.ts
- packages/abc/page-header/style/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:page-header): add loading & wide properies

- packages/schematics/application/index.ts
- scripts/ci/build-schematics.sh
- scripts/ci/deploy.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematice): add generate color less

- package.json
- scripts/git/commit-message.json
- scripts/git/commit-msg.js
- scripts/git/validate-commit-message.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: add git hook to check commit messages

- packages/abc/page-header/style/index.less
- packages/theme/styles/app/antd/_preserve-white-spaces.less
- page-header
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme): fix white spaces

- packages/schematics/docs/getting-started.en-US.md
- packages/schematics/docs/getting-started.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> doc: fix typo in doc

- .travis.yml
- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/ci/deploy.sh
- scripts/publish/publish-scaffold.js
- scripts/publish/publish.js
- scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> release(2.0.0-beta.4): release 2.0.0-beta.4

- packages/schematics/application/files/src/app/layout/default/header/components/fullscreen.component.ts
- packages/schematics/application/files/src/app/layout/default/header/components/search.component.ts
- packages/schematics/application/files/src/app/layout/default/header/components/storage.component.ts
- packages/schematics/application/files/src/app/layout/default/sidebar/sidebar.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(schematics): refactor i18n service

- packages/schematics/application/files/src/app/core/startup/startup.service.ts
- packages/theme/styles/app/utils/other.less
- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:theme): add page loading styles

- packages/schematics/plugin/plugin.code-style.spec.ts
- packages/schematics/plugin/plugin.code-style.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:code-style): upgrade husky

- packages/form/src/widget.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #211
```
[ ] Yes
[x] No
```
> fix(module:form): fix invalid disabled status when is readOnly

- .travis.yml
- docs/i18n.md
- packages/form/src/widgets/date/date.widget.ts
- packages/schematics/application/files/src/app/app.module.ts
- packages/theme/src/pipes/date/date.pipe.spec.ts
- packages/theme/src/pipes/date/date.pipe.ts
```
[ ] Bugfix
[x] Feature
```
Issue Number: #113
```
[ ] Yes
[x] No
```
>  fix(module:date): all dates supported unit timestamp

- packages/form/src/widgets/date/date.widget.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: #219 
```
[ ] Yes
[x] No
```
> fix(module:form): fix missing nzShowTime in date widgets

- packages/schematics/edit/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
- packages/schematics/edit/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/722
```
[ ] Yes
[x] No
```
> fix(schematics): fix invalid msgSrv property in edit page

- .travis.yml
- scripts/ci/deploy.sh
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
Issue Number: #216
```
[ ] Yes
[x] No
```
> ci: allow `build_artifacts` builds to fail on Travis

- packages/auth/docs/getting-started.md
- packages/auth/docs/send.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix the typo and link errors in document

- package.json
- packages/abc/reuse-tab/style/index.less
- packages/abc/table/style/index.less
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/test/table-column-source.spec.ts
- packages/theme/src/theme.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:st): fix filter table header in ant design 3.10

- packages/schematics/application/files/src/app/core/startup/startup.service.ts
- packages/schematics/application/files/src/app/layout/default/header/components/user.component.ts
- packages/schematics/application/index.ts
- scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/735
```
[ ] Yes
[x] No
```
> fix(schematics): fix used translate when not i18n

- packages/theme/styles/app/delon/search-form-pro.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> chore: update styles(ant-design 3.10.1)

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/abc/table/demo/expand.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: Releases
```
```
[x] Yes
[ ] No
```
> release(2.0.0-rc.0): release 2.0.0-rc.0

- packages/abc/table/test/table-data-source.spec.ts
- packages/abc/table/test/table.spec.ts
- packages/abc/view/style/index.less
- packages/theme/src/pipes/yn/yn.pipe.spec.ts
- packages/theme/src/pipes/yn/yn.pipe.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(module:theme:yn): new style

- packages/schematics/curd/schema.json
- packages/schematics/docs/add.en-US.md
- packages/schematics/docs/add.zh-CN.md
- packages/schematics/docs/generate.en-US.md
- packages/schematics/docs/generate.zh-CN.md
- packages/schematics/docs/plugin.en-US.md
- packages/schematics/docs/plugin.zh-CN.md
- packages/schematics/edit/schema.json
- packages/schematics/empty/schema.json
- packages/schematics/list/schema.json
- packages/schematics/view/schema.json
- scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(schematics): fix repeat alias name

- packages/mock/src/mock.interceptor.spec.ts
- packages/mock/src/mock.interceptor.ts
e.g:
```
/fn/queryString?a=1&b=1&b=2&b=3
```
generateor
```
queryString = { a: '1', b: [ '1', '2', '3'] };
```
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:mock): support array params of queryString

- packages/form/src/widget.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/754
```
[ ] Yes
[x] No
```
> fix(module:form): fix attempt to use a destroyed error

- packages/theme/styles/variable/color.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme): fix grey color values

- packages/schematics/application/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add color less when running ng commend

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add remove method

- packages/form/src/sf-item-wrap.component.ts
- packages/form/src/widgets/checkbox/checkbox.widget.html
- packages/form/src/widgets/checkbox/checkbox.widget.spec.ts
- packages/form/src/widgets/checkbox/checkbox.widget.ts
- issues #258
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf): fix missing title

- packages/abc/table/demo/buttons.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- feat(module:st): add icon & text coexist
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:st): fix invalid trigger when used icon & pop

- packages/abc/table/demo/type.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-column-source.ts
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-column-source.spec.ts
- packages/abc/table/test/table-data-source.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add no type

- packages/schematics/application/files/src/app/app.module.ts
- pull https://github.com/ng-alain/ng-alain/pull/762
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
> fix(schematics): GLOBAL_THIRD_MDOULES changed to GLOBAL_THIRD_MODULES

- packages/abc/sidebar-nav/index.md
- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- packages/theme/src/services/menu/interface.ts
- packages/theme/src/services/menu/menu.service.ts
- packages/theme/styles/layout/default/fix/sidebar-nav.less
- packages/theme/styles/layout/default/index.en-US.md
- packages/theme/styles/layout/default/index.zh-CN.md
- packages/theme/styles/layout/default/variable.less
- add nav image width & height
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sidebar-nav): add icon more properties

- packages/theme/ng-package.json
- packages/theme/package.json
- packages/theme/src/services/menu/menu.service.spec.ts
- packages/theme/src/services/menu/menu.service.ts
- packages/theme/tsconfig.lib.json
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme:menu): fix shortcut children polluted

- packages/mock/src/mock.interceptor.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> style(module:mock): optimize log style

- packages/theme/docs/tools.en-US.md
- packages/theme/docs/tools.zh-CN.md
- packages/theme/styles/app/widgets/scrollbar.less
- scripts/ci/deploy.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:theme): add scrollbar style service of div

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-data-source.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add rowClassName property

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 2.0.0-rc.3
```
```
[ ] Yes
[x] No
```
> release(2.0.0-rc.3): release 2.0.0-rc.3

- packages/form/spec/base.spec.ts
- packages/form/src/widgets/upload/index.md
- packages/form/src/widgets/upload/upload.widget.spec.ts
- packages/form/src/widgets/upload/upload.widget.ts
close #273
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf): fix missing size property of upload widget

- packages/schematics/application/files/src/app/routes/routes-routing.module.ts
- packages/schematics/application/files/src/app/routes/routes.module.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add SimpleGuard of root router

- packages/form/src/widgets/checkbox/checkbox.widget.html
- packages/form/src/widgets/checkbox/checkbox.widget.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:checkbox): fix delayed rendering when onpush strategy

- packages/abc/table/demo/data.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add clear & clearStatus methods

- packages/theme/public_api.ts
- packages/theme/src/services/http/http.decorator.spec.ts
- packages/theme/src/services/http/http.decorator.ts
- packages/theme/src/services/http/index.en-US.md
- packages/theme/src/services/http/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:http): support decorator @GET, @POST etc

- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- #290
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:autocomplete): fix missing value

- packages/schematics/core/lang.config.ts
- packages/schematics/docs/plugin.en-US.md
- packages/schematics/docs/plugin.zh-CN.md
- packages/theme/docs/locale.en-US.md
- packages/theme/docs/locale.zh-CN.md
- packages/theme/src/locale/languages/tr-TR.ts
- packages/theme/src/locale/public_api.ts
- #288
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:theme): add tr-TR locale

- packages/form/spec/form.spec.ts
- packages/form/src/sf.component.html
- packages/form/src/sf.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:button): fix invalid button size

- packages/theme/src/services/title/title.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme:title): fix default property should  be not read-only

- packages/theme/styles/app/ng/preserve-white-spaces.less
- packages/theme/styles/app/utils/color.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme:style): fix dropdown + button spacing when closed preserve

- packages/abc/page-header/page-header.component.html
- packages/abc/page-header/page-header.component.ts
- packages/abc/page-header/page-header.spec.ts
- src/app/routes/dev/home/home.component.ts
- src/app/routes/dev/layout.component.html
- src/app/routes/dev/layout.component.ts
- src/app/routes/dev/pages/page.component.ts
- fix: refresh title when router changed #293
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:page-header): should be clean old breadcrumb data when changes

- CHANGELOG.md
- README.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 2.0.1
```
```
[ ] Yes
[x] No
```
> release(2.0.1): release 2.0.1

- packages/schematics/list/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(schematics): fix template in list command

- packages/abc/table/table.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:st): should clean filter style when not filter

- README.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/chart/custom/index.en-US.md
- packages/chart/custom/index.zh-CN.md
- packages/chart/docs/faq.en-US.md
- packages/chart/docs/faq.zh-CN.md
- packages/chart/docs/getting-started.md
- packages/form/docs/customize.en-US.md
- packages/form/docs/customize.zh-CN.md
- packages/form/docs/error.md
- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/docs/layout.md
- packages/form/docs/qa.md
- packages/form/docs/schema.md
- packages/form/src/interface.ts
- packages/form/src/sf.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: repair mode

- docs/upgrade-v2.en-US.md
- docs/upgrade-v2.zh-CN.md
- packages/form/docs/qa.md
easy to understand.
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> correct misspelling word

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:release 7.0.0-rc.0
```
```
[ ] Yes
[ ] No
```
> release(7.0.0-rc.0): release 7.0.0-rc.0

- packages/mock/docs/getting-started.en-US.md
- packages/mock/docs/getting-started.zh-CN.md
- packages/mock/ng-package.json
- packages/mock/package.json
- packages/mock/src/mock.config.ts
- packages/mock/src/mock.interceptor.spec.ts
- packages/mock/src/mock.interceptor.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:mock): add executeOtherInterceptors config

- packages/chart/timeline/index.md
- packages/chart/timeline/timeline.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:chart:timeline): remove tickCount

- packages/util/public_api.ts
- packages/util/src/addon/index.en-US.md
- packages/util/src/addon/index.zh-CN.md
- src/site.config.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:util): export stringTemplateOutlet

- packages/form/spec/base.spec.ts
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/date/date.widget.ts
- packages/form/src/widgets/time/time.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/831
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf): shoule trigger detect change when reset value

- packages/auth/docs/get.md
- packages/auth/docs/getting-started.en-US.md
- packages/auth/docs/getting-started.zh-CN.md
- packages/auth/docs/guard.md
- packages/auth/docs/send.md
- packages/auth/docs/service.en-US.md
- packages/auth/docs/service.zh-CN.md
- packages/auth/docs/set.md
- packages/auth/ng-package.json
- packages/auth/package.json
- packages/auth/src/auth.config.ts
- packages/auth/src/token/base.interceptor.spec.ts
- packages/auth/src/token/base.interceptor.ts
- packages/auth/src/token/helper.ts
- packages/auth/src/token/interface.ts
- packages/auth/src/token/jwt/jwt.guard.ts
- packages/auth/src/token/simple/simple.guard.ts
- packages/auth/src/token/simple/simple.interceptor.spec.ts
- packages/auth/src/token/token.service.spec.ts
- packages/auth/src/token/token.service.ts
- remove redirect property
- close https://github.com/ng-alain/ng-alain/issues/835
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(module:auth): add referrer property

- packages/theme/styles/layout/default/aside.less
- packages/theme/styles/layout/default/variable.less
- close https://github.com/ng-alain/ng-alain/issues/837
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme): fix keeping show scroll bar in firefox

- packages/abc/sidebar-nav/index.md
- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- packages/theme/src/services/menu/index.en-US.md
- packages/theme/src/services/menu/index.zh-CN.md
- packages/theme/src/services/menu/interface.ts
- packages/theme/src/services/menu/menu.service.spec.ts
- packages/theme/src/services/menu/menu.service.ts
- packages/theme/styles/layout/default/fix/_sidebar-nav.less
- src/app/routes/dev/layout.component.ts
- add disabled of Menu
- removed linkExact property
- close https://github.com/ng-alain/ng-alain/issues/264
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sidebar-nav): add disabledAcl property

- packages/cache/src/cache.service.ts
- packages/cache/src/cache.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/846
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:cache): fix specified storage type parameters

- packages/form/src/sf-item.component.ts
- packages/form/src/utils.ts
- packages/form/src/widget.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/form/src/widgets/cascader/cascader.widget.ts
- packages/form/src/widgets/cascader/demo/simple.md
- packages/form/src/widgets/cascader/index.md
- packages/form/src/widgets/mention/demo/simple.md
- packages/form/src/widgets/mention/mention.widget.ts
- packages/form/src/widgets/upload/demo/simple.md
- packages/form/src/widgets/upload/upload.widget.ts
- async ng-zorro-antd 7.0.0-rc.1
- close https://github.com/ng-alain/delon/issues/257
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf): should based on item unsubscription

- packages/abc/reuse-tab/index.en-US.md
- packages/abc/reuse-tab/index.md
- packages/abc/reuse-tab/index.zh-CN.md
- packages/abc/reuse-tab/reuse-tab.component.spec.ts
- packages/abc/reuse-tab/reuse-tab.component.ts
- packages/abc/reuse-tab/reuse-tab.interfaces.ts
- packages/abc/reuse-tab/reuse-tab.service.spec.ts
- packages/abc/reuse-tab/reuse-tab.service.ts
- packages/theme/src/services/scroll/index.en-US.md
- packages/theme/src/services/scroll/index.zh-CN.md
- packages/theme/src/services/scroll/scroll.service.spec.ts
- packages/theme/src/services/scroll/scroll.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:reuse-tab): add keeping scroll property

- packages/form/src/widgets/array/array.widget.html
- packages/form/src/widgets/array/array.widget.spec.ts
- close #348
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf): fix invalid trigger submit via add button

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/schematics/application/files/src/app/routes/routes-routing.module.ts
- packages/schematics/application/files/src/app/routes/routes.module.ts
- packages/schematics/application/index.ts
- close https://github.com/ng-alain/ng-alain/issues/845
- close https://github.com/ng-alain/delon/pull/342
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.2
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.2): release 7.0.0-rc.2

- packages/theme/src/services/scroll/scroll.service.ts
- packages/theme/src/theme.module.ts
- packages/theme/src/win_tokens.ts
- remove duplicate icon
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme): fix not found window value

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.3
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.3): release 7.0.0-rc.3

- packages/form/spec/base.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.html
- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/form/src/widgets/autocomplete/demo/simple.md
- close https://github.com/ng-alain/delon/issues/359
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:autocomplete):  fix invalid value when item is SFSchemaEnum

- .vscode/settings.json
- package.json
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- close #363
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:st): fix disabled check all when  all data is disabled

- packages/abc/reuse-tab/reuse-tab.component.html
- packages/abc/reuse-tab/reuse-tab.component.spec.ts
- packages/abc/reuse-tab/reuse-tab.component.ts
- packages/abc/reuse-tab/style/index.less
- close #361
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:reuse-tab): fix overflow when route changed

- packages/abc/edit/style/index.less
- close #370
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:se): fix error message style

- packages/abc/sidebar-nav/index.md
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- closes #373, closes #365
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sidebar-nav): add recursivePath property

- package.json
- packages/abc/avatar-list/package.json
- packages/abc/edit/edit-container.component.ts
- packages/abc/edit/edit.spec.ts
- packages/abc/error-collect/error-collect.component.ts
- packages/abc/error-collect/error-collect.spec.ts
- packages/abc/grid/grid-container.component.ts
- packages/abc/grid/grid.spec.ts
- packages/abc/image/image.directive.ts
- packages/abc/image/image.spec.ts
- packages/abc/page-header/page-header.component.ts
- packages/abc/page-header/page-header.spec.ts
- packages/abc/qr/qr.component.ts
- packages/abc/qr/qr.spec.ts
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- packages/abc/view/view-container.component.ts
- packages/abc/view/view.spec.ts
- packages/abc/xlsx/xlsx.directive.ts
- packages/cache/src/cache.service.ts
- packages/util/src/other/other.ts
- src/app/routes/dev/demo/demo.component.ts
- close https://github.com/ng-alain/ng-alain/issues/870
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:*): fix losing global config

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish-scaffold.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.4
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.4): release 7.0.0-rc.4

- packages/form/src/widgets/radio/demo/simple.md
- packages/form/src/widgets/radio/index.en-US.md
- packages/form/src/widgets/radio/index.zh-CN.md
- packages/form/src/widgets/radio/radio.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/878
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sf:radio): add change event

- packages/mock/src/mock.service.spec.ts
- packages/mock/src/mock.service.ts
- close https://github.com/ng-alain/ng-alain/issues/879
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:mock): fix `/:id` does not match `user/1`

- packages/form/src/widgets/number/number.widget.ts
- close #381
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:number): fix missing integer type

- packages/form/src/widgets/upload/index.md
- packages/form/src/widgets/upload/upload.widget.spec.ts
- packages/form/src/widgets/upload/upload.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/862
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sf:upload): add fileList property

- packages/chart/bar/bar.component.ts
- packages/chart/gauge/gauge.component.ts
- packages/chart/mini-area/mini-area.component.ts
- packages/chart/mini-bar/mini-bar.component.ts
- packages/chart/pie/pie.component.ts
- packages/chart/radar/radar.component.ts
- packages/chart/single-bar/single-bar.component.ts
- packages/chart/tag-cloud/tag-cloud.component.ts
- packages/chart/timeline/timeline.component.ts
- packages/chart/water-wave/water-wave.component.ts
- src/app/routes/dev/demo/demo.component.ts
- close #377
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: performance
```
```
[ ] Yes
[x] No
```
> perf(module:chart): optimize g2 performance

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/882
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add expand event in change property

- packages/form/src/widgets/upload/index.md
- packages/form/src/widgets/upload/upload.widget.ts
- close #389
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sf:upload): add extra properties

- package.json
- packages/abc/table/demo/render.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-column-source.spec.ts
- packages/abc/table/test/table.spec.ts
- close #393
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add `iif` in column

- packages/theme/docs/global.en-US.md
- packages/theme/docs/global.zh-CN.md
- packages/theme/styles/variable/_global.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:theme): add text, icon, width more sizes

- packages/theme/src/services/title/title.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme:title): fix i18n will auto call setTitle

- package.json
- packages/schematics/application/index.ts
```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
```
```
[ ] Yes
[x] No
```
> style: import ng-alain-codelyzer

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.5
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.5): release 7.0.0-rc.5

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.6
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.6): release 7.0.0-rc.6

- packages/abc/down-file/down-file.directive.ts
- packages/abc/down-file/down-file.spec.ts
- packages/abc/image/image.directive.ts
- packages/abc/image/image.spec.ts
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-column-source.ts
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-column-source.spec.ts
- packages/abc/table/test/table-data-source.spec.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/891
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add skip & limit pagination type

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/spec/schema.spec.ts
- packages/form/src/sf.component.ts
- packages/form/src/utils.ts
- packages/form/src/widget.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/boolean/boolean.widget.spec.ts
- packages/form/src/widgets/cascader/cascader.widget.spec.ts
- packages/form/src/widgets/cascader/cascader.widget.ts
- packages/form/src/widgets/checkbox/checkbox.widget.spec.ts
- packages/form/src/widgets/custom/custom.widget.spec.ts
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/mention/mention.widget.spec.ts
- packages/form/src/widgets/radio/radio.widget.spec.ts
- packages/form/src/widgets/rate/rate.widget.html
- packages/form/src/widgets/rate/rate.widget.spec.ts
- packages/form/src/widgets/rate/rate.widget.ts
- packages/form/src/widgets/select/select.widget.spec.ts
- packages/form/src/widgets/select/select.widget.ts
- packages/testing/src/zorro.ts
- fix(module:sf): fix custom widget allow re-attach
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:sf): add onlyVisual property in sf component

- packages/schematics/docs/generate.en-US.md
- packages/schematics/docs/generate.zh-CN.md
- packages/schematics/tpl/index.ts
- packages/schematics/tpl/schema.ts
- close #409
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(schematics): add external fix function in tpl command

- .prettierrc
- .vscode/settings.json
- packages/abc/table/demo/export.md
- packages/abc/table/demo/statistical.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-data-source.spec.ts
- packages/abc/table/test/table.spec.ts
- src/app/routes/dev/demo/demo.component.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add statistical

- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- close #387
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:autocomplete): fix losing defualt value

- packages/abc/edit/edit.component.ts
- packages/abc/edit/edit.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/897
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:edit): fix should contain dirty check

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-data-source.spec.ts
- close #419
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:st): add process in STReq

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release(7.0.0-rc.7): release 7.0.0-rc.7
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.7): release 7.0.0-rc.7

- packages/form/spec/schema.spec.ts
- packages/form/src/model/form.property.factory.ts
- src/app/routes/dev/demo/demo.component.ts
- close #428
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf): fix invalid request in $ref property

- scripts/ci/build-schematics.sh
- close #427
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> ci: fix release version in package

- packages/abc/edit/edit.component.ts
- packages/abc/edit/edit.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/899
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:se): fix error status in first visual

- packages/theme/styles/app/ng/_preserve-white-spaces.less
- close https://github.com/ng-alain/ng-alain/issues/900
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:theme): fix button + button spacing of transfer options when enabled preserveWhitespaces

- packages/form/docs/error.md
- packages/form/spec/form.spec.ts
- packages/form/src/model/form.property.ts
- packages/form/src/validator.factory.ts
- packages/form/src/widgets/checkbox/checkbox.widget.html
- packages/form/src/widgets/checkbox/checkbox.widget.spec.ts
- packages/form/src/widgets/checkbox/checkbox.widget.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:checkbox): fix invalid indeterminate status

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.8
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.8): release 7.0.0-rc.8

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/src/config.ts
- packages/form/src/model/form.property.ts
- packages/form/src/sf.component.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/form/src/widgets/autocomplete/index.md
- close #438
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(module:sf:autocomplete): fix invalid custom email suffix by enum

- .vscode/settings.json
- packages/abc/date-picker/date-picker.config.ts
- packages/abc/date-picker/demo/shortcut.md
- packages/abc/date-picker/index.en-US.md
- packages/abc/date-picker/index.zh-CN.md
- packages/abc/date-picker/range.component.html
- packages/abc/date-picker/range.component.ts
- packages/abc/date-picker/range.spec.ts
- packages/util/src/time/time.spec.ts
- packages/util/src/time/time.ts
fix(module:util:getTimeDistance): fix used `weekStartsOn: 1` in week
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(module:range-picker): add shortcut property

- scripts/git/commit-message.json
- scripts/git/commit-msg.js
- scripts/git/validate-commit-message.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: update scopes of git commit
```
```
[ ] Yes
[x] No
```
> chore: update scopes of git commit

- packages/schematics/application/index.spec.ts
- packages/schematics/application/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(schematics): add VsCode extension recommendations in ng add

- packages/abc/table/table-column-source.ts
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/test/table-data-source.spec.ts
- packages/form/src/widgets/number/index.zh-CN.md
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/909
```
[ ] Yes
[x] No
```
> fix(module:st): fix sort order data should be in user click order

- packages/theme/styles/layout/default/fix/_sidebar-nav.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar): fix invalid menu item ellipsis when text overflow

- packages/abc/sidebar-nav/demo/basic.md
- packages/abc/sidebar-nav/index.en-US.md
- packages/abc/sidebar-nav/index.zh-CN.md
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/theme/styles/layout/default/fix/_sidebar-nav.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf(abc:sidebar): optimize dom rendering

- package.json
- packages/abc/edit/edit.component.html
- packages/abc/edit/edit.component.ts
- packages/abc/edit/edit.spec.ts
- packages/abc/edit/index.en-US.md
- packages/abc/edit/index.zh-CN.md
- packages/schematics/application/index.spec.ts
- packages/schematics/curd/index.spec.ts
- packages/schematics/edit/index.spec.ts
- packages/schematics/empty/index.spec.ts
- packages/schematics/list/index.spec.ts
- packages/schematics/plugin/plugin.default-language.spec.ts
- packages/schematics/plugin/plugin.docker.spec.ts
- packages/schematics/plugin/plugin.icon.spec.ts
- packages/schematics/utils/testing.ts
- packages/schematics/view/index.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/892
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:se): add labelWidth property

- packages/abc/sidebar-nav/demo/basic.md
- packages/abc/sidebar-nav/index.en-US.md
- packages/abc/sidebar-nav/index.zh-CN.md
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- packages/theme/src/services/menu/interface.ts
- close https://github.com/ng-alain/ng-alain/issues/913
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sidebar-nav): add  openStrictly property

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-column-source.spec.ts
- packages/abc/table/test/table-data-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/915
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): support custom function of noIndex

- docs/import.en-US.md
- docs/import.zh-CN.md
- packages/chart/docs/getting-started.en-US.md
- packages/chart/docs/getting-started.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0-rc.9
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.9): release 7.0.0-rc.9

- .travis.yml
- packages/form/src/widgets/checkbox/checkbox.widget.ts
- scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix LocaleData type

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish-scaffold.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe:  release 7.0.0-rc.10
```
```
[ ] Yes
[x] No
```
> release(7.0.0-rc.10): release 7.0.0-rc.10

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- src/app/core/code.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.0
```
```
[ ] Yes
[x] No
```
> release(7.0.0): release 7.0.0

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish-scaffold.js
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.1
```
```
[ ] Yes
[x] No
```
> release(7.0.1): release 7.0.1

- packages/abc/table/table.component.ts
- close https://github.com/ng-alain/ng-alain/issues/935
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix losing req config

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.2
```
```
[ ] Yes
[x] No
```
> release(7.0.2): release 7.0.2

- package.json
- packages/abc/table/table.component.html
- packages/form/src/widgets/transfer/transfer.widget.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/946
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix styles of filter button

- packages/abc/table/table-column-source.ts
- packages/abc/table/test/table-column-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/949
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix invalid number type of width

- packages/abc/edit/edit.component.html
- packages/abc/edit/edit.component.ts
- packages/abc/edit/edit.spec.ts
- packages/abc/edit/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/972
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:se): should be keeping placeholder when content is empty

- packages/abc/table/table.component.ts
- close https://github.com/ng-alain/ng-alain/issues/936
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix losing global config in modal or drawer

- packages/abc/result/result.component.html
- packages/abc/result/result.spec.ts
- close https://github.com/ng-alain/delon/pull/472
- close https://github.com/ng-alain/ng-alain/issues/967
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:result): use nztype instead of class anticon

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.0.3
```
```
[ ] Yes
[x] No
```
> release(7.0.3): release 7.0.3

- packages/abc/table/demo/statistical.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-data-source.spec.ts
```
[ ] Bugfix
[ ] Feature
```
Issue Number: #489
```
[x] Yes
[ ] No
```
> refactor(abc:st): currenty rename to currency

- packages/form/src/widgets/checkbox/checkbox.widget.html
- packages/form/src/widgets/checkbox/checkbox.widget.spec.ts
- packages/form/src/widgets/checkbox/checkbox.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/990
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(sf:checkbox): fix invalid trigger check-all when click input

- packages/form/src/widgets/select/index.md
- packages/form/src/widgets/select/select.widget.html
- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/995
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(sf:select): fix invalid clear value

- packages/abc/view/demo/basic.md
- packages/abc/view/index.en-US.md
- packages/abc/view/index.zh-CN.md
- packages/abc/view/style/index.less
- packages/abc/view/view.component.html
- packages/abc/view/view.component.ts
- packages/abc/view/view.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/994
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sv): add unit property

- packages/abc/qr/demo/basic.md
- packages/abc/qr/index.zh-CN.md
- packages/abc/qr/qr.service.ts
- packages/abc/qr/qr.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:qr): add support unicode value

- package.json
- packages/schematics/docs/plugin.en-US.md
- packages/schematics/docs/plugin.zh-CN.md
- packages/schematics/plugin/files/sts/_fix.js
- packages/schematics/plugin/files/sts/swagger-edit/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
- packages/schematics/plugin/files/sts/swagger-edit/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
- packages/schematics/plugin/files/sts/swagger-edit/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/plugin/files/sts/swagger-list/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.html
- packages/schematics/plugin/files/sts/swagger-list/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.spec.ts
- packages/schematics/plugin/files/sts/swagger-list/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/plugin/index.ts
- packages/schematics/plugin/plugin.sts.spec.ts
- packages/schematics/plugin/plugin.sts.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cli:plugin:sts): add sts plugin

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.1.0
```
```
[ ] Yes
[x] No
```
> release(7.1.0): release 7.1.0

- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1001
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix missing trigger expand event when click expand icon

- packages/schematics/application/files/src/app/layout/passport/passport.component.html
- scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix removed header-i18n when no-include i18n

- packages/abc/image/demo/error.md
- packages/abc/image/image.directive.ts
- close https://github.com/ng-alain/ng-alain/issues/1003
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:_src): fix invalid size

- packages/form/src/widgets/radio/demo/simple.md
- packages/form/src/widgets/radio/radio.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1006
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(sf:radio): fix async data invlid render

- packages/abc/reuse-tab/index.en-US.md
- packages/abc/reuse-tab/index.zh-CN.md
- packages/abc/reuse-tab/reuse-tab.component.html
- packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1010
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:reuse-tab): add `tabBarExtraContent` `tabBarStyle` `tabBarGutter` properites

- src/app/layout/header/header.component.html
- src/app/layout/header/header.component.ts
- src/app/shared/components/code-box/code-box.component.html
- src/app/shared/components/main-menu/main-menu.component.html
- src/app/shared/components/main-menu/main-menu.component.ts
- src/app/styles/demo.less
- src/app/styles/hljs.less
- new actions in code
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix layout in mobile

- packages/abc/table/test/table-column-source.spec.ts
- packages/acl/docs/control.en-US.md
- packages/acl/docs/control.zh-CN.md
- packages/acl/docs/getting-started.en-US.md
- packages/acl/docs/getting-started.zh-CN.md
- packages/acl/src/acl.config.ts
- packages/acl/src/acl.service.spec.ts
- packages/acl/src/acl.service.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(acl): add `preCan` property in global config

- packages/form/src/sf.component.ts
- packages/theme/styles/app/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1012
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(sf): fix layout misplacement in inline mode

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.2.0
```
```
[ ] Yes
[x] No
```
> release(7.2.0): release 7.2.0

- packages/abc/table/demo/basic.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/style/index.less
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- packages/theme/styles/app/antd/variable.less
- close https://github.com/ng-alain/ng-alain/issues/1018
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `widthMode` property

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/sf.component.html
- packages/form/src/sf.component.ts
- packages/form/src/widgets/text/demo/simple.md
- src/app/routes/dev/demo/demo.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1017
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add loading property

- packages/abc/table/demo/expand.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1020
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `showExpand` property

- packages/form/src/widgets/time/demo/simple.md
- packages/form/src/widgets/time/time.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1022
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(form:time): fix format usage demo

- packages/theme/src/locale/languages/en-US.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(en-US locale): maint 404 error message in en-US locale

- packages/theme/src/locale/languages/en-US.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix typo

- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1025
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:select): fix i18n of notFoundContent

- packages/form/src/widgets/select/demo/simple.md
- packages/form/src/widgets/tag/demo/simple.md
- packages/form/src/widgets/transfer/demo/simple.md
- packages/form/src/widgets/tree-select/demo/simple.md
- packages/form/src/widgets/tree-select/tree-select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1024
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:*): fix can't render when async data

- packages/form/src/widgets/upload/demo/simple.md
- packages/form/src/widgets/upload/upload.widget.html
- packages/form/src/widgets/upload/upload.widget.spec.ts
- packages/form/src/widgets/upload/upload.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1028
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:upload): fix clean value when remove file list

- packages/form/src/widgets/date/date.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1029
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:date): fix throw error when not include end property

- package.json
- packages/acl/docs/control.en-US.md
- packages/acl/docs/control.zh-CN.md
- packages/acl/public_api.ts
- packages/acl/src/acl-if.directive.spec.ts
- packages/acl/src/acl-if.directive.ts
- packages/acl/src/acl.directive.ts
- packages/acl/src/acl.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1032
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(acl): add `*aclIf` structural directive

- packages/abc/table/test/table.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: add test
```
Issue Number: https://github.com/NG-ZORRO/ng-zorro-antd/issues/3225
```
[ ] Yes
[x] No
```
> test(abc:st): add http request tests

- packages/acl/docs/control.en-US.md
- packages/acl/docs/control.zh-CN.md
- packages/acl/ng-package.json
- packages/acl/package.json
- packages/acl/src/acl-if.directive.spec.ts
- packages/acl/src/acl-if.directive.ts
- packages/acl/src/acl.directive.ts
- packages/acl/src/acl.module.ts
- packages/acl/tsconfig.lib.json
- packages/form/src/validator.factory.ts
- scripts/ci/build-delon.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> chore: add aclIfThen, aclIfElse

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1037
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): support controlled `loading` property

- packages/theme/src/services/modal/modal.helper.ts
- packages/theme/src/services/modal/modal.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1045
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:modal): fix losing `nzWrapClassName` when has `size` exists

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/form.spec.ts
- packages/form/src/interface.ts
- packages/form/src/sf.component.html
- close https://github.com/ng-alain/ng-alain/issues/1049
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add icon in button proprety

- packages/theme/src/services/drawer/drawer.helper.ts
- packages/theme/src/services/drawer/drawer.spec.ts
- packages/theme/src/services/drawer/index.en-US.md
- packages/theme/src/services/drawer/index.zh-CN.md
- feat(theme:drawer): add `exact` property
- close https://github.com/ng-alain/ng-alain/issues/1046
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:drawer): fix deep merge object

- packages/abc/table/table.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1041
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix ingore load data when page size changed

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/theme/ng-package.json
- packages/util/ng-package.json
- src/app/core/code.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.3.0
```
```
[ ] Yes
[x] No
```
> release(7.3.0): release 7.3.0

- packages/schematics/application/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix `lint:style` invalid script

- packages/form/src/widgets/checkbox/checkbox.widget.ts
- packages/form/src/widgets/mention/mention.widget.ts
- packages/form/src/widgets/transfer/transfer.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1048
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:*): fix `ViewDestroyedError` error

- packages/theme/src/services/http/http.client.ts
- packages/theme/src/services/http/http.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1057
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:http): fix losing retrun a generic type in `get`

- CHANGELOG.md
- README.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish.js
- src/app/core/code.service.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.3.1
```
```
[ ] Yes
[x] No
```
> release(7.3.1): release 7.3.1

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.interfaces.ts
- close https://github.com/ng-alain/ng-alain/issues/1061
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): add `rawData` parameter of `res.process`

- packages/abc/edit/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:se): fix ingore label width when layout is inline

- packages/util/src/other/other.spec.ts
- packages/util/src/other/other.ts
- close https://github.com/ng-alain/ng-alain/issues/1063
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(util:deepMergeKey): fix override array when  ingoreArray is true

- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1064
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix auto hide dropdown in buttons

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.3.2
```
```
[ ] Yes
[x] No
```
> release(7.3.2): release 7.3.2

- .vscode/launch.json
- packages/schematics/ng-update/dom/dom.service.ts
- packages/schematics/ng-update/test-cases/v2-test-cases.spec.ts
- packages/schematics/ng-update/test-cases/v2/dom_expected_output.ts
- packages/schematics/ng-update/test-cases/v2/dom_input.ts
- close https://github.com/ng-alain/ng-alain/issues/1067
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix repeat variable suffix in `ng g ng-alain`

- packages/schematics/application/index.spec.ts
- packages/schematics/application/index.ts
- close https://github.com/ng-alain/ng-alain/issues/1073
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix invalid translate in ng add

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/test/table.spec.ts
- packages/theme/styles/app/antd/_table.less
- close https://github.com/ng-alain/ng-alain/issues/1078
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix responsive styles pollution `nz-table`

- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix ingore pi event trigger when change size in last page

- packages/acl/docs/getting-started.en-US.md
- packages/acl/docs/getting-started.zh-CN.md
- packages/acl/src/acl.service.spec.ts
- packages/acl/src/acl.service.ts
- packages/acl/src/acl.type.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(acl): add `except` property in `ACLType`

- packages/abc/table/table.component.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: fix reset invalid loading

- packages/abc/sidebar-nav/demo/basic.md
- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/theme/src/services/menu/index.en-US.md
- packages/theme/src/services/menu/index.zh-CN.md
- packages/theme/src/services/menu/interface.ts
- close https://github.com/ng-alain/ng-alain/issues/1087
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar): fix invalid iconfont icon

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-data-source.spec.ts
- src/app/routes/dev/demo/demo.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1088
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): ingore sort procees when `compare` is `null`

- packages/form/src/widgets/select/select.widget.ts
- src/app/routes/dev/demo/demo.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1089
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:select): fix invlaid tag count

- packages/form/docs/schema.en-US.md
- packages/form/docs/schema.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(schema): translate document of schema to English

- scripts/ci/build-schematics.sh
- close https://github.com/ng-alain/ng-alain/issues/1094
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> build: fix invalid ng-alain-sts version

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.4.0
```
```
[ ] Yes
[x] No
```
> release(7.4.0): release 7.4.0

- packages/abc/table/demo/expand.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1098
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `expandAccordion` property

- packages/abc/edit/edit.module.ts
- packages/abc/edit/style/index.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:se): fix losing opttional icon

- packages/abc/view/demo/fixed.md
- packages/abc/view/index.en-US.md
- packages/abc/view/index.zh-CN.md
- packages/abc/view/style/index.less
- packages/abc/view/view.component.html
- packages/abc/view/view.component.ts
- packages/abc/view/view.module.ts
- packages/abc/view/view.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sv): add `optional` `optionalHelp` properittes

- packages/form/src/model/form.property.ts
- packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1105
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix ingore trigger formChange event when call refreshSchema

- packages/form/src/widgets/autocomplete/autocomplete.widget.html
- close https://github.com/ng-alain/ng-alain/issues/1108
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:autocomplete): fix verify form in typing

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.5.0
```
```
[ ] Yes
[x] No
```
> release(7.5.0): release 7.5.0

- packages/abc/table/demo/buttons.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/style/index.less
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- `text` property support function
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix trigger area in sub buttons

- packages/schematics/application/index.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix lint in windows

- packages/form/src/widgets/date/date.widget.html
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/date/date.widget.ts
- packages/form/src/widgets/date/demo/simple.md
- packages/form/src/widgets/date/index.en-US.md
- packages/form/src/widgets/date/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1120
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form:date): add `year` in `mode` property

- _mock/user.ts
- packages/abc/table/demo/export.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/test/table-data-source.spec.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1102
- close https://github.com/ng-alain/delon/pull/584
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `filteredData` property in component

- packages/abc/table/demo/type.md
- packages/abc/table/demo/virtual.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/style/index.less
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add virtual scroll

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.6.0
```
```
[ ] Yes
[x] No
```
> release(7.6.0): release 7.6.0

- packages/form/src/widgets/radio/demo/simple.md
- packages/form/src/widgets/radio/index.en-US.md
- packages/form/src/widgets/radio/index.zh-CN.md
- packages/form/src/widgets/radio/radio.widget.html
- src/app/routes/dev/demo/demo.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1133
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:radio): fix losing `nzButtonStyle` property

- packages/form/src/widgets/select/index.md
- packages/form/src/widgets/select/select.widget.html
- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1131
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:select): fix losing `compareWith` property

- packages/form/spec/form.spec.ts
- packages/form/src/model/form.property.ts
- packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1132
- close https://github.com/ng-alain/ng-alain/issues/1135
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix invalid form values when call `refreshSchema` method

- packages/schematics/application/index.ts
- scripts/ci/build-schematics.sh
- close https://github.com/ng-alain/ng-alain/issues/1129
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix losing antd-theme-generator package

- packages/schematics/application/index.ts
- close https://github.com/ng-alain/ng-alain/issues/1130
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix invalid translating

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.6.1
```
```
[ ] Yes
[x] No
```
> release(7.6.1): release 7.6.1

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1134
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update exact

- packages/theme/src/services/drawer/drawer.helper.ts
- packages/theme/src/services/drawer/index.en-US.md
- packages/theme/src/services/drawer/index.zh-CN.md
- packages/theme/src/services/modal/index.en-US.md
- packages/theme/src/services/modal/index.zh-CN.md
- packages/theme/src/services/modal/modal.helper.ts
- close https://github.com/ng-alain/ng-alain/issues/1141
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:modal&drawer): removed automatic management of `z-index` values

- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1145
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:select): fix invlid render group in search mode

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1136
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add optional parameters of `resetColumns` method

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/sf.component.ts
- packages/form/src/widget.ts
- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1138
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add `disabled` property

- packages/abc/table/demo/buttons.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/style/index.less
- packages/abc/table/style/variable.less
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1142
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `iifBehavior` property

- docs/getting-started.zh-CN.md
- src/app/core/i18n/en-US.ts
- src/app/core/i18n/zh-CN.ts
- src/app/layout/header/header.component.html
- src/app/shared/components/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update qq group

- packages/abc/image/image.directive.ts
- packages/abc/image/image.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1153
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:_src): fix img causing infinite loop when error image still load fail

- packages/form/spec/form.spec.ts
- packages/form/src/widget.factory.ts
- close https://github.com/ng-alain/ng-alain/issues/1157
- close https://github.com/ng-alain/delon/pull/608
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add `widgets` property in `WidgetRegistry`

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.7.0
```
```
[ ] Yes
[x] No
```
> release(7.7.0): release 7.7.0

- packages/form/src/widgets/select/select.widget.spec.ts
- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1159
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:select): fix invalid value via click clean

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 7.7.1
```
```
[ ] Yes
[x] No
```
> release(7.7.1): release 7.7.1

- packages/abc/table/demo/data.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/style/index.less
- packages/abc/table/table-column-source.ts
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/table.module.ts
- packages/abc/table/test/table-column-source.spec.ts
- packages/abc/table/test/table-data-source.spec.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1160
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add keyword in filter

- .prettierrc
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.config.ts
- packages/abc/table/test/table-column-source.spec.ts
- packages/theme/src/locale/languages/el-GR.ts
- packages/theme/src/locale/languages/en-US.ts
- packages/theme/src/locale/languages/ko-KR.ts
- packages/theme/src/locale/languages/pl-PL.ts
- packages/theme/src/locale/languages/tr-TR.ts
- packages/theme/src/locale/languages/zh-CN.ts
- packages/theme/src/locale/languages/zh-TW.ts
- packages/theme/src/locale/locale.types.ts
- close https://github.com/ng-alain/ng-alain/issues/1167
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): `confirmText`, `clearText` support i18n text

- packages/util/src/other/other.spec.ts
- packages/util/src/other/other.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(util:deepMergeKey): support `null` & `undefined` of objects parament

- .prettierrc
- packages/form/docs/schema.en-US.md
- packages/form/docs/schema.zh-CN.md
- packages/form/spec/schema.spec.ts
- packages/form/src/schema/ui.ts
- packages/form/src/sf-item-wrap.component.html
- packages/form/src/sf-item-wrap.component.ts
- packages/form/src/sf.component.ts
- packages/form/src/widget.ts
- packages/form/src/widgets/array/array.widget.html
- packages/form/src/widgets/array/array.widget.ts
- packages/form/src/widgets/checkbox/checkbox.widget.html
- packages/form/src/widgets/checkbox/checkbox.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1173
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): `optionalHelp` support complex attributes

- packages/form/spec/base.spec.ts
- packages/form/src/model/object.property.ts
- packages/form/src/schema/ui.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.html
- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/form/src/widgets/boolean/boolean.widget.spec.ts
- packages/form/src/widgets/cascader/cascader.widget.spec.ts
- packages/form/src/widgets/cascader/cascader.widget.ts
- packages/form/src/widgets/checkbox/checkbox.widget.spec.ts
- packages/form/src/widgets/checkbox/checkbox.widget.ts
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/number/number.widget.spec.ts
- packages/form/src/widgets/radio/radio.widget.spec.ts
- packages/form/src/widgets/radio/radio.widget.ts
- packages/form/src/widgets/select/select.widget.spec.ts
- packages/form/src/widgets/select/select.widget.ts
- packages/form/src/widgets/string/string.widget.ts
- packages/form/src/widgets/tag/tag.widget.spec.ts
- packages/form/src/widgets/tag/tag.widget.ts
- packages/form/src/widgets/transfer/transfer.widget.spec.ts
- packages/form/src/widgets/transfer/transfer.widget.ts
- packages/form/src/widgets/tree-select/tree-select.widget.spec.ts
- packages/form/src/widgets/tree-select/tree-select.widget.ts
- packages/form/src/widgets/upload/index.md
- packages/form/src/widgets/upload/upload.widget.spec.ts
- packages/form/src/widgets/upload/upload.widget.ts
- src/app/delon.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1171
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:*): fix invalid render value when call `setValue` method

- packages/abc/down-file/down-file.directive.ts
- packages/abc/down-file/down-file.spec.ts
- packages/abc/down-file/index.en-US.md
- packages/abc/down-file/index.zh-CN.md
- packages/abc/down-file/style/index.less
- packages/abc/down-file/style/variable.less
- packages/abc/index.less
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:down-file): add `down-file_not-support` & `down-file__disabled`

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update changelog

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/const.ts
- packages/form/src/model/array.property.ts
- packages/form/src/model/form.property.factory.ts
- packages/form/src/model/form.property.ts
- packages/form/src/utils.ts
- packages/form/src/widgets/array/array.widget.html
- packages/form/src/widgets/array/array.widget.spec.ts
- packages/form/src/widgets/custom/sf-template.directive.ts
- src/app/core/i18n/service.ts
- close https://github.com/ng-alain/ng-alain/issues/1178
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:array): fix invalid value subscript of path value

- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- packages/abc/notice-icon/notice-icon.component.html
- packages/abc/notice-icon/notice-icon.spec.ts
- packages/abc/page-header/demo/standard.md
- packages/abc/table/demo/render.md
- packages/abc/table/style/index.less
- packages/abc/table/table.component.html
- packages/form/src/model/form.property.factory.ts
- packages/form/src/model/form.property.ts
- packages/form/src/schema/index.ts
- packages/schematics/application/files/src/app/app.module.ts
- packages/schematics/application/files/src/app/core/startup/startup.service.ts
- packages/schematics/application/files/src/app/layout/default/header/header.component.html
- packages/schematics/application/files/src/app/routes/dashboard/dashboard.component.html
- packages/schematics/application/files/src/app/routes/dashboard/dashboard.component.ts
- packages/schematics/application/files/src/app/routes/routes-routing.module.ts
- packages/schematics/application/index.ts
- packages/schematics/utils/json.ts
- packages/theme/styles/layout/default/widgets/_user.less
- scripts/ci/build-schematics.sh
- scripts/ci/build.sh
- src/app/core/i18n/zh-CN.ts
- src/app/routes/dev/layout.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update breaking change of ng-zorro

- packages/form/spec/base.spec.ts
- packages/form/src/widgets/array/array.widget.html
- packages/form/src/widgets/array/array.widget.spec.ts
- packages/form/src/widgets/array/array.widget.ts
- packages/theme/styles/app/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1192
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:array): fix disabled add & remove buttons when `readOnly` is `true`

- packages/form/src/widgets/upload/schema.ts
- packages/form/src/widgets/upload/upload.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1195
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:upload): fix invalid `showUploadList` property

- packages/abc/table/demo/render.md
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1194
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `emitReload` of `resetColumns` method

- packages/schematics/plugin/plugin.icon.spec.ts
- packages/schematics/plugin/plugin.icon.ts
- packages/theme/src/theme.module.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli:plugin:icon): fix unidentified `nzType` property

- packages/theme/styles/layout/default/widgets/_user.less
- close https://github.com/ng-alain/ng-alain/issues/1203
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:style): fix aside user style

- packages/abc/table/demo/buttons.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/package.json
- packages/abc/table/style/index.less
- packages/abc/table/table.component.html
- packages/abc/table/table.interfaces.ts
- packages/abc/table/table.module.ts
- packages/abc/table/test/table.spec.ts
- src/app/shared/index.ts
- close https://github.com/ng-alain/ng-alain/issues/1205
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `tooltip` property in button

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/upgrade-v8.en-US.md
- docs/upgrade-v8.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.0.0
```
```
[ ] Yes
[x] No
```
> release(8.0.0): release 8.0.0

- packages/abc/table/demo/sort.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table-export.ts
- packages/abc/table/table.interfaces.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `index` argument of `format`

- packages/form/src/sf-item-wrap.component.html
- packages/form/src/widgets/array/array.widget.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix missing style of widget item

- packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1228
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix losing inherit of `ui` property value

- packages/abc/table/table.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1218
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix losing default page config

- packages/abc/page-header/page-header.component.ts
- packages/abc/reuse-tab/reuse-tab.component.ts
- packages/abc/reuse-tab/reuse-tab.interfaces.ts
- packages/theme/src/services/menu/index.en-US.md
- packages/theme/src/services/menu/interface.ts
- close https://github.com/ng-alain/ng-alain/issues/1233
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:menu): fix can be choose one of `text` or `i18n`

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.1.0
```
```
[ ] Yes
[x] No
```
> release(8.1.0): release 8.1.0

- packages/auth/src/token/base.interceptor.spec.ts
- packages/auth/src/token/base.interceptor.ts
- packages/auth/src/token/helper.ts
- packages/auth/src/token/simple/simple.guard.ts
- close https://github.com/ng-alain/ng-alain/issues/1140
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(auth): fix `referrer.url` should be always latest router url

- packages/abc/edit/demo/complex.md
- packages/abc/edit/edit.component.html
- packages/abc/edit/edit.component.ts
- packages/abc/edit/edit.spec.ts
- packages/abc/edit/style/index.less
- packages/abc/view/demo/fixed.md
- packages/abc/view/style/index.less
- packages/abc/view/view-container.component.ts
- packages/abc/view/view.component.html
- packages/abc/view/view.component.ts
- packages/abc/view/view.spec.ts
- src/app/core/code.service.ts
- feat(abc:*): add ellipsis of long label text in `sv` and `se` components
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:*): fix `sv`, `se` title styles

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.2.0
```
```
[ ] Yes
[x] No
```
> release(8.2.0): release 8.2.0

- packages/abc/table/demo/basic.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/style/index.less
- packages/abc/table/style/variable.less
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `STColumnTitle` type of `title` property`

- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/test/table-data-source.spec.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1256
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix ignore catch error of http request when component is destroyed

- packages/theme/src/services/title/index.en-US.md
- packages/theme/src/services/title/index.zh-CN.md
- packages/theme/src/services/title/title.service.spec.ts
- packages/theme/src/services/title/title.service.ts
```
[x] Bugfix
[ ] Feature
```
Issue Number: https://github.com/ng-alain/ng-alain/issues/1261
```
[ ] Yes
[x] No
```
> fix(theme:title): should be avoid can't get title when rendered componet in `NavigationEnd` event

- packages/abc/reuse-tab/reuse-tab.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1259
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:reuse-tab): should be always get title from  menu data

- packages/form/ng-package.json
- packages/form/src/utils.ts
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/date/date.widget.ts
- packages/form/src/widgets/date/schema.ts
- packages/form/src/widgets/time/demo/simple.md
- packages/form/src/widgets/time/schema.ts
- packages/form/src/widgets/time/time.widget.html
- packages/form/src/widgets/time/time.widget.spec.ts
- packages/form/src/widgets/time/time.widget.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form:*): support date-fns format in `date`, `time` widgets

- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1271
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar): fix invalid subnode when include badge value in collapsed mode

- packages/acl/docs/guard.en-US.md
- packages/acl/docs/guard.zh-CN.md
- packages/acl/src/acl-guard.spec.ts
- packages/acl/src/acl-guard.ts
- close https://github.com/ng-alain/ng-alain/issues/1269
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(acl): support specify guard fail url in router data

- packages/abc/view/view.config.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sv): fix labelWidth type

- packages/abc/notice-icon/notice-icon.spec.ts
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: fix test
```
```
[ ] Yes
[x] No
```
> test(abc:notice-icon): fix test

- packages/cache/docs/getting-started.md
- packages/cache/src/cache.config.ts
- packages/cache/src/cache.service.ts
- packages/cache/src/cache.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1288
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cache): add `type`, `expire` in `DelonCacheConfig`

- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1304
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar-nav): fix invalid click children title in collapsed

- .travis.yml
- src/app/shared/components/code-box/code-box.component.html
- src/app/shared/components/code-box/code-box.component.ts
- src/app/styles/demo.less
- src/style-icons.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update document site

- packages/abc/table/demo/buttons.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-column-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/table.config.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table-column-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1279
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `pop` property

- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1291
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix ingored incomplete request when has new request

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.4.0
```
```
[ ] Yes
[x] No
```
> release(8.4.0): release 8.4.0

- angular.json
- package.json
- src/app/layout/header/header.component.ts
- src/app/styles/header.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add algolia docsearch

- src/app/shared/components/config-button/config-button.component.html
- src/app/shared/components/docs/docs.component.html
- src/app/styles/utils.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: update style

- packages/abc/table/demo/buttons.md
- packages/abc/table/table.component.html
- packages/abc/table/table.interfaces.ts
- close https://github.com/ng-alain/ng-alain/issues/1316
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `divider` type in button

- packages/form/src/widgets/cascader/cascader.widget.html
- packages/form/src/widgets/cascader/cascader.widget.spec.ts
- packages/form/src/widgets/cascader/cascader.widget.ts
- packages/form/src/widgets/cascader/index.md
- packages/form/src/widgets/cascader/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/1312
```
[x] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> fix(sf:cascader): removed `select` event, muse be use `selectionChange` instead

- packages/abc/sidebar-nav/sidebar-nav.component.html
- close https://github.com/ng-alain/ng-alain/issues/1330
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar-nav): fix repeat render item in external link

- packages/abc/table/table-export.ts
- packages/abc/table/test/table-export.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1334
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix render null value in export to excel

- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.html
- packages/abc/table/test/table-data-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1341
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix ingore invalid `tag` or `badge`

- package.json
- packages/abc/count-down/count-down.component.ts
- packages/abc/count-down/count-down.spec.ts
- packages/abc/count-down/demo/accuracy.md
- packages/abc/count-down/demo/simple.md
- packages/abc/count-down/index.md
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```
> build(abc:count-down): bump to 8.0.1

- packages/abc/reuse-tab/index.en-US.md
- packages/abc/reuse-tab/index.zh-CN.md
- packages/abc/reuse-tab/reuse-tab.component.html
- packages/abc/reuse-tab/reuse-tab.component.spec.ts
- packages/abc/reuse-tab/reuse-tab.component.ts
- packages/abc/reuse-tab/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1336
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:reuse-tab): add `tabMaxWidth` property

- packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/form/src/widgets/autocomplete/index.md
- packages/form/src/widgets/autocomplete/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/1332
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form:autocomplete): add `change` event

- packages/abc/table/demo/expand.md
- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1338
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): should be stop propagation in button event when `expandRowByClick` is `true`

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.5.0
```
```
[ ] Yes
[x] No
```
> release(8.5.0): release 8.5.0

- packages/abc/table/test/table.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> test(abc:st): fix test

- packages/abc/table/table-column-source.ts
- packages/abc/table/test/table-column-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1359
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): shoule be auto 100% width when not specified

- packages/abc/reuse-tab/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1365
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:reuse-tab): fix style in card type

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.5.1
```
```
[ ] Yes
[x] No
```
> release(8.5.1): release 8.5.1

- packages/schematics/application/index.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cli): add cnpm reminder

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/sf.component.ts
- packages/theme/styles/app/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1346
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add `noColon` property

- packages/abc/xlsx/xlsx.service.ts
- packages/abc/xlsx/xlsx.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1376
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:xlsx): fix duplicate loading xlsx.js when XLSX  exists

- packages/abc/reuse-tab/reuse-tab.component.html
- close https://github.com/ng-alain/ng-alain/issues/1379
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:reuse-tab): fix duplicate render list

- packages/form/src/widgets/checkbox/checkbox.widget.html
- close https://github.com/ng-alain/ng-alain/issues/1390
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:checkbox): fix losing `optionalHelp` property

- packages/abc/edit/edit.component.html
- packages/abc/edit/edit.component.ts
- packages/abc/edit/index.en-US.md
- packages/abc/edit/index.zh-CN.md
- packages/abc/edit/style/index.less
- packages/abc/edit/style/variable.less
- packages/abc/view/index.en-US.md
- packages/abc/view/index.zh-CN.md
- packages/abc/view/style/index.less
- packages/abc/view/style/variable.less
- packages/abc/view/view.component.html
- packages/abc/view/view.component.ts
fix(abc:sv, se): fix `optionalHelp` and `title` spacing is invalid
- close https://github.com/ng-alain/ng-alain/issues/1392
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sv,se): `optional`, `optionalHelp` support `TemplateRef<void>` type

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/table.interfaces.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1386
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:table): add `loaded` type event of `change`

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1387
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add `cleanValue` property

- packages/schematics/utils/alain.spec.ts
- packages/schematics/utils/alain.ts
```
[ ] Bugfix
[ ] Feature
```
- close https://github.com/ng-alain/ng-alain/issues/1319
- close https://github.com/ng-alain/ng-alain/issues/1314
```
[ ] Yes
[ ] No
```
> test(cli): add alain test

- package.json
- src/app/routes/dev/demo/demo.component.ts
- src/app/shared/components/docs/docs.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix typo style

- packages/form/src/widgets/array/array.widget.html
```
[x] Bugfix
[ ] Feature
```
Issue Number: 
- close https://github.com/ng-alain/ng-alain/issues/1400
```
[ ] Yes
[x] No
```
> fix(form:array): fix losing `optionalHelp` property

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.6.0
```
```
[ ] Yes
[x] No
```
> release(8.6.0): release 8.6.0

- packages/abc/table/demo/checkbox.md
- packages/abc/table/demo/export.md
- packages/abc/table/demo/fixed.md
- packages/abc/table/demo/form.md
- packages/abc/table/demo/radio.md
- packages/abc/table/demo/responsive.md
- packages/abc/table/demo/sort.md
- packages/abc/table/table.component.html
- close https://github.com/ng-alain/ng-alain/issues/1415
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix expand width value in strict mode

- packages/auth/docs/service.en-US.md
- packages/auth/docs/service.zh-CN.md
- packages/auth/src/token/interface.ts
- packages/auth/src/token/token.service.spec.ts
- packages/auth/src/token/token.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1404
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(auth): add `onlyToken` property in `clear` method

- packages/abc/edit/demo/reactive.md
- packages/abc/edit/edit.component.html
- packages/abc/edit/edit.component.ts
- packages/abc/edit/edit.spec.ts
- packages/abc/edit/index.en-US.md
- packages/abc/edit/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1414
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `error` supports multiple types

- packages/abc/sidebar-nav/index.en-US.md
- packages/abc/sidebar-nav/index.zh-CN.md
- packages/theme/src/services/menu/index.en-US.md
- packages/theme/src/services/menu/index.zh-CN.md
- packages/theme/src/services/menu/interface.ts
- packages/theme/src/services/menu/menu.service.spec.ts
- packages/theme/src/services/menu/menu.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1418
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(theme:MenuService): add `getItem`, `setItem` methods

- packages/abc/sidebar-nav/demo/basic.md
- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
- packages/theme/src/services/menu/index.en-US.md
- packages/theme/src/services/menu/index.zh-CN.md
- packages/theme/src/services/menu/interface.ts
- close #716
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sidebar-nav): support html in `text` or `i18n` property

- packages/auth/docs/getting-started.en-US.md
- packages/auth/docs/getting-started.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1420
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: add note of token value type

- packages/abc/table/demo/basic.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1097
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `setRow` method in component

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.7.0
```
```
[ ] Yes
[x] No
```
> release(8.7.0): release 8.7.0

- packages/abc/index.less
- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.types.ts
- packages/abc/sidebar-nav/style/index.less
- packages/abc/sidebar-nav/style/variable.less
- packages/theme/styles/layout/default/fix/index.less
- packages/theme/styles/layout/default/variable.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar-nav): fix style in disabled

- packages/abc/table/table.component.html
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1434
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix duplcate title when `responsive` is `false`

- packages/chart/water-wave/demo/basic.md
- packages/chart/water-wave/water-wave.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1433
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(chart:water-wave): fix first time unable to render

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.7.1
```
```
[ ] Yes
[x] No
```
> release(8.7.1): release 8.7.1

- Dockerfile.compile
- Dockerfile.package
- _nginx/default.conf
- daocloud.yml
- docs/faq.en-US.md
- docs/faq.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: update cn snapshot

- packages/abc/sidebar-nav/sidebar-nav.component.html
- close https://github.com/ng-alain/ng-alain/issues/1438
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar-nav): fix invalide tooltip render

- docs/architecture.en-US.md
- docs/architecture.zh-CN.md
- docs/faq.en-US.md
- docs/server.en-US.md
- docs/server.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1441
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix invalid router path

- packages/acl/src/acl-guard.ts
- packages/acl/src/acl.config.ts
- packages/acl/src/acl.service.ts
- packages/auth/docs/set.en-US.md
- packages/auth/src/store/local-storage.service.ts
- packages/auth/src/store/memory.service.ts
- packages/auth/src/store/session-storage.service.ts
- packages/auth/src/token/jwt/jwt.guard.ts
- packages/auth/src/token/jwt/jwt.interceptor.ts
- packages/auth/src/token/simple/simple.guard.ts
- packages/auth/src/token/simple/simple.interceptor.ts
- packages/auth/src/token/token.service.ts
- packages/theme/src/services/menu/menu.service.ts
- packages/util/src/lazy/lazy.service.ts
- packages/util/src/other/check.ts
- packages/util/src/other/index.en-US.md
- packages/util/src/other/index.zh-CN.md
- packages/util/src/other/other.ts
- close https://github.com/ng-alain/ng-alain/issues/1430
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: optimize code documentation

- packages/abc/edit/demo/basic.md
- packages/abc/edit/edit.component.html
- packages/abc/edit/style/index.less
- packages/abc/view/style/index.less
- packages/abc/view/view.component.html
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sv,se): fix spacing between option and Icon

- CHANGELOG.md
- daocloud.yml
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.7.2
```
```
[ ] Yes
[x] No
```
> release(8.7.2): release 8.7.2

- packages/abc/edit/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1448
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:se): fix misplaced labels on small screens

- packages/theme/src/services/http/http.decorator.spec.ts
- packages/theme/src/services/http/http.decorator.ts
- close https://github.com/ng-alain/ng-alain/issues/1450
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:http.decorator): fix unable to send array response body

- packages/form/spec/schema.spec.ts
- packages/form/src/sf.component.ts
- close #745
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix shoule be inherit ui properites of array property

- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar-nav): fix can't click text in collapsed mode

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.7.3
```
```
[ ] Yes
[x] No
```
> release(8.7.3): release 8.7.3

- packages/schematics/plugin/plugin.icon.ts
- close https://github.com/ng-alain/ng-alain/issues/1457
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli:plugin:icon): fix multi-project pollution

- packages/abc/table/table.component.html
- close https://github.com/ng-alain/ng-alain/issues/1454
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix filter misalignment

- packages/abc/abc.module.ts
- packages/abc/index.less
- packages/abc/loading/demo/basic.md
- packages/abc/loading/demo/custom.md
- packages/abc/loading/demo/delay.md
- packages/abc/loading/index.en-US.md
- packages/abc/loading/index.ts
- packages/abc/loading/index.zh-CN.md
- packages/abc/loading/loading.component.html
- packages/abc/loading/loading.component.ts
- packages/abc/loading/loading.config.ts
- packages/abc/loading/loading.interfaces.ts
- packages/abc/loading/loading.module.ts
- packages/abc/loading/loading.service.ts
- packages/abc/loading/loading.spec.ts
- packages/abc/loading/package.json
- packages/abc/loading/public_api.ts
- packages/abc/loading/style/index.less
- packages/abc/loading/style/variable.less
- packages/abc/public_api.ts
- close https://github.com/ng-alain/ng-alain/issues/1458
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:loading): add global loading indicator

- src/app/layout/header/header.component.html
- src/app/shared/components/config-button/config-button.component.html
- src/app/shared/components/config-button/config-button.component.ts
- src/app/shared/components/docs/docs.component.html
- src/app/styles/common.less
- src/app/styles/demo.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> chore: update site

- packages/abc/down-file/down-file.directive.ts
- packages/abc/down-file/down-file.spec.ts
- packages/abc/down-file/index.en-US.md
- packages/abc/down-file/index.zh-CN.md
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:down-file): support custom file name

- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar-nav): fix keeping expand when `openStrictly` is `true`

- packages/abc/date-picker/date-picker.config.ts
- packages/abc/date-picker/index.en-US.md
- packages/abc/date-picker/index.zh-CN.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(abc:date-picker): update

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.8.0
```
```
[ ] Yes
[x] No
```
> release(8.8.0): release 8.8.0

- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.interfaces.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix lose `dblClick` in `STChange`

- packages/abc/table/table-data-source.ts
- packages/abc/table/test/table-data-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1471
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix invalid default value of `date` type

- packages/schematics/plugin/schema.json
- packages/schematics/tpl/schema.json
Muse wait for merge https://github.com/angular/angular-cli/pull/16512
- close https://github.com/ng-alain/ng-alain/issues/1466
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix unknown options

- packages/abc/down-file/down-file.directive.ts
- packages/abc/down-file/down-file.spec.ts
- packages/abc/down-file/index.en-US.md
- packages/abc/down-file/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1272
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:down-file): add `http-body` property

- packages/abc/table/demo/statistical.md
- packages/abc/table/index.en-US.md
- packages/abc/table/index.zh-CN.md
- packages/abc/table/table.component.ts
- packages/abc/table/test/table.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1481
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `count`, `list` properites of component

- .travis.yml
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> chore: fix travis

- packages/form/src/model/form.property.factory.ts
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/date/date.widget.ts
- packages/form/src/widgets/time/time.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1488
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:date): fix can't custom end format

- packages/theme/styles/layout/default/fix/_sidebar-nav.less
- close https://github.com/ng-alain/ng-alain/issues/1487
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:sidebar): fix badge overflow

- packages/form/spec/base.spec.ts
- packages/form/src/model/array.property.ts
- packages/form/src/model/form.property.ts
- close https://github.com/ng-alain/ng-alain/issues/1472
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:array): fix invalid error when removed item

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish-scaffold.js
- scripts/publish/publish.js
- scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.9.0
```
```
[ ] Yes
[x] No
```
> release(8.9.0): release 8.9.0

- packages/form/src/widgets/date/date.widget.ts
sf的date小部件的两个问题:
1.选择时间范围后,第二个值与第一个值的格式不匹配.
2.清除了选择的时间范围后,返回值成了["Invalid Date","Invalid Date"]
```
[x] Bugfix
[ ] Feature
```
Issue Number: 1535
```
[ ] Yes
[x] No
```
> fix(form:date): fix invalid date value when mode is range

- docs/deploy.en-US.md
- changed wording for better understanding
- updated instructions for location strategies
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: updated language

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/form/src/widgets/upload/index.md
- scripts/publish/publish.js
- scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.9.1
```
```
[ ] Yes
[x] No
```
> release(8.9.1): release 8.9.1

- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
[x] CI related changes
```
```
[ ] Yes
[x] No
```
> test: fix cli

- packages/abc/page-header/package.json
- packages/abc/page-header/page-header.component.html
- packages/abc/page-header/page-header.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1526
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:page-header): fix missing import of `@angular/cdk/observers`

- packages/theme/src/services/http/http.client.ts
- packages/theme/src/services/http/http.decorator.spec.ts
- packages/theme/src/services/http/http.decorator.ts
- packages/theme/src/services/http/http.spec.ts
- packages/theme/src/services/http/index.en-US.md
- packages/theme/src/services/http/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1525
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(theme:http): add `form` method

- packages/form/src/widgets/string/demo/simple.md
- packages/form/src/widgets/string/index.en-US.md
- packages/form/src/widgets/string/index.zh-CN.md
- packages/form/src/widgets/string/schema.ts
- packages/form/src/widgets/string/string.widget.html
- packages/form/src/widgets/string/string.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1539
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form:string): add `change`, `focus`, `blur`, `enter` event

- packages/abc/table/table-data-source.ts
- packages/abc/table/table.component.html
- packages/theme/src/pipes/yn/yn.pipe.ts
- close https://github.com/ng-alain/ng-alain/issues/1549
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix unabled to render `yn` type

- packages/form/docs/qa.md
- packages/form/src/widgets/select/demo/simple.md
- close https://github.com/ng-alain/ng-alain/issues/1528
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs(form): typing qa

- packages/theme/src/services/menu/index.en-US.md
- packages/theme/src/services/menu/index.zh-CN.md
- close https://github.com/ng-alain/ng-alain/issues/1497
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: typo

- packages/theme/src/services/title/title.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:title): fix can't set comment node as title

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- scripts/publish/publish.sh
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 8.9.2
```
```
[ ] Yes
[x] No
```
> release(8.9.2): release 8.9.2

- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st.component.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1509
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add enforce control to top via `reset`, `load` methods

- packages/abc/sidebar-nav/demo/basic.md
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1496
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sidebar-nav): can be set 3 levels icon

- packages/abc/se/demo/basic.md
- packages/abc/se/index.en-US.md
- packages/abc/se/index.zh-CN.md
- packages/abc/se/se.component.html
- packages/abc/se/se.component.ts
- packages/abc/se/se.spec.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:se): add `TemplateRef<void>` in `label`, `error`, `extra` properties

- docs/upgrade-v9.zh-CN.md
- packages/abc/notice-icon/demo/popover.md
- packages/abc/st/test/st-data-source.spec.ts
- packages/abc/st/test/st.spec.ts
- packages/theme/ng-package.json
- packages/theme/src/pipes/date/date.pipe.spec.ts
- packages/theme/src/pipes/date/date.pipe.ts
- packages/theme/src/theme.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: using date-fns

- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- packages/abc/st/test/st.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(abc:st): remove invalid property

- packages/form/src/validator.factory.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form:validator):fix abstract createValidator fn definition

- docs/upgrade-v9.en-us.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: translate upgrade-v9.en-us.md

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/upgrade-v9.en-us.md
- package.json
- packages/abc/README.md
- packages/acl/README.md
- packages/auth/README.md
- packages/cache/README.md
- packages/chart/README.md
- packages/form/README.md
- packages/mock/README.md
- packages/schematics/README.md
- packages/testing/README.md
- packages/theme/README.md
- packages/util/README.md
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 9.0.0-rc.1
```
```
[ ] Yes
[x] No
```
> release(9.0.0-rc.1): release 9.0.0-rc.1

- packages/abc/loading/loading.module.ts
- packages/abc/reuse-tab/reuse-tab.module.ts
- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st.interfaces.ts
- packages/form/docs/customize.en-US.md
- packages/form/docs/customize.zh-CN.md
- packages/form/src/module.ts
- packages/schematics/application/files/src/app/layout/layout.module.ts
- packages/schematics/application/files/src/app/routes/routes.module.ts
- packages/schematics/application/files/src/app/shared/json-schema/json-schema.module.ts
- packages/schematics/docs/generate.zh-CN.md
- packages/schematics/module/files/__name@dasherize@if-flat__/__name@dasherize__.module.ts
- packages/theme/docs/icon.md
- packages/theme/src/services/drawer/drawer.spec.ts
- packages/theme/src/services/modal/modal.spec.ts
- src/app/shared/json-schema/json-schema.module.ts
- src/app/shared/shared.module.ts
- src/templates/examples.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: remove entryComponents

- packages/theme/src/services/http/http.decorator.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: fix DI compatible lvy

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 9.0.0-rc.2
```
```
[ ] Yes
[x] No
```
> release(9.0.0-rc.2): release 9.0.0-rc.2

- packages/mock/docs/getting-started.en-US.md
- packages/mock/docs/getting-started.zh-CN.md
- packages/mock/src/mock.config.ts
- packages/mock/src/mock.interceptor.spec.ts
- packages/mock/src/mock.interceptor.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(mock): add `copy` property

- packages/chart/tag-cloud/tag-cloud.component.ts
- packages/chart/timeline/timeline.component.ts
- packages/util/src/logger/logger.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> perf: performance depreation

- packages/schematics/application/index.ts
- close https://github.com/ng-alain/ng-alain/issues/1577
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): fix Invalid "extends" configuration value

- packages/abc/st/st-row.directive.ts
- packages/form/src/sf-fixed.directive.ts
- close https://github.com/ng-alain/ng-alain/issues/1575
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix width is not aligned in fixed label width

- packages/abc/st/demo/widget.md
- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/public_api.ts
- packages/abc/st/st-column-source.ts
- packages/abc/st/st-widget-host.directive.ts
- packages/abc/st/st-widget.ts
- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/st.module.ts
- packages/abc/st/test/st-column-source.spec.ts
- packages/abc/st/test/st.spec.ts
- src/app/app.module.ts
- src/app/shared/st-widget/img.widget.ts
- src/app/shared/st-widget/st-widget.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1449
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:st): add `widget` type

- packages/schematics/application/files/src/app/app.module.ts
- packages/schematics/application/files/src/app/core/startup/startup.service.ts
- packages/schematics/application/files/src/app/layout/layout.module.ts
- scripts/ci/build-schematics.sh
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): add `widget` of `st`

- packages/form/src/model/array.property.ts
- close https://github.com/ng-alain/ng-alain/issues/1561
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix update value and validity when removing the last item

- packages/form/src/model/form.property.factory.ts
- packages/form/src/sf.component.ts
- packages/form/src/widgets/date/date.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1578
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form:widget:date): fix invalid end date when clean date

- packages/form/src/model/form.property.factory.ts
- packages/form/src/sf.component.ts
- packages/form/src/widgets/date/date.widget.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form:widget:date): fix Invalid Date when clean date

- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/date/date.widget.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form:widget:date): fix format default value

- .travis.yml
- CHANGELOG.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(8.9.3): release 8.9.3

- CHANGELOG.md
- README.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/abc/README.md
- packages/acl/README.md
- packages/auth/README.md
- packages/cache/README.md
- packages/chart/README.md
- packages/form/README.md
- packages/mock/README.md
- packages/schematics/README.md
- packages/theme/README.md
- packages/util/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.0.0-rc.3): release 9.0.0-rc.3

- angular.json
- packages/schematics/application/index.ts
- packages/schematics/curd/schema.json
- packages/schematics/edit/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/edit/schema.json
- packages/schematics/empty/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/empty/schema.json
- packages/schematics/list/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/list/schema.json
- packages/schematics/plugin/files/sts/swagger-edit/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/plugin/files/sts/swagger-list/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/tpl/schema.json
- packages/schematics/view/files/__path__/__name@dasherize@if-flat__/__name@dasherize__.component.ts
- packages/schematics/view/schema.json
- close https://github.com/ng-alain/ng-alain/issues/1583
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli): use `style` instead of `styleext`

- packages/abc/se/demo/basic.md
- packages/abc/se/demo/complex.md
- packages/abc/se/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1584
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:se): fix `se-title` misalignment

- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1589
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix invalid expand

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
[x] Other... Please describe: release 9.0.0-rc.4
```
```
[ ] Yes
[ ] No
```
> release(9.0.0-rc.4): release 9.0.0-rc.4

- packages/schematics/migration.json
- packages/schematics/ng-update/index.ts
- packages/schematics/ng-update/target-version.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> feat(cli): add `ng update ng-alain`

- docs/upgrade-v9.en-us.md
- docs/upgrade-v9.zh-CN.md
- packages/abc/st/st.component.ts
- packages/chart/timeline/timeline.component.ts
- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/src/config.ts
- packages/form/src/widgets/date/date.widget.spec.ts
- packages/form/src/widgets/date/index.en-US.md
- packages/form/src/widgets/date/index.zh-CN.md
- packages/form/src/widgets/date/schema.ts
- packages/form/src/widgets/time/index.en-US.md
- packages/form/src/widgets/time/index.zh-CN.md
- packages/form/src/widgets/time/schema.ts
- packages/form/src/widgets/time/time.widget.spec.ts
- packages/theme/src/pipes/date/date.pipe.spec.ts
- packages/theme/src/pipes/date/date.pipe.ts
- packages/util/src/config/sf/sf.type.ts
- packages/util/src/time/time.ts
- close https://github.com/ng-alain/ng-alain/issues/1595
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: fix invalid date via date-fns

- docs/upgrade-v9.en-us.md
- docs/upgrade-v9.zh-CN.md
- packages/schematics/ng-update/index.ts
- packages/schematics/ng-update/upgrade-rules/v9/files-tpl/lintstagedrc.ts
- packages/schematics/ng-update/upgrade-rules/v9/files-tpl/st-widget.module.ts
- packages/schematics/ng-update/upgrade-rules/v9/v9Rule.spec.ts
- packages/schematics/ng-update/upgrade-rules/v9/v9Rule.ts
- packages/schematics/utils/file.ts
- packages/schematics/utils/project.ts
- packages/schematics/utils/testing.ts
- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): fix `ng-update`

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- docs/global-config.en-US.md
- docs/global-config.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.0.0): release 9.0.0

- .github/workflows/deploy-site.yml
- packages/form/src/module.ts
- src/app/core/code/code.service.ts
- src/app/core/code/files/angular.json.ts
- src/app/core/code/files/app.module.ts
- src/app/core/code/files/global-config.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix stackblitz

- packages/schematics/ng-update/upgrade-rules/v9/v9Rule.spec.ts
- packages/schematics/ng-update/upgrade-rules/v9/v9Rule.ts
- packages/schematics/utils/json.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): should be remove g2 in `ng update`

- docs/ie11.en-US.md
- docs/ie11.zh-CN.md
- packages/schematics/docs/plugin.en-US.md
- packages/schematics/docs/plugin.zh-CN.md
- packages/schematics/plugin/files/ie/tsconfig-es5.app.ts
- packages/schematics/plugin/files/ie/tsconfig-es5.spec.ts
- packages/schematics/plugin/index.ts
- packages/schematics/plugin/plugin.ie.spec.ts
- packages/schematics/plugin/plugin.ie.ts
- packages/schematics/utils/file.ts
- close https://github.com/ng-alain/ng-alain/issues/1517
- close https://github.com/ng-alain/ng-alain/issues/1232
- close https://github.com/ng-alain/ng-alain/issues/1580
- close https://github.com/ng-alain/ng-alain/pull/1603
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(cli:plugin:ie): add `ie` plugin

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.0.1): release 9.0.1

- packages/theme/styles/layout/default/_header.less
- close https://github.com/ng-alain/ng-alain/issues/1605
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:default): fix search icon misplacement

- packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1607
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix unable to display loading when call `load`

- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- packages/abc/st/style/index.less
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1608
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix style misplacement when expand is true

- packages/cache/src/cache.spec.ts
- packages/form/src/widgets/select/select.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1613
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix: remove console.log

- docs/upgrade-v9.en-us.md
- docs/upgrade-v9.zh-CN.md
- packages/theme/docs/icon.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> docs: fix icon.md,upgrade-v9.md

- packages/abc/reuse-tab/index.en-US.md
- packages/abc/reuse-tab/index.zh-CN.md
- packages/abc/reuse-tab/reuse-tab-context-menu.component.html
- packages/abc/reuse-tab/reuse-tab.component.html
- packages/abc/reuse-tab/reuse-tab.component.spec.ts
- packages/abc/reuse-tab/reuse-tab.component.ts
- packages/abc/reuse-tab/reuse-tab.interfaces.ts
- packages/abc/reuse-tab/reuse-tab.service.ts
- packages/schematics/application/files/src/app/shared/shared-delon.module.ts
- packages/theme/src/locale/languages/el-GR.ts
- packages/theme/src/locale/languages/en-US.ts
- packages/theme/src/locale/languages/hr-HR.ts
- packages/theme/src/locale/languages/ja-JP.ts
- packages/theme/src/locale/languages/ko-KR.ts
- packages/theme/src/locale/languages/pl-PL.ts
- packages/theme/src/locale/languages/tr-TR.ts
- packages/theme/src/locale/languages/zh-CN.ts
- packages/theme/src/locale/languages/zh-TW.ts
- packages/theme/src/locale/locale.types.ts
- src/app/global-config.module.ts
- src/app/routes/dev/layout.component.ts
- src/app/routes/dev/pages/page.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1590
- close https://github.com/ng-alain/ng-alain/issues/1601
- close https://github.com/ng-alain/ng-alain/issues/1311
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor(abc:reuse-tab): refactor reuse tab

- packages/form/src/config.ts
- packages/form/src/model/form.property.factory.ts
- packages/form/src/sf.component.ts
- packages/form/src/utils.ts
- packages/util/src/config/sf/sf.type.ts
- close https://github.com/ng-alain/ng-alain/issues/1615
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(form): fix default date-time format is invalid iso8601 value

- packages/theme/src/pipes/yn/yn.pipe.spec.ts
- packages/theme/src/pipes/yn/yn.pipe.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:yn): fix unable to select parameters

- packages/form/src/widget.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1611
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(sf:widget:autocomplete): fix widget using `ngAfterViewInit` event will be overwrite

- packages/form/src/widgets/cascader/cascader.widget.html
- packages/form/src/widgets/cascader/index.md
- packages/form/src/widgets/cascader/schema.ts
- packages/form/src/widgets/rate/index.en-US.md
- packages/form/src/widgets/rate/index.zh-CN.md
- packages/form/src/widgets/rate/rate.widget.html
- packages/form/src/widgets/rate/schema.ts
- packages/form/src/widgets/select/index.md
- packages/form/src/widgets/select/schema.ts
- packages/form/src/widgets/select/select.widget.html
- packages/form/src/widgets/select/select.widget.ts
- packages/form/src/widgets/tree-select/index.md
- packages/form/src/widgets/tree-select/schema.ts
- packages/form/src/widgets/tree-select/tree-select.widget.html
- packages/form/src/widgets/upload/index.md
- packages/form/src/widgets/upload/schema.ts
- packages/form/src/widgets/upload/upload.widget.html
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): sync property of ng-zorro components

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.1.0): release 9.1.0

- packages/theme/src/services/drawer/drawer.helper.ts
- packages/theme/src/services/drawer/drawer.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(theme:drawer): fix bottom margin spacing

- packages/abc/st/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1619
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix missing border when custom body of nest table

- packages/abc/st/st.component.ts
- packages/karma.conf.js
- packages/schematics/application/files/src/app/layout/layout.module.ts
- close https://github.com/ng-alain/ng-alain/issues/1620
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli:ng-add): fix lose component import

- packages/util/src/lazy/lazy.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(util:lazy): add `loading` status when load is non-complete

- packages/auth/docs/set.en-US.md
- packages/auth/docs/set.zh-CN.md
- packages/auth/public_api.ts
- packages/auth/src/store/cookie-storage.service.spec.ts
- packages/auth/src/store/cookie-storage.service.ts
- close #718
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(auth): add cookie storage

- packages/form/src/widgets/object/demo/card.md
- packages/form/src/widgets/object/index.en-US.md
- packages/form/src/widgets/object/index.zh-CN.md
- packages/form/src/widgets/object/object.widget.html
- packages/form/src/widgets/object/object.widget.spec.ts
- packages/form/src/widgets/object/object.widget.ts
- packages/form/src/widgets/object/schema.ts
- packages/theme/styles/app/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1552
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(sf:widget:object): add card style

- packages/auth/src/store/cookie-storage.service.ts
- packages/auth/src/store/local-storage.service.ts
- packages/auth/src/store/memory.service.ts
- packages/auth/src/store/session-storage.service.ts
- packages/auth/src/token/jwt/jwt.guard.ts
- packages/auth/src/token/jwt/jwt.interceptor.ts
- packages/auth/src/token/jwt/jwt.model.ts
- packages/auth/src/token/simple/simple.guard.ts
- packages/auth/src/token/simple/simple.interceptor.ts
- packages/auth/src/token/token.service.ts
- packages/form/src/sf.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1460
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: update code docs

- packages/abc/page-header/page-header.component.ts
…e params
- close https://github.com/ng-alain/ng-alain/issues/1627
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:page-header): fix can't generate breadcrumb when route include params

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.2.0): release 9.2.0

- packages/abc/page-header/page-header.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:page-header): remove debug info

- package.json
- packages/abc/st/demo/type.md
- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st-column-source.ts
- packages/abc/st/st-data-source.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/test/st-data-source.spec.ts
- packages/karma.conf.js
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(abc:st): add `enum` type

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.2.1): release 9.2.1

- packages/abc/lodop/lodop.types.ts
- close https://github.com/ng-alain/ng-alain/issues/1637
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:lodop): fix lodop definition

- package.json
- packages/abc/se/se-container.component.html
- packages/abc/se/se-container.component.ts
- packages/abc/se/se.spec.ts
- packages/abc/se/style/index.less
- packages/abc/st/st.component.ts
- packages/form/src/widgets/autocomplete/autocomplete.widget.ts
- packages/theme/styles/app/ng/_preserve-white-spaces.less
- packages/theme/styles/app/utils/_display.less
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(theme:style:utils): fix `flex-center-between`

- packages/schematics/plugin/plugin.ie.ts
- close https://github.com/ng-alain/ng-alain/issues/1639
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli:plugin:ie): fix invalid version number of dependencies

- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- fix(abc:st): fix click the filter icon to trigger sorting
- close https://github.com/ng-alain/ng-alain/issues/1638
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix invalid highlight when filter has set

- packages/form/src/widgets/date/date.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1640
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(sf:widget:date): fix format default value when value is not null

- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- packages/abc/st/style/index.less
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1633
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix invalid fixed column

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.2.2): release 9.2.2

- packages/form/spec/form.spec.ts
- packages/form/spec/schema.spec.ts
- packages/form/src/sf-fixed.directive.ts
- packages/form/src/sf.component.ts
- packages/theme/styles/app/antd/_form.less
- packages/theme/styles/app/delon/_sf.less
- packages/theme/styles/app/widgets/_form.less
- close https://github.com/ng-alain/ng-alain/issues/1647
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form): fix misalignment in fixed label

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.2.3): release 9.2.3

- packages/abc/st/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1636
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix invalid link break in strict mode

- packages/schematics/application/files/src/app/core/startup/startup.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(cli:ng-add): fix invalid parameter in catchError

- packages/schematics/plugin/plugin.ie.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli:plugin:ie): fix modifiy invalid file

- packages/abc/lodop/lodop.service.ts
- packages/abc/lodop/lodop.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1650
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:lodop): fix unable to attach `LODOP.NEWPAGE();` this kind of code

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.2.4): release 9.2.4

- packages/theme/styles/app/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1655
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form): fix button & form misalignment in inline mode

- packages/theme/src/services/menu/menu.service.spec.ts
- packages/theme/src/services/menu/menu.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1657
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(theme:menu.service): fix invald recursive hit when is hash location strategy

- packages/form/src/widgets/array/array.widget.spec.ts
- packages/form/src/widgets/array/array.widget.ts
- packages/form/src/widgets/array/index.md
- packages/form/src/widgets/array/schema.ts
- close https://github.com/ng-alain/ng-alain/issues/1658
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form:widget:array): add callback evetns

- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st-column-source.ts
- packages/abc/st/st.component.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/test/st.spec.ts
- fix(abc:st): fix default is always multiple sort
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(abc:st): auto generate compose method when `sort: true`

- packages/abc/st/st-data-source.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/test/st-data-source.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix not specifying key should use index instead in statistical

- packages/abc/media/media.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1662
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:media): fix can't init when Plyr has beed load

- packages/abc/sidebar-nav/index.en-US.md
- packages/abc/sidebar-nav/index.zh-CN.md
- packages/abc/sidebar-nav/sidebar-nav.component.html
- packages/abc/sidebar-nav/sidebar-nav.component.ts
- packages/abc/sidebar-nav/sidebar-nav.types.ts
- packages/theme/src/services/menu/interface.ts
- packages/theme/src/services/menu/menu.service.spec.ts
- packages/theme/src/services/menu/menu.service.ts
- packages/theme/styles/layout/default/fix/_sidebar-nav.less
- packages/theme/styles/layout/default/variable.less
- close https://github.com/ng-alain/ng-alain/issues/1660
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:sidebar-nav): unlimited levels

- package.json
- packages/chart/bar/bar.component.ts
- packages/chart/custom/custom.component.ts
- packages/chart/gauge/gauge.component.ts
- packages/chart/mini-area/mini-area.component.ts
- packages/chart/mini-bar/mini-bar.component.ts
- packages/chart/package.json
- packages/chart/pie/pie.component.ts
- packages/chart/radar/radar.component.ts
- packages/chart/single-bar/single-bar.component.ts
- packages/chart/tag-cloud/tag-cloud.component.ts
- packages/chart/timeline/timeline.component.ts
- packages/form/src/widgets/date/schema.ts
- packages/util/src/config/abc/date-picker.type.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix: fix entry point warning

- docs/upgrade-v9.en-US.md
- close https://github.com/ng-alain/ng-alain/issues/1667
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix file name case

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/src/sf.component.ts
- packages/form/src/widgets/array/array.widget.html
- packages/form/src/widgets/array/array.widget.spec.ts
- packages/theme/system/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1665
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(form): add `compact` property

- packages/chart/water-wave/index.md
- packages/chart/water-wave/water-wave.component.ts
- packages/chart/water-wave/water-wave.spec.ts
- packages/testing/src/g2.ts
- close https://github.com/ng-alain/ng-alain/issues/1666
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(chart:water-wave): add `animate` property

- packages/schematics/application/index.ts
- scripts/ci/build-schematics.sh
- https://github.com/mzohaibqc/antd-theme-generator/issues/43
- https://github.com/ng-alain/ng-alain/issues/1664
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> build: lock antd-theme-generator to 1.2.2

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/schematics/application/files/src/app/layout/default/default.component.html
- scripts/build/fix-zorro-path.js
- scripts/ci/build-schematics.sh
- src/app/core/app.service.ts
- src/app/core/code/code.service.ts
- src/app/core/code/files/angular.json.ts
- src/app/core/code/files/dot_angular-cli.json.ts
- src/app/shared/components/theme-btn/theme-btn.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.3.0): release 9.3.0

- .github/workflows/deploy-site.yml
- src/app/core/i18n/en-US.ts
- src/app/core/i18n/zh-CN.ts
- src/app/layout/header/header.component.ts
- src/app/routes/404/404.component.html
- src/app/routes/dev/layout.component.html
- src/app/routes/home/home.component.html
- src/app/shared/components/footer/footer.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add cn mirror

- packages/abc/reuse-tab/style/index.less
- close https://github.com/ng-alain/ng-alain/issues/1671
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:reuse-tab): fix dark style of close button

- packages/abc/sidebar-nav/sidebar-nav.component.html
- close https://github.com/ng-alain/ng-alain/issues/1672
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:sidebar-nav): add title of menu item

- packages/abc/reuse-tab/reuse-tab.component.ts
- packages/abc/reuse-tab/reuse-tab.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1673
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:reuse-tab): fix exclude items should be updated after leave

- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- packages/theme/layout/fullscreen/theme-compact.less
- packages/theme/layout/fullscreen/theme-dark.less
- src/app/core/code/code.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(theme:layout:fullscreen): fix dark theme

- packages/abc/se/se.component.html
- packages/abc/se/se.component.ts
- packages/abc/se/se.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1678
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:se): fix only control vision when error is null

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.3.1): release 9.3.1

- packages/schematics/ng-update/upgrade-rules/v9/files-tpl/global-config.module.ts
- packages/schematics/ng-update/upgrade-rules/v9/v9Rule.ts
- close https://github.com/ng-alain/ng-alain/issues/1623
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): fix ng-update

- packages/abc/page-header/page-header.component.ts
- packages/abc/page-header/page-header.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1687
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:page-header): fix route event cannot be destroyed in reuse router

- packages/theme/system/delon/_sf.less
- packages/theme/system/theme-dark.less
- packages/theme/system/theme-default.less
- close #939
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form): fix optional color of dark theme

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.3.2): release 9.3.2

- packages/abc/se/demo/reset-errors.md
- packages/abc/se/index.en-US.md
- packages/abc/se/index.zh-CN.md
- packages/abc/se/public_api.ts
- packages/abc/se/se-container.component.ts
- packages/abc/se/se.component.ts
- packages/abc/se/se.spec.ts
- packages/abc/se/se.types.ts
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(abc:se): add `errors` property

- packages/abc/st/st.component.ts
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1691
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix recalculate no value of removeRows method

- .vscode/settings.json
- packages/theme/system/antd/_card.less
- packages/theme/system/antd/_drawer.less
- packages/theme/system/antd/_modal.less
- packages/theme/system/antd/_tag.less
- packages/theme/system/delon/_acl.less
- packages/theme/system/mixins/_freak.less
- packages/theme/system/theme-default.less
- packages/theme/system/utils/_align.less
- packages/theme/system/utils/_border.less
- packages/theme/system/utils/_color.less
- packages/theme/system/utils/_display.less
- packages/theme/system/utils/_float.less
- packages/theme/system/utils/_icon.less
- packages/theme/system/utils/_img.less
- packages/theme/system/utils/_other.less
- packages/theme/system/utils/_overflow.less
- packages/theme/system/utils/_position.less
- packages/theme/system/utils/_responsive.less
- packages/theme/system/utils/_text.less
- packages/theme/system/utils/_width.less
- scripts/build/generate-css.js
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add css docs

- packages/abc/se/demo/reactive.md
- packages/abc/se/index.en-US.md
- packages/abc/se/index.zh-CN.md
- packages/abc/se/se-container.component.ts
- packages/abc/se/se.component.ts
- packages/abc/se/se.spec.ts
- packages/util/src/config/abc/se.type.ts
- scripts/publish/sync-scaffold-version.js
- close https://github.com/ng-alain/ng-alain/issues/1701
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(abc:se): add `ingoreDirty` property

- src/app/shared/components/dialog/modal.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1699
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: fix callback in modal

- packages/form/src/widgets/upload/upload.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1704
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form:widget:upload): fix value should not be updated during initialization

- packages/form/spec/form.spec.ts
- packages/form/src/model/array.property.ts
- packages/form/src/widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1705
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form:widget:array): fix clean value of `cleanValue`

- packages/form/src/sf-item-wrap.component.html
- packages/form/src/sf.component.ts
- packages/theme/system/delon/_sf.less
- src/app/core/code/code.service.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form): fix text overflow ellipsis of lable

- packages/form/src/widgets/date/date.widget.ts
- packages/form/src/widgets/date/index.en-US.md
- packages/form/src/widgets/date/index.zh-CN.md
- packages/form/src/widgets/date/schema.ts
- packages/form/src/widgets/time/index.en-US.md
- packages/form/src/widgets/time/index.zh-CN.md
- packages/form/src/widgets/time/schema.ts
- packages/form/src/widgets/time/time.widget.html
- packages/form/src/widgets/time/time.widget.ts
- close https://github.com/ng-alain/ng-alain/issues/1707
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(form:widget:date): add `change` event

- packages/form/src/widgets/object/demo/card.md
- packages/form/src/widgets/object/index.en-US.md
- packages/form/src/widgets/object/index.zh-CN.md
- packages/form/src/widgets/object/object.widget.html
- packages/form/src/widgets/object/object.widget.spec.ts
- packages/form/src/widgets/object/object.widget.ts
- packages/form/src/widgets/object/schema.ts
- packages/theme/src/theme.module.ts
- packages/theme/system/delon/_sf.less
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```
> feat(form:widget:object): add expand of type is card

- packages/abc/reuse-tab/reuse-tab.component.spec.ts
- packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1702
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:reuse-tab): fix refresh tab component when call replace method of service

- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1697
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix call `resetColumns` method should clean data

- src/app/app.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: fix demo

- packages/abc/date-picker/range.component.ts
- packages/abc/error-collect/error-collect.component.ts
- packages/abc/image/image.directive.ts
- packages/abc/loading/loading.service.ts
- packages/abc/lodop/lodop.service.ts
- packages/abc/media/media.service.ts
- packages/abc/page-header/page-header.component.ts
- packages/abc/qr/qr.component.ts
- packages/abc/se/se-container.component.ts
- packages/abc/sg/sg-container.component.ts
- packages/abc/st/st.component.ts
- packages/abc/sv/sv-container.component.ts
- packages/abc/xlsx/xlsx.service.ts
- packages/abc/zip/zip.service.ts
- packages/acl/src/acl.service.ts
- packages/auth/src/auth.config.ts
- packages/cache/src/cache.service.ts
- packages/form/src/config.ts
- packages/mock/src/mock.service.ts
- packages/theme/src/services/http/http.client.ts
- packages/theme/src/services/responsive/responsive.ts
- packages/util/src/array/array.service.ts
- packages/util/src/config/config.service.ts
- packages/util/src/config/config.spec.ts
- src/app/shared/components/theme-btn/theme-btn.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> refactor: refactor global config

- packages/abc/st/index.en-US.md
- packages/abc/st/index.zh-CN.md
- packages/abc/st/st.component.ts
- packages/auth/src/token/base.interceptor.spec.ts
- packages/auth/src/token/base.interceptor.ts
- packages/form/src/widgets/select/demo/coordinate.md
- packages/util/src/logger/logger.spec.ts
- packages/util/src/other/check.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> test: add test

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/form/src/widgets/object/object.widget.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.4.0): release 9.4.0

- .github/workflows/deploy-site.yml
- Dockerfile.compile
- daocloud.yml
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> ci: update build

- packages/abc/se/se-container.component.ts
- packages/abc/se/se.component.ts
- packages/abc/se/se.spec.ts
- packages/abc/se/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:se): fix invalid auto assigned id under nested `se` component

- packages/abc/st/st.component.html
- packages/abc/st/st.component.ts
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1721
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix losing `nzWidthConfig`

- packages/chart/pie/pie.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1727
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(chart:pie): fix `isPercent` scope

- packages/schematics/plugin/plugin.icon.ts
- close https://github.com/ng-alain/ng-alain/issues/1726
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli:plugin:icon): fix skip cannot be resolved

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.4.1): release 9.4.1

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/interface.ts
- packages/form/src/model/array.property.ts
- packages/form/src/model/atomic.property.ts
- packages/form/src/model/form.property.ts
- packages/form/src/model/number.property.ts
- packages/form/src/model/object.property.ts
- packages/form/src/model/string.property.ts
- packages/form/src/sf.component.ts
- packages/form/src/widget.ts
- packages/form/src/widgets/array/array.widget.spec.ts
- packages/form/src/widgets/date/demo/simple.md
- packages/form/src/widgets/string/string.widget.spec.ts
- packages/form/src/widgets/upload/upload.widget.ts
- packages/testing/src/dispatch-events.ts
- scripts/git/commit-message.json
- src/app/routes/form-pages/validator/validator.component.html
- src/app/routes/form-pages/validator/validator.component.ts
- `formChange2` support return current path data, close #662
- fix trigger validator in conditional, close https://github.com/ng-alain/ng-alain/issues/1050, close https://github.com/ng-alain/ng-alain/issues/1675
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> refactor(sf): `formChange` instead of `formChange2`

- packages/theme/src/services/drawer/drawer.helper.ts
- packages/theme/src/services/drawer/drawer.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1679
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(theme:drawer): fix `nzWidth` is invalid

- packages/abc/abc.module.ts
- packages/chart/ng-package.json
- packages/chart/package.json
- close https://github.com/ng-alain/ng-alain/issues/1731
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): fix missing dependencie "@antv/data-set"

- packages/form/src/form.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form): export utils

- packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1734
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:reuest-tab): fix cannot read property 'active'

- packages/abc/reuse-tab/reuse-tab.component.html
- packages/abc/reuse-tab/reuse-tab.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1736
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:reuse-tab): fix take `nzSelectedIndex` of `nz-tabset`

- packages/abc/se/se.component.ts
- packages/abc/se/se.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:se): fix ingored set id when control invalid controlAccessor

- packages/theme/src/services/settings/index.en-US.md
- packages/theme/src/services/settings/index.zh-CN.md
- packages/theme/src/services/settings/settings.service.ts
- close https://github.com/ng-alain/ng-alain/issues/1737
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor(theme:SettingsService): optimized to be rewritten more friendly

- packages/theme/system/delon/_sf.less
- close https://github.com/ng-alain/ng-alain/issues/1738
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(form): fix invalid width of inline mode

- README.md
- docs/getting-started.en-US.md
- docs/getting-started.zh-CN.md
- packages/abc/README.md
- packages/acl/README.md
- packages/auth/README.md
- packages/cache/README.md
- packages/chart/README.md
- packages/form/README.md
- packages/mock/README.md
- packages/schematics/README.md
- packages/schematics/ng-add/index.ts
- packages/testing/README.md
- packages/theme/README.md
- packages/util/README.md
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): only supports angular 9.x

- packages/form/docs/getting-started.en-US.md
- packages/form/docs/getting-started.zh-CN.md
- packages/form/spec/base.spec.ts
- packages/form/spec/form.spec.ts
- packages/form/src/interface.ts
- packages/form/src/model/form.property.ts
- packages/form/src/sf.component.ts
- packages/form/src/widgets/date/demo/simple.md
- packages/form/src/widgets/string/demo/simple.md
- packages/util/src/util.module.ts
- src/app/routes/form-pages/validator/validator.component.html
- src/app/routes/form-pages/validator/validator.component.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(form): add `formValueChange` path

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.5.0): release 9.5.0

- packages/chart/timeline/demo/mask.md
- packages/chart/timeline/index.md
- packages/chart/timeline/timeline.component.ts
- packages/chart/timeline/timeline.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1744
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(chart:timeline): fix invalid format of slider

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.5.1): release 9.5.1

- packages/chart/bar/bar.component.ts
- packages/chart/docs/demo/resizable.md
- packages/chart/docs/faq.en-US.md
- packages/chart/docs/faq.zh-CN.md
- packages/chart/gauge/gauge.component.ts
- packages/chart/mini-area/mini-area.component.ts
- packages/chart/mini-bar/mini-bar.component.ts
- packages/chart/pie/pie.component.ts
- packages/chart/radar/radar.component.ts
- packages/chart/single-bar/single-bar.component.ts
- packages/chart/tag-cloud/tag-cloud.component.ts
- packages/chart/timeline/timeline.component.ts
- packages/chart/water-wave/water-wave.component.ts
- src/app/shared/shared-zorro.module.ts
- src/styles.less
- close https://github.com/ng-alain/ng-alain/issues/1746
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(chart:*): fix access to `chart` instances

- packages/abc/st/demo/grouping-columns.md
- packages/abc/st/st-column-source.ts
- packages/abc/st/st.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1706
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix invalid width in grouping header

- packages/abc/page-header/page-header.component.ts
- packages/abc/page-header/page-header.spec.ts
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:page-header): fix refresh title when route changed

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.5.2): release 9.5.2

- packages/abc/st/st.component.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/test/st.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1752
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix pre-clear data of `resetColumns` method

- packages/abc/media/media.service.ts
- packages/abc/media/media.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1751
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:media): fix loading multiple components at the same time will cause `No window.Plyr found`

- packages/abc/st/st.component.html
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix noResult misalignment in grouping header

- package.json
- packages/abc/ellipsis/ellipsis.component.html
- packages/abc/qr/qr.component.ts
- packages/abc/st/st.component.html
- packages/abc/xlsx/demo/import.md
- packages/abc/xlsx/xlsx.service.ts
- packages/abc/zip/demo/read.md
- packages/abc/zip/zip.service.ts
- packages/form/src/sf-item-wrap.component.html
- packages/form/src/widgets/array/array.widget.html
- packages/form/src/widgets/checkbox/checkbox.widget.html
- src/app/layout/header/header.component.html
- src/app/layout/header/search-box.component.ts
- src/app/routes/dev/demo/demo.component.ts
- src/app/routes/form-pages/validator/validator.component.ts
- src/app/shared/components/footer/footer.component.html
- src/app/shared/components/route-transfer/route-transfer.directive.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor: sync zorro 9.3.0

- .github/workflows/deploy-site.yml
- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.5.3): release 9.5.3

- packages/abc/sidebar-nav/sidebar-nav.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1764
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:sidebar): fix closed floating when toggle collapsed

- packages/abc/st/st-export.ts
- packages/abc/st/st.component.ts
- packages/abc/st/st.interfaces.ts
- packages/abc/st/test/st-export.spec.ts
- packages/abc/xlsx/index.en-US.md
- packages/abc/xlsx/index.zh-CN.md
- packages/abc/xlsx/xlsx.service.ts
- packages/abc/xlsx/xlsx.spec.ts
- packages/abc/xlsx/xlsx.types.ts
- fix(abc:st): fix show NaN when date is null in export
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(abc:st): fix over 26 columns export failure

- packages/abc/st/st-export.ts
- packages/abc/st/test/st-export.spec.ts
- packages/abc/xlsx/xlsx.service.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> refactor: fix build

- packages/auth/docs/getting-started.en-US.md
- packages/auth/docs/getting-started.zh-CN.md
- packages/auth/src/token/base.interceptor.spec.ts
- packages/auth/src/token/base.interceptor.ts
- close https://github.com/ng-alain/ng-alain/issues/1771
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```
> fix(auth): fix should removed `_allow_anonymous` property in truth request

- packages/theme/layout/default/_header.less
- close https://github.com/ng-alain/ng-alain/issues/1772
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(theme:layout:default): fix non-support autocomplete

- packages/abc/st/st-column-source.ts
- packages/abc/st/st.component.ts
- packages/abc/st/test/st-column-source.spec.ts
- close https://github.com/ng-alain/ng-alain/issues/1773
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(abc:st): fix ingore group column whne children is empty array

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.5.4): release 9.5.4

- docs/style-guide.en-US.md
- docs/style-guide.zh-CN.md
- package.json
- packages/schematics/application/index.ts
- packages/schematics/docs/plugin.en-US.md
- packages/schematics/docs/plugin.zh-CN.md
- packages/schematics/plugin/plugin.code-style.ts
- scripts/ci/build-schematics.sh
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```
> feat(cli): pretty-quick instead lint-staged

- scripts/site/utils/generate-md.ts
- src/app/core/i18n/en-US.ts
- src/app/core/i18n/zh-CN.ts
- src/app/layout/header/header.component.ts
- src/app/shared/components/docs/docs.component.html
- src/app/shared/components/docs/docs.component.ts
- src/app/shared/components/route-transfer/route-transfer.directive.ts
- src/site.config.js
- src/style/_toc.less
- src/style/_utils.less
- src/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> docs: add copy paragraph link

- packages/schematics/application/files/src/app/layout/default/header/header.component.html
- packages/schematics/application/files/src/app/shared/shared-zorro.module.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(cli): fix header

- CHANGELOG.md
- docs/changelog.en-US.md
- docs/changelog.zh-CN.md
- package.json
- packages/util/public_api.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> release(9.5.5): release 9.5.5

- packages/abc/onboarding/onboarding.component.html
- packages/abc/onboarding/onboarding.module.ts
- packages/abc/onboarding/onboarding.types.ts
- packages/abc/onboarding/public_api.ts
- packages/abc/onboarding/schema.json
- packages/abc/onboarding/style/index.less
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> feat(abc:onboarding): add `lightStyle` property

- packages/auth/docs/getting-started.en-US.md
- packages/auth/docs/getting-started.zh-CN.md
- packages/auth/docs/service.en-US.md
- packages/auth/docs/service.zh-CN.md
- packages/auth/src/auth.config.ts
- packages/auth/src/token/base.interceptor.spec.ts
- packages/auth/src/token/interface.ts
- packages/auth/src/token/jwt/jwt.model.ts
- packages/auth/src/token/simple/simple.interceptor.spec.ts
- packages/auth/src/token/simple/simple.model.ts
- packages/auth/src/token/token.service.spec.ts
- packages/auth/src/token/token.service.ts
- packages/util/src/config/auth/auth.type.ts
- close https://github.com/ng-alain/ng-alain/issues/1530
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(auth): add `refresh` event

- docs/upgrade-v10.en-US.md
- docs/upgrade-v10.zh-CN.md
- package.json
- packages/abc/notice-icon/notice-icon.spec.ts
- packages/abc/reuse-tab/reuse-tab.component.spec.ts
- packages/chart/tag-cloud/tag-cloud.component.ts
- packages/chart/timeline/timeline.component.ts
- packages/util/src/lazy/lazy.service.ts
- packages/util/src/logger/logger.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> chore: remove deprecation

- packages/chart/water-wave/index.md
- packages/chart/water-wave/water-wave.component.ts
- close https://github.com/ng-alain/ng-alain/issues/1786
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```
> feat(chart:water-wave): add `render()` method

- packages/mock/src/mock.interceptor.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(mock): show params in log

- packages/theme/src/services/http/http.client.ts
- packages/theme/src/services/http/http.spec.ts
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```
> fix(theme:http): fix ingored value handling when params is `HttpParams` type
