ng-alain/delon

packages/theme/services/modal/modal.helper.ts

maskClosable should be nzMaskClosable after ng-zorro-antd upgraded 0.7.x
To fix ModalHelper static method not works for stop `click mask close`
```
[x] Bugfix
[ ] Feature
```
Can not hold back to click mask close.
Fixed 
```
[ ] Yes
[x ] No
```

Fixed ModalHelper static method not works for stop `click mask close`

---

packages/theme/styles/layout/default/aside.less
packages/theme/styles/layout/default/fix/footer-toolbar.less
packages/theme/styles/layout/default/fix/reuse-tab.less
packages/theme/styles/layout/default/fix/sidebar-nav.less
packages/theme/styles/layout/default/fixed.less
packages/theme/styles/layout/default/header.less
packages/theme/styles/layout/default/index.en-US.md
packages/theme/styles/layout/default/index.zh-CN.md
packages/theme/styles/layout/default/layout.less
packages/theme/styles/layout/default/user.less
src/app/routes/dev/layout.component.ts

BREAKING CHANGE:
+ `layout-fixed` was changed to `alain-default__fixed`
+ `layout-boxed` was changed to `alain-default__boxed`
+ `aside-collapsed` was changed to `alain-default__collapsed`
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```

feat(module:theme:alain-default): refactor layout component

---

docs/i18n.md
packages/theme/src/services/i18n/i18n.pipe.ts
packages/theme/src/services/i18n/i18n.spec.ts
packages/theme/src/services/i18n/i18n.ts
packages/theme/src/theme.module.ts
src/app/core/i18n/service.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(module:theme:i18n): add i18n pipe

---

packages/abc/table/table-data-source.ts
packages/abc/table/table.component.ts
packages/abc/table/test/table-data-source.spec.ts
packages/abc/table/test/table.spec.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(module:st): fix render null when value is null in edge or ie

---

docs/upgrade-v2.en-US.md
docs/upgrade-v2.zh-CN.md
packages/abc/table/index.en-US.md
packages/abc/table/index.zh-CN.md
packages/abc/table/table.component.ts
packages/abc/table/test/table.spec.ts
packages/schematics/ng-update/upgrade-rules/misc-checks/checkPropertyNamesMiscRule.ts

Breaking Changes:
- Use `(change)`  instead
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

refactor(module:st): remove deprecated events

---

packages/theme/src/services/i18n/i18n.ts
packages/theme/src/services/title/index.en-US.md
packages/theme/src/services/title/index.zh-CN.md
packages/theme/src/services/title/title.service.spec.ts
packages/theme/src/services/title/title.service.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(module:theme:title): add setTitleByI18n method

---

packages/schematics/core/lang.config.ts
packages/schematics/docs/plugin.en-US.md
packages/schematics/docs/plugin.zh-CN.md
packages/theme/docs/locale.en-US.md
packages/theme/docs/locale.zh-CN.md
packages/theme/src/locale/languages/pl-PL.ts
packages/theme/src/locale/public_api.ts

```
[ ] Bugfix
[X] Feature
```
N/A
Issue Number: #307 
N/A
```
[ ] Yes
[X] No
```
This is a set of files for the Polish locale for Delon. [ng-alain PR is comming along](https://github.com/ng-alain/ng-alain/issues/807), just give me a second...

feat(module:theme): adding Polish locale

---

.editorconfig
package.json
packages/abc/table/demo/expand.md
packages/abc/table/index.en-US.md
packages/abc/table/index.zh-CN.md
packages/abc/table/table-column-source.ts
packages/abc/table/table-data-source.ts
packages/abc/table/table.component.ts
packages/abc/table/table.config.ts
packages/abc/table/test/table.spec.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(module:st): add expandRowByClick property

---

_mock/user.ts
packages/abc/table/demo/basic.md
packages/abc/table/index.en-US.md
packages/abc/table/index.zh-CN.md
packages/abc/table/table-data-source.ts
packages/abc/table/table.component.ts
packages/abc/table/test/table-data-source.spec.ts
packages/abc/table/test/table.spec.ts
src/app/shared/shared.module.ts
src/styles.less

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(module:st): support response body is an array type

---

scripts/ci/build-schematics.sh

A simple solution, manually modify the version number of ng-alain-codelyzer to `^0.0.1` and run yarn again
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(module:schematics): fix missing version of ng-alain-codelyzer

---

packages/abc/table/index.en-US.md
packages/abc/table/index.zh-CN.md
packages/abc/table/table.component.ts
packages/abc/table/table.config.ts
packages/abc/table/table.interfaces.ts
packages/abc/table/test/table.spec.ts

fix(abc:st): fix ingore truncate of img column when `strictBehavior` is `truncate`
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:st): add `lazyLoad` property in `req`

---

packages/abc/table/index.en-US.md
packages/abc/table/index.zh-CN.md
packages/abc/table/table-column-source.ts
packages/abc/table/table-data-source.ts
packages/abc/table/table.component.ts
packages/abc/table/table.interfaces.ts
packages/abc/table/test/table-column-source.spec.ts
packages/abc/table/test/table-data-source.spec.ts
packages/abc/table/test/table.spec.ts

fix(abc:table): fix invalid global `sortReName` property in mulitisort
- close https://github.com/ng-alain/ng-alain/issues/1399
```
[x] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:table): add `keepEmptyKey` of mulitisort

---

packages/form/src/widgets/date/date.widget.spec.ts
packages/form/src/widgets/date/date.widget.ts

- close https://github.com/ng-alain/ng-alain/issues/1560
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form:widget:date): fix format default value

---

packages/abc/st/st.component.html
packages/abc/st/st.component.ts
packages/abc/st/test/st.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/1805
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(abc:st): fix `width` can't be reset when refresh group columns

---

packages/theme/src/pipes/currency/cn-currency.pipe.ts

There is an upcoming improvement in common pipes in Angular framework that would be released in the next major version (v11). The changes can be found in https://github.com/angular/angular/pull/37447.
This commit refactors the `CNCurrencyPipe` pipe to provide forward-compatibility for the next major release of Angular framework. The improved typings make `transform` function signature of the mentioned pipe incompatible with the `CurrencyPipe`. This commit updates the `CNCurrencyPipe` pipe to initialize the `CurrencyPipe` in constructor instead of extending it (to keep existing `transform` function signature) and use created instance inside the `transform` function as needed.

refactor: forward-compatibility for upcoming type improvements in Angular Pipes

---

packages/theme/docs/getting-started.zh-CN.md

更正前： @delon/theme 是 ng-alain 架手脚唯一必须引入的模块。
更正后：@delon/theme 是 ng-alain 手脚架唯一必须引入的模块。

docs: typo

---

packages/abc/reuse-tab/index.en-US.md
packages/abc/reuse-tab/index.zh-CN.md

当前的文档，缺失重要引导：在实际使用 reuse tab的模块中，引入 ReuseTabModule 模块。
后果：导致在模板中找不到 reuse-tab 标签。
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(abc:reuse-tab): fix typo

---

packages/abc/st/st.component.ts
packages/abc/st/test/st.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2056
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:st): fix invalid `toTop` when `scroll` is set

---

packages/chart/timeline/index.md

```
[ ] Bugfix
[ ] Feature
```
Url of G2 mask is outdated, which is currently 404.
Update to latest url. https://g2.antv.vision/zh/docs/manual/tutorial/scale#time
```
[ ] Yes
[x] No
```

docs(chart): update url of G2 mask format

---

packages/form/src/sf-fixed.directive.ts

修复当设置array widget ui 的spanlabelfixed时，数组小部件的ant-form-item-control-wrapper未按比例显示在同一行内
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form:array): fix array spanlabelfixed style

---

packages/form/src/sf-item.component.ts
packages/form/src/sf.component.html
packages/form/src/style/index.less

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form): fix buttons misalignment in `inline` layout

---

packages/form/src/model/form.property.factory.ts
packages/form/src/model/form.property.ts

当有嵌套Object  property时且嵌套的属性中定义了visibleIf，_bindVisibility被重复调用并订阅执行setVisible。当visibleIf发生变化时将重新触发resetValue多次。
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form): fix form multiple bind visibility

---

packages/form/src/model/form.property.ts
packages/form/src/sf.component.ts

- close https://github.com/ng-alain/ng-alain/issues/2375
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form): fix can't render due to inherited

---

.stylelintrc
package.json
packages/abc/page-header/style/index.less
packages/abc/page-header/style/rtl.less
packages/form/src/style/index.less
packages/theme/default.less
packages/theme/layout-blank/style/index.less
packages/theme/layout-default/style/_aside.less
packages/theme/layout-default/style/_layout.less
packages/theme/layout-default/style/fix/_sidebar-nav.less
packages/theme/layout-default/style/index.less
packages/theme/layout-default/style/widgets/_user.less
packages/theme/system/antd/_drawer.less
packages/theme/system/antd/index.less
schematics/application/index.ts
schematics/ng-update/upgrade-rules/v16/index.spec.ts
schematics/ng-update/upgrade-rules/v16/index.ts
schematics/test.ts
scripts/ci/utils.sh

- see: https://github.com/prettier/stylelint-config-prettier#stylelint-config-prettier
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(cli): remove `stylelint-config-prettier`

---

packages/abc/reuse-tab/index.en-US.md
packages/abc/reuse-tab/index.zh-CN.md
packages/abc/reuse-tab/reuse-tab.cache.ts
packages/abc/reuse-tab/reuse-tab.module.ts
packages/abc/reuse-tab/reuse-tab.service.spec.ts
packages/abc/reuse-tab/reuse-tab.service.ts

- close https://github.com/ng-alain/ng-alain/issues/2400
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:reuse-tab): support custom cache data

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(16.1.0): release 16.1.0

---

package.json
packages/theme/src/services/modal/index.en-US.md
packages/theme/src/services/modal/index.zh-CN.md
packages/theme/src/services/modal/modal.helper.ts
packages/theme/src/services/modal/modal.spec.ts

- 保留 nzComponentParams 原有风格，其实这个方案还蛮好用的，但依然可以通过 @Inject(NZ_MODAL_DATA) 获取 ng-zorro 的标准写法
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

fix(theme:modal): removed `nzComponentParams`

---

packages/theme/layout-default/index.en-US.md
packages/theme/layout-default/index.zh-CN.md
packages/theme/layout-default/layout.component.spec.ts
packages/theme/layout-default/layout.component.ts

- close https://github.com/ng-alain/ng-alain/issues/2403
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(theme:layout-default): add `fetching` property

---

schematics/application/index.ts
schematics/docs/default.en-US.md
schematics/docs/default.zh-CN.md

```
[x] Bugfix
[ ] Feature
```
Angular CLI: 16.1.4
Node: 20.1.0 (Unsupported)
Package Manager: npm 9.6.4
OS: win32 x64
After running `ng g module xxx`, shows error below
```
Schematic input does not validate against the Schema: {"routing":true,"skipTests":false,"name":"xxx","path":"src/app/routes","project":"frontend"}       
Errors:
Data path "" must NOT have additional properties(skipTests).
```
And …

fix(cli): remove `skipTests` from generating module

---

packages/abc/st/demo/colspan-rowspan.md
packages/abc/st/index.en-US.md
packages/abc/st/index.zh-CN.md
packages/abc/st/st-data-source.ts
packages/abc/st/st.component.html
packages/abc/st/st.component.ts
packages/abc/st/st.interfaces.ts
packages/abc/st/st.types.ts
packages/abc/st/test/st-data-source.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2404
```
[ ] Bugfix
[x] Feature
```
```
[x] Yes
[ ] No
```

feat(abc:st): add `onCell`, support colSpan and rowSpan merging

---

packages/abc/se/demo/complex.md
packages/abc/se/se.component.ts
packages/abc/sg/demo/basic.md
packages/abc/sg/sg-container.component.ts
packages/abc/sg/sg.component.ts
packages/abc/sv/demo/basic.md
packages/abc/sv/index.en-US.md
packages/abc/sv/index.zh-CN.md
packages/abc/sv/sv-container.component.ts
packages/abc/sv/sv.component.ts
packages/theme/src/services/responsive/responsive.spec.ts
packages/theme/src/services/responsive/responsive.ts
packages/util/config/theme/responsive.type.ts

- close https://github.com/ng-alain/ng-alain/issues/2386
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(*): fix misalignment of `col` placeholders in `se`, `sv`, `sg`

---

packages/chart/timeline/index.md
packages/chart/timeline/timeline.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(chat:timeline): fix `y2` to be optional

---

docs/how-to-start.zh-CN.md
docs/i18n.en-US.md
docs/i18n.zh-CN.md
packages/acl/docs/guard.en-US.md
packages/acl/docs/guard.zh-CN.md
packages/acl/src/acl-guard.spec.ts
packages/acl/src/acl-guard.ts
packages/acl/src/acl.module.ts
packages/acl/src/acl.type.ts
packages/auth/docs/guard.en-US.md
packages/auth/docs/guard.zh-CN.md
packages/auth/src/token/jwt/jwt.guard.spec.ts
packages/auth/src/token/jwt/jwt.guard.ts
packages/auth/src/token/simple/simple.guard.spec.ts
packages/auth/src/token/simple/simple.guard.ts
packages/theme/src/services/i18n/i18n-url.guard.ts
packages/theme/src/services/i18n/i18n.spec.ts
schematics/application/files/src/app/routes/routes-routing.module.ts
src/app/routes/routes.module.ts

-  refactor `ACLGuard` to `aclCanMatch`, `aclCanActivate`, `aclCanActivateChild`
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

refactor(*): refactor `CanActivate` to `CanActivateFn`

---

packages/abc/onboarding/onboarding.service.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(abc:onboarding): fix `ComponentFactoryResolver`

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(16.2.0): release 16.2.0

---

packages/abc/st/demo/basic.md
packages/abc/st/st.interfaces.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: update demo

---

packages/abc/avatar-list/avatar-list.component.ts
packages/abc/error-collect/error-collect.component.ts
packages/abc/exception/exception.component.ts
packages/abc/exception/exception.spec.ts
packages/abc/full-content/full-content.component.ts
packages/abc/global-footer/global-footer.component.ts
packages/abc/media/media.component.ts
packages/abc/page-header/page-header.component.ts
packages/abc/pdf/pdf.component.ts
packages/abc/result/result.component.ts
packages/abc/reuse-tab/reuse-tab.component.ts
packages/abc/se/se.component.ts
packages/abc/st/demo/virtual.md
packages/abc/st/st.component.ts
packages/abc/tag-select/tag-select.component.ts
packages/chart/chart-echarts/echarts.component.ts
packages/form/src/sf.component.ts
packages/theme/layout-default/layout-header.component.ts
packages/theme/layout-default/layout-nav.component.ts
packages/theme/layout-default/layout.component.ts
packages/theme/setting-drawer/setting-drawer.component.ts
packages/theme/src/services/title/title.service.ts
packages/theme/theme-btn/theme-btn.component.ts
src/app/layout/layout.component.ts
src/app/routes/form-pages/validator/validator.component.ts
src/app/shared/components/code-box/code-box.component.ts
src/app/shared/components/content/content.component.ts
src/app/shared/components/main-menu/main-menu.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

refactor(*): unsubscribe with `takeUntilDestroyed`

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(16.2.1): release 16.2.1

---

packages/theme/src/services/modal/index.en-US.md
packages/theme/src/services/modal/index.zh-CN.md
packages/theme/src/services/modal/modal.helper.ts
packages/theme/src/services/modal/modal.spec.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(theme:modal): add size support percentage

---

schematics/application/files/src/app/routes/routes-routing.module.ts
src/app/routes/routes.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(cli): add `bindToComponentInputs` of `ng add`

---

packages/theme/src/services/drawer/drawer.helper.ts
packages/theme/src/services/drawer/drawer.spec.ts
packages/theme/src/services/drawer/index.en-US.md
packages/theme/src/services/drawer/index.zh-CN.md
src/app/app.component.ts
src/app/shared/components/dialog/drawer.component.ts

- close https://github.com/ng-alain/ng-alain/issues/2377
- close https://github.com/ng-alain/ng-alain/issues/2280
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(theme:drawer): add `closeAll`, `openDrawers` method

---

packages/abc/st/demo/virtual.md
packages/abc/st/st-data-source.ts
packages/abc/st/st-td.component.html
packages/abc/st/st.component.ts
packages/abc/st/test/base.spec.ts
packages/abc/st/test/st-filter.spec.ts
packages/abc/st/test/st.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2233
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

refactor(abc:st): use `Observable` instead of `Promise` of load

---

package.json
packages/abc/package.json
packages/abc/pdf/demo/design.md
packages/abc/pdf/index.en-US.md
packages/abc/pdf/index.zh-CN.md
packages/abc/pdf/pdf.component.ts
packages/abc/pdf/pdf.types.ts
scripts/site/route-paths.txt
src/app/global-config.module.ts

Although pdfjs-dist is an optional dependency on canvas, Will be installed automatically when the dependency is installed by default; This requires a higher environment and often fails to install
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(abc:pdf): fix ignore dependency `pdfjs-dist`

---

packages/abc/page-header/demo/structure.md
packages/abc/page-header/index.en-US.md
packages/abc/page-header/index.zh-CN.md
packages/abc/page-header/page-header.component.html
packages/abc/page-header/page-header.component.ts
packages/abc/page-header/page-header.module.ts
packages/abc/page-header/page-header.spec.ts
packages/abc/page-header/style/index.less
packages/abc/theme-default.less

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:page-header): add `titleSub` property

---

packages/form/src/widgets/select/select.widget.ts

- close https://github.com/ng-alain/ng-alain/issues/2415
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(form:select): fix ignore reset option data when set `onSearch`

---

.eslintrc.js
CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json
scripts/publish/package.json
scripts/publish/publish-scaffold.js
scripts/publish/publish.js
scripts/publish/sync-scaffold-version.js

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(16.3.0): release 16.3.0

---

packages/theme/src/services/i18n/i18n-url.guard.ts
src/app/layout/header/header.component.ts
src/app/routes/routes.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: correctly use local language in document site

---

packages/abc/st/st-export.ts

- close https://github.com/ng-alain/ng-alain/issues/2423
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:st): correct width misalignment in export excel

---

packages/form/src/model/array.property.ts
packages/form/src/model/form.property.factory.ts
packages/form/src/model/form.property.ts
packages/form/src/model/object.property.ts
packages/form/src/sf.component.ts
packages/form/src/widgets/autocomplete/autocomplete.widget.spec.ts
packages/form/src/widgets/checkbox/checkbox.widget.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2419
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

fix(form): fix `visibleIf` to correctly trigger `reset`

---

packages/form/src/sf.component.ts
packages/form/src/widgets/array/index.en-US.md
packages/form/src/widgets/array/index.zh-CN.md

- close https://github.com/ng-alain/ng-alain/issues/2429
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form:array): fix invalid ui in `ui` schema

---

packages/abc/onboarding/demo/basic.md
packages/abc/onboarding/index.en-US.md
packages/abc/onboarding/index.zh-CN.md
packages/abc/onboarding/onboarding.service.ts
packages/abc/onboarding/onboarding.spec.ts
packages/abc/onboarding/onboarding.storage.ts
packages/abc/onboarding/onboarding.types.ts
packages/abc/onboarding/public_api.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:onboarding): add `key`

---

packages/form/src/widgets/select/select.widget.spec.ts
packages/form/src/widgets/select/select.widget.ts

- close https://github.com/ng-alain/ng-alain/issues/2427
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form:select): correct trigger onSearch in reset when set value

---

docs/i18n.en-US.md
docs/i18n.zh-CN.md
package.json
schematics/application/files/src/app/app.module.ts
schematics/plugin/plugin.default-language.spec.ts
schematics/plugin/plugin.default-language.ts
src/app/core/code/files/app.module.ts
src/app/core/code/files/global-config.module.ts
src/app/global-config.module.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[ ] No
```

feat: add provide function

---

packages/form/spec/schema.spec.ts
packages/form/src/sf.component.ts
packages/form/src/widgets/object/object.widget.html

- fix(form:widget:object): fix missing optional of card type
- close https://github.com/ng-alain/ng-alain/issues/2426
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form): fix render UI can't be inherit

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json
scripts/publish/publish.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(16.4.0): release 16.4.0

---

packages/theme/src/services/modal/modal.helper.ts
packages/theme/system/antd/_modal.less

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(theme:modal): perf code

---

docs/server.en-US.md
docs/server.zh-CN.md

- close https://github.com/ng-alain/ng-alain/issues/2339
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: update qa

---

.eslintignore
packages/theme/public_api.ts
packages/theme/src/services/preloader/preloader.spec.ts
packages/theme/src/services/preloader/preloader.ts
schematics/ng-update/upgrade-rules/v17/index.spec.ts
schematics/ng-update/upgrade-rules/v17/index.ts
schematics/ng-update/upgrade-rules/v17/preloader.ts
schematics/ng-update/upgrade-rules/v17/removeForRoot.ts
src/app/app.component.ts
src/index.html
src/main.ts

BREAKING CHANGE: 之前提供的 `preloaderFinished` 并不能解决当首次加载的路由是懒加载时中间存在空白问题
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(theme:preloader): fix loading order issues

---

packages/abc/hotkey/hotkey.directive.ts
packages/abc/hotkey/hotkey.module.ts
packages/abc/let/let.directive.ts
packages/abc/let/let.module.ts
packages/abc/observers/observer-size.ts
packages/abc/xlsx/xlsx.directive.ts
packages/abc/xlsx/xlsx.module.ts
packages/abc/zip/index.en-US.md
packages/abc/zip/index.zh-CN.md
packages/abc/zip/public_api.ts
packages/abc/zip/zip.module.ts
packages/abc/zip/zip.spec.ts
packages/theme/theme-btn/theme-btn.component.html
packages/theme/theme-btn/theme-btn.component.ts
packages/theme/theme-btn/theme-btn.module.ts
packages/util/pipes/currency/cny.pipe.ts
packages/util/pipes/currency/mega.pipe.ts
packages/util/pipes/currency/module.ts
packages/util/pipes/currency/price.pipe.ts
packages/util/pipes/filter/filter.pipe.ts
packages/util/pipes/filter/module.ts
packages/util/pipes/format/mask.pipe.ts
packages/util/pipes/format/module.ts
src/app/core/code/files/delon-abc.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(*): support standalone

---

packages/mock/docs/getting-started.en-US.md
packages/mock/docs/getting-started.zh-CN.md
packages/mock/src/mock.interceptor.spec.ts
packages/mock/src/mock.service.spec.ts
packages/mock/src/provide.ts
packages/theme/src/config.ts
schematics/ng-update/upgrade-rules/v17/index.spec.ts
schematics/ng-update/upgrade-rules/v17/replaceProvideConfig.ts
src/app/app.config.ts
src/app/core/code/files/global-config.module.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: fix `provideMockConfig`

---

packages/theme/src/services/i18n/i18n.pipe.ts
packages/theme/src/services/i18n/i18n.spec.ts
packages/theme/src/services/i18n/i18n.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(theme:i18n): correct params type of i18e pipe

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(17.0.4): release 17.0.4

---

packages/abc/st/st-export.ts
packages/abc/st/test/st-export.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2461
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:st): fix export mismatch

---

.vscode/launch.json
packages/abc/auto-focus/index.en-US.md
packages/abc/auto-focus/index.zh-CN.md
scripts/site/utils/generate-md.ts
scripts/site/utils/utils.ts
src/app/shared/components/docs/docs.component.ts
src/styles/_markdown.less
src/typings.d.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: fix site

---

packages/abc/reuse-tab/reuse-tab.component.spec.ts
packages/abc/reuse-tab/reuse-tab.component.ts
packages/abc/reuse-tab/reuse-tab.service.spec.ts
packages/abc/reuse-tab/reuse-tab.service.ts
src/dev/pages/page.component.ts
src/dev/router.ts

- close https://github.com/ng-alain/ng-alain/issues/2464
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:reuse-tab): fix keep open order

---

packages/abc/auto-focus/auto-focus.directive.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(abc:auto-focus): perf code

---

docs/deploy.en-US.md
docs/deploy.zh-CN.md

- close https://github.com/ng-alain/ng-alain/issues/2472
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: update deploy

---

packages/form/src/model/array.property.ts
packages/form/src/widgets/array/array.widget.ts

-  close https://github.com/ng-alain/ng-alain/issues/2470
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form:widget:array): fix error remove notify

---

.github/workflows/ci.yml
packages/abc/st/index.en-US.md
packages/abc/st/index.zh-CN.md
packages/abc/st/st.component.html
packages/abc/st/st.component.ts

- close https://github.com/ng-alain/ng-alain/issues/2477
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:st): add `trackBy` property

---

package.json
packages/theme/docs/global.en-US.md
packages/theme/docs/global.zh-CN.md
packages/theme/system/theme-default.less
packages/theme/system/utils/_scrollbar.less
src/styles/theme.less
yarn.lock

- close https://github.com/ng-alain/ng-alain/issues/2476
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix: fix scrollbar thumb color default is transparent

---

packages/theme/package.json

`@delon/theme` is importing styles by relative paths, which will cause error if `@delon/abc` and `@delon/form` is not installed
```
[x] Bugfix
[ ] Feature
```
`@delon/theme` is importing styles by relative paths, which will cause error if `@delon/abc` and `@delon/form` is not installed
`@delon/abc` and `@delon/form` will be dependency of `@delon/theme`
```
[ ] Yes
[x] No
```

fix: update theme/package.json to depend on @delon/abc and @delon/form

---

packages/form/widgets-third/monaco-editor/index.en-US.md
packages/form/widgets-third/monaco-editor/index.zh-CN.md
packages/form/widgets-third/tinymce/index.en-US.md
packages/form/widgets-third/tinymce/index.zh-CN.md
packages/form/widgets/autocomplete/index.en-US.md
packages/form/widgets/autocomplete/index.zh-CN.md
packages/form/widgets/cascader/index.en-US.md
packages/form/widgets/cascader/index.zh-CN.md
packages/form/widgets/color/index.en-US.md
packages/form/widgets/color/index.zh-CN.md
packages/form/widgets/mention/index.en-US.md
packages/form/widgets/mention/index.zh-CN.md
packages/form/widgets/qr-code/index.en-US.md
packages/form/widgets/qr-code/index.zh-CN.md
packages/form/widgets/rate/index.en-US.md
packages/form/widgets/rate/index.zh-CN.md
packages/form/widgets/segmented/index.en-US.md
packages/form/widgets/segmented/index.zh-CN.md
packages/form/widgets/slider/index.en-US.md
packages/form/widgets/slider/index.zh-CN.md
packages/form/widgets/tag/index.en-US.md
packages/form/widgets/tag/index.zh-CN.md
packages/form/widgets/time/index.en-US.md
packages/form/widgets/time/index.zh-CN.md
packages/form/widgets/transfer/index.en-US.md
packages/form/widgets/transfer/index.zh-CN.md
packages/form/widgets/tree-select/index.en-US.md
packages/form/widgets/tree-select/index.zh-CN.md
packages/form/widgets/upload/index.en-US.md
packages/form/widgets/upload/index.zh-CN.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(sf): non-built-in widget registration method

---

angular.json
packages/abc/cell/cell-host.directive.ts
packages/abc/cell/cell.component.ts
packages/abc/cell/cell.spec.ts
packages/abc/cell/cell.types.ts
packages/abc/cell/index.en-US.md
packages/abc/cell/index.zh-CN.md
src/app/shared/cell-widget/test.ts

Breaking Changes:
为了保持数据处理结果的统一性，将小部件的 `data` 类型由原来的 `CellWidgetData` 变更为 `CellTextResult` 以此来保证数据为处理后的结果。
```
[ ] Bugfix
[ ] Feature
```
```
[x] Yes
[ ] No
```

refactor(abc:cell): widget `data` type changed to CellTextResult

---

packages/auth/docs/getting-started.en-US.md
packages/auth/docs/getting-started.zh-CN.md
packages/auth/src/auth.config.ts
packages/util/config/auth/auth.type.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

feat(auth): ignore all local resource

---

packages/abc/README.md
packages/acl/README.md
packages/auth/README.md
packages/cache/README.md
packages/chart/README.md
packages/form/README.md
packages/mock/README.md
packages/testing/README.md
packages/theme/README.md
packages/util/README.md
schematics/README.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs: typo readme

---

package.json
packages/abc/cell/cell.spec.ts
packages/form/widgets/upload/widget.spec.ts
schematics/plugin/plugin.icon.ts
yarn.lock

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

chore: bump ng-zorro to 17.3

---

.github/workflows/ci.yml
CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json
scripts/ci/build-artifacts.sh
scripts/publish/publish.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(17.3.0): release 17.3.0

---

schematics/application/files/src/app/core/startup/startup.service.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(cli): add `./` current fold in `startup.service`

---

.github/workflows/ci.yml
scripts/ci/build-artifacts.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

ci: fix upload to delon-builds when push

---

packages/theme/docs/customize-theme.en-US.md
packages/theme/docs/customize-theme.zh-CN.md

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

docs(theme):  typo demo

---

packages/abc/cell/cell-host.directive.ts
packages/abc/cell/cell.service.ts
packages/abc/cell/cell.spec.ts
packages/abc/cell/demo/simple.md

- close https://github.com/ng-alain/ng-alain/issues/2494
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(abc:cell): fix can't change detection of widget

---

packages/abc/st/demo/resizable.md
packages/abc/st/st.component.html
packages/abc/st/style/index.less

- close https://github.com/ng-alain/ng-alain/issues/2493
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:st): fix resizeable will trigger sorting or filter

---

packages/abc/cell/cell.spec.ts
packages/abc/down-file/down-file.spec.ts
packages/abc/exception/exception.spec.ts
packages/abc/full-content/full-content.spec.ts
packages/abc/global-footer/global-footer.spec.ts
packages/abc/notice-icon/notice-icon.spec.ts
packages/abc/onboarding/onboarding.spec.ts
packages/abc/page-header/page-header.spec.ts
packages/abc/reuse-tab/reuse-tab.component.spec.ts
packages/abc/st/test/base.spec.ts
packages/abc/xlsx/xlsx.spec.ts
packages/acl/src/acl-guard.spec.ts
packages/auth/src/social/social.service.spec.ts
packages/auth/src/token/base.interceptor.spec.ts
packages/auth/src/token/jwt/jwt.guard.spec.ts
packages/auth/src/token/jwt/jwt.interceptor.spec.ts
packages/auth/src/token/simple/simple.guard.spec.ts
packages/auth/src/token/simple/simple.interceptor.spec.ts
packages/cache/src/cache.spec.ts
packages/form/spec/base.spec.ts
packages/theme/layout-default/layout-nav.component.spec.ts
packages/theme/layout-default/layout.component.spec.ts
packages/theme/src/services/http/http.spec.ts
packages/theme/src/services/i18n/i18n.spec.ts
packages/theme/src/services/title/title.service.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(*): clean deprecated of angular libs

---

packages/abc/avatar-list/avatar-list.component.ts
packages/abc/error-collect/error-collect.component.ts
packages/abc/exception/exception.component.ts
packages/abc/global-footer/global-footer.component.ts
packages/abc/loading/loading.service.ts
packages/abc/onboarding/onboarding.service.ts
packages/abc/page-header/page-header.component.ts
packages/abc/page-header/page-header.spec.ts
packages/abc/result/result.component.ts
packages/abc/reuse-tab/reuse-tab.component.ts
packages/abc/st/st-export.ts
packages/abc/st/st.component.ts
packages/abc/tag-select/tag-select.component.ts
packages/form/src/sf.component.ts
packages/theme/layout-default/layout-nav.component.ts
packages/theme/setting-drawer/setting-drawer.component.ts
packages/theme/src/services/menu/menu.service.ts
packages/theme/src/services/title/title.service.ts
packages/theme/theme-btn/theme-btn.component.ts
scripts/site/route-paths.txt

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

perf(*): remove unnecessary optional attributes

---

packages/abc/st/st.component.ts

- close https://github.com/ng-alain/ng-alain/issues/2479
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:st): fix optional use context menu

---

.github/workflows/build-doc-site-aliyun-docker.yml
.github/workflows/build-doc-site-docker.yml
.github/workflows/deploy-site.yml
.github/workflows/mirror-gitee.yml
schematics/application/index.spec.ts
schematics/application/index.ts
schematics/test.ts
schematics/utils/workspace.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(cli): corrected missing setup `src/assets` of `angular.json`

---

packages/abc/st/test/st.spec.ts
scripts/build/generate-css.js
scripts/ci/build-artifacts-site.sh
scripts/ci/build-artifacts.sh
scripts/ci/build-delon.sh

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

build: correct css not generated

---

packages/form/src/widgets/select/select.widget.ts

```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(form:select): fix `maxTagCount` default value is `Infinity`

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(18.1.0): release 18.1.0

---

packages/auth/docs/getting-started.en-US.md
packages/auth/docs/getting-started.zh-CN.md
packages/auth/docs/send.en-US.md
packages/auth/docs/send.zh-CN.md
packages/auth/docs/set.en-US.md
packages/auth/docs/set.zh-CN.md
packages/auth/src/store/cookie-storage.service.ts
packages/auth/src/store/local-storage.service.ts
packages/auth/src/store/session-storage.service.ts

- close https://github.com/ng-alain/ng-alain/issues/2516
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

docs(auth): typo

---

schematics/utils/alain.ts

- close https://github.com/ng-alain/ng-alain/issues/2517
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(cli): fix could not find any [routes] variable

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(18.2.0): release 18.2.0

---

packages/theme/layout-default/style/_header.less

- close https://github.com/ng-alain/ng-alain/issues/2519
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(theme:default): fix inconsistency of top icon size

---

packages/form/src/widgets/select/index.en-US.md
packages/form/src/widgets/select/index.zh-CN.md
packages/form/src/widgets/select/schema.ts
packages/form/src/widgets/select/select.widget.spec.ts
packages/form/src/widgets/select/select.widget.ts
packages/form/widgets/cascader/index.en-US.md
packages/form/widgets/cascader/index.zh-CN.md
packages/form/widgets/cascader/schema.ts
packages/form/widgets/cascader/widget.ts
packages/form/widgets/tree-select/index.en-US.md
packages/form/widgets/tree-select/index.zh-CN.md
packages/form/widgets/tree-select/schema.ts
packages/form/widgets/tree-select/widget.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(form:select,cascader,tree-select): default value when cleared

---

CHANGELOG.md
docs/changelog.en-US.md
docs/changelog.zh-CN.md
package.json

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

release(18.3.0): release 18.3.0

---

packages/abc/avatar-list/avatar-list.component.ts
packages/abc/avatar-list/avatar-list.module.ts
packages/abc/avatar-list/index.en-US.md
packages/abc/avatar-list/index.zh-CN.md

will be removed in v20, Please use `nz-avatar-group` instead
```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(abc:avatar-list): set deprecated

---

packages/theme/src/services/menu/index.en-US.md
packages/theme/src/services/menu/index.zh-CN.md
packages/theme/src/services/menu/menu.service.spec.ts
packages/theme/src/services/menu/menu.service.ts

```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(theme:menu): add `getDefaultRedirect` method

---

packages/abc/st/index.en-US.md
packages/abc/st/index.zh-CN.md
packages/abc/st/st.component.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(abc:st): add `arrayProcessMethod` in `setRow`

---

packages/abc/st/st-column-source.ts
packages/abc/st/st.interfaces.ts
packages/abc/st/test/base.spec.ts
packages/abc/st/test/st.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2528
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:st): add i18n in `pop`

---

packages/abc/st/st-column-source.ts
packages/abc/st/st.component.html
packages/abc/st/st.component.ts
packages/abc/st/test/st-column-source.spec.ts

- close https://github.com/ng-alain/ng-alain/issues/2534
```
[x] Bugfix
[ ] Feature
```
```
[ ] Yes
[x] No
```

fix(abc:st): misalignment when fixed and expand is set

---

packages/abc/st/demo/drag.md
packages/abc/st/index.en-US.md
packages/abc/st/index.zh-CN.md
packages/abc/st/st.component.html
packages/abc/st/st.component.ts
packages/abc/st/st.interfaces.ts
packages/abc/st/test/base.spec.ts
packages/abc/st/test/st.spec.ts
packages/theme/system/ng/_drag.less
packages/theme/system/ng/index.less
src/styles/_demo.less

- close https://github.com/ng-alain/ng-alain/issues/1835
```
[ ] Bugfix
[x] Feature
```
```
[ ] Yes
[x] No
```

feat(abc:st): add `drag` property

---

TODO.md
schematics/ng-update/upgrade-rules/V19/index.spec.ts
schematics/ng-update/upgrade-rules/V19/index.ts
schematics/test.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

feat(cli): add declaration-property-value-no-unknown via ng update

---

packages/util/config/config.service.ts
packages/util/config/config.spec.ts

```
[ ] Bugfix
[ ] Feature
```
```
[ ] Yes
[ ] No
```

fix(util:config): support signal of `attach`

---

packages/form/src/utils.ts

```
[x] Bugfix
[ ] Feature
```
- 【受益人银行所在国家】和【受益人所在国家】都是下拉框，并且用了同样的异步数据源
- 【受益人所在国家】设置了 `readOnly: true`，导致【受益人银行所在国家】下拉框的数据受到影响
- 希望在底层用deepCopy解决
```
// html
depositcountry: {
type: "string",
title: "受益人银行所在国家",
ui: {
widget: "select",
allowClear: true,
placeholder: "请选择",
optionalHelp: "系统会根据所选国家判断是境内账户或境外账户",
showRequired: true,
showSearch: true,
serverSearch: true,
asyncData: (): …
```

fix(form:utils): replace getEnum with getCopyEnum in getData
